### ISSUE TITLE
DASDLS: various errors unexpectedly occur in certain situations

### ISSUE THREAD

**Issue by peter-sylvester** [SDL-Hercules-390/hyperion#393] opened 2021-05-13 10:00 UTC
Using dasdls with shadow files always provokes error 311 in cckddasd.c and cckddasd64.c

The inner loop strcmp for checking duplicate files do not check i != j.
___
_**Edit:** The originally reported problem was so poorly and inaccurately described and documented that it took a while to eventually figure out what the problem the author was attempting to report actually was. Please see comment **[841705811](https://github.com/SDL-Hercules-390/hyperion/issues/393#issuecomment-841705811) further below** for a description of the actual problem that the author was actually trying to report._

**Comment by Fish-Git** [comment] 2021-05-13 15:21
I have no idea what you're talking about.

**Comment by Fish-Git** [comment] 2021-05-14 23:20
Closing as PEBKAC (User Error).

**Comment by peter-sylvester** [comment] 2021-05-15 08:39
IMO the problem can be easily reproduced in the following way:
Take a cckd device with shadow file.
Allocate a dataset with secondary extents,and fill it so that a secondary extent is used
dasdls -info   zedisk .cckd -sf shadow*.cckd

**Comment by Fish-Git** [comment] 2021-05-15 13:49
> IMO the problem can be easily reproduced in the following way:

Please see: [**SUBMITTING PROBLEM REPORTS**](https://github.com/SDL-Hercules-390/hyperion/issues/373).

You failed to adequately describe/document the problem. We thus do not known (we do not understand) what your complaint is. We do not know (we do not understand) what your problem is.

It is rather difficult to fix a problem when one is never told what the problem actually is.

**dasdls works fine:**

```
Q:\CCKD\zOS 2.1> dir

 Volume in drive Q is DATA 003
 Volume Serial Number is EE45-1610

 Directory of Q:\CCKD\zOS 2.1

05/15/2021  06:28 AM    <DIR>          .
05/15/2021  06:28 AM    <DIR>          ..
06/22/2017  05:26 PM    <DIR>          CTCI
06/19/2017  02:59 AM    <DIR>          LCS
06/25/2017  03:01 AM    <DIR>          LCS #2
06/19/2017  03:03 AM    <DIR>          QETH
07/02/2017  10:33 PM    <DIR>          QETH #2
06/30/2015  07:15 AM       332,453,785 S1BBN1.comp
06/19/2017  03:52 AM            59,318 S1BBN1_Shadow_1.comp
05/15/2021  06:23 AM             1,808 S1BBN1_Shadow_2.comp
06/30/2015  07:16 AM         8,345,898 S1BBN2.comp
06/19/2017  03:52 AM             1,808 S1BBN2_Shadow_1.comp
11/11/2019  03:14 PM             1,808 S1BBN2_Shadow_2.comp
06/30/2015  07:17 AM         8,332,938 S1BBN3.comp
06/19/2017  03:52 AM             1,808 S1BBN3_Shadow_1.comp
11/11/2019  03:14 PM             1,808 S1BBN3_Shadow_2.comp
06/30/2015  07:50 AM     1,540,293,103 S1BLZ1.comp
06/19/2017  03:52 AM             1,808 S1BLZ1_Shadow_1.comp
11/11/2019  03:14 PM             1,808 S1BLZ1_Shadow_2.comp
06/30/2015  07:56 AM     2,375,117,328 S1BLZ2.comp
06/19/2017  03:52 AM             2,316 S1BLZ2_Shadow_1.comp
11/11/2019  03:14 PM             2,316 S1BLZ2_Shadow_2.comp
06/30/2015  07:58 AM       383,430,982 S1C511.comp
06/19/2017  03:52 AM            10,707 S1C511_Shadow_1.comp
11/11/2019  03:14 PM             1,808 S1C511_Shadow_2.comp

[...]

06/30/2015  10:54 AM       513,517,681 SARES1.comp
06/19/2017  03:52 AM             1,808 SARES1_Shadow_1.comp
11/11/2019  03:14 PM             1,808 SARES1_Shadow_2.comp
06/19/2017  03:53 AM                 6 _Fish README.txt
             127 File(s) 33,601,165,035 bytes
               7 Dir(s)  1,091,818,291,200 bytes free




Q:\CCKD\zOS 2.1> dasdls

HHC02499I Hercules utility dasdls - List DASD image file contents - version 4.3.0.10296-SDL-ga4db8213
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 27 2020 at 10:51:04
HHC02463I Usage: dasdls [-option [-option ... ]] ckdfile [sf=sfile]  [...]
HHC02463I   ckdfile:      input dasd image file
HHC02463I   sfile:        optional dasd image shadow file
HHC02463I options:
HHC02463I   -hdr          show column headers
HHC02463I   -dsnl[=n]     restrict dsname width
HHC02463I   -info         show F1 info
HHC02463I   -caldt        calendar date format
HHC02463I   -refdt        show last-reference date
HHC02463I   -expdt        show expiry date
HHC02463I   -yroffs[=n]   year offset
HHC02463I Note:
HHC02463I   Multiple images can be processed in the same run,
HHC02463I   but options must be specified ahead of each image.





Q:\CCKD\zOS 2.1> dasdls -info S1BBN1.comp sf=S1BBN1_Shadow_*.comp

HHC02499I Hercules utility dasdls - List DASD image file contents - version 4.3.0.10296-SDL-ga4db8213
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 27 2020 at 10:51:04

HHC00403I 0:0000 CKD file S1BBN1.comp: opened r/o
HHC00414I 0:0000 CKD file S1BBN1.comp: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832

VOLSER:  S1BBN1    "S1BBN1.comp"

SYS1.VTOCIX.S1BBN1                           14149 PS  F      2048  2048   0    15 100   1 TRK       0
SYS1.VVDS.VS1BBN1                            14149 VS  U            4096   0    30   3   1 TRK      15
IZU210.SIZUZFS.DATA                          13191 VS  U            4096   0  6300  -0   1 CYL      30
IZU210.GLOBAL.CSI.DATA                       13191 VS  U            4096   0    30  -0   1 CYL       1
IZU210.GLOBAL.CSI.INDEX                      13191 VS  U            4096   0     2  -2   1 TRK       1
IZU210.IZU210D.CSI.DATA                      13191 VS  U            4096   0    90  -0   1 CYL       1
IZU210.IZU210D.CSI.INDEX                     13191 VS  U            4096   0    45  -0   1 TRK       1
IZU210.IZU210T.CSI.DATA                      13191 VS  U            4096   0    90  -0   1 CYL       1
IZU210.IZU210T.CSI.INDEX                     13191 VS  U            4096   0    45  -0   1 TRK       1
IZU210.WBEM.ZFS.DATA                         13210 VS  U            4096   0  2250  -0   1 CYL      15
IZU210.ETC.ZOSMF.DATA                        14167 VS  U            4096   0   750   0   1 CYL       3
IZU210.VAR.ZOSMF.DATA                        14167 VS  U            4096   0  2700   0   1 CYL      20
IZU210.SIZUJCL                               13191 PO  FB       80 27920   0     4  95   1 BLK       2
IZU210.PROCLIB                               13191 PO  FB       80 27920   0     1  29   1 BLK       2
IZU210.AIZUFS                                13191 PO  VB      259 32760   0  3925   0   1 BLK    1105
IZU210.AIZUJCL                               13191 PO  FB       80 27920   0     4  95   1 BLK       2
IZU210.APROCLIB                              13191 PO  FB       80 27920   0     1  29   1 BLK       2
IZU210.SVSC.INSTALL                          13191 PO  FB       80  6160   0    15  27   1 CYL       2
IZU210.SVSC.MIS.SERVICE                      13191 PO  FB       80  8000   0    15  27   1 CYL       2
IZU210.SVSC.README                           13191 PO  FB       80  6160   0    15  21   1 CYL       2
IZU210.SMPMTS                                13191 PO  FB       80  8800   0     1   9   1 TRK      10
IZU210.GLOBAL.SMPPTS                         13283 PO  FB       80  6160   0    15   0   1 CYL     100
IZU210.SMPLTS                                13191 PO  U            6144   0     1   0   1 TRK      10
IZU210.SMPSCDS                               13191 PO  FB       80  8800   0     1  32   1 TRK      10
IZU210.SMPSTS                                13191 PO  FB       80  8800   0     1  32   1 TRK      10
IZU210.SBPXEXEC                              14100 PO  FB       80 27920   0    15   1   1 CYL       3
IZU210.ABPXEXEC                              14100 PO  FB       80 27920   0    15   1   1 CYL       3
IZU210.SIEALNKE                              14100 PO  U           32760   0    15   7   1 CYL       2
IZU210.AIEALNKE                              14100 PO  U           32760   0    15   7   1 CYL       2
IZU210.ISPLLIB                               13235 PO  U           23200   0     1  82   1 TRK       1
IZU210.SVSC.CONFIG                           13228 PO  FB       80  6160   0     3  90   1 TRK      10
Y.Y00.CD504B27.A13943A1.X00.VEW              14167 PS  FB      132 13200   0     1  46   1 BLK     100
Y.Y00.CD505016.H179F481.X00.VEW              14167 PS  FB      132 13200   0     2  51   1 BLK     100
CEA.Y00.CD507745.MCA1258C.X00.VEW            14167 PS  FB      132 13200   0     1  71   1 BLK     100
CEA.Y00.CD509EBC.A95FB8A3.X00.VEW            14167 PS  FB      132 13200   0     1  67   1 BLK     100
Y.Y00.CD504B27.A13943A1.X00.TRS              14167 PS  FB     1024 27648   0     1  13   1 TRK      25
Y.Y00.CD505016.H179F481.X00.TRS              14167 PS  FB     1024 27648   0     1  22   1 TRK      25
CEA.Y00.CD507745.MCA1258C.X00.TRS            14167 PS  FB     1024 27648   0     1  16   1 TRK      25
CEA.Y00.CD509EBC.A95FB8A3.X00.TRS            14167 PS  FB     1024 27648   0     1  16   1 TRK      25

End of dasdls; rc=0
```

**Comment by Fish-Git** [comment] 2021-05-15 13:58
Even your TITLE does not make any sense!

&nbsp; &nbsp; &nbsp; "**cchkdasd (64) always issue E 311 with SF**"

First, there is no Hercules utility called "**cchkdasd**".

Second, your follow-up post mentions _**dasdls**_, not "**cchkdasd**".

Third, what the heck does "**E 311**" mean?

Bottom line: you problem report is invalid. It does not make sense, and it does not describe any problem. Therefore there is nothing to be fixed. Nothing is broken.

**Comment by peter-sylvester** [comment] 2021-05-15 14:20
All the datasets in the example above have one extent only.

In cckddasd.c there is the code snippet

                if (strcmp (cckd_sf_name(dev, i),cckd_sf_name(dev2, j)) == 0)
                {
                    WRMSG (HHC00311, "E", LCSS_DEVNUM,  i, cckd_sf_name(dev,  i),
                                         SSID_TO_LCSS(dev2->ssid), dev2->devnum, j, cckd_sf_name(dev2, j));
                    return -1;
                }

I thought E 311  (error 311) would be ok. 

This message is issued by dasdls -info   whenever you have a dataset that has more than one extent on a device cckd device that has shadow files. 

The reason is that dasdls callls the cckd_sf_init routine a second time inside the chainf3 function.
Since the list of files already contains the shadow files, the message is triggered.

**Comment by Fish-Git** [comment] 2021-05-15 15:31
> All the datasets in the example above have one extent only.

```
Q:\CCKD64\zOS 2.3 (ADCD)> dasdls -info -hdr a3dbar.cckd64 sf=a3dbar_Shadow_*.cckd64

HHC02499I Hercules utility dasdls - List DASD image file contents - version 4.3.0.10296-SDL-ga4db8213
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 27 2020 at 10:51:04

HHC00476I 0:0000 CKD64 file a3dbar.cckd64: opened r/o
HHC00470I 0:0000 CKD64 file a3dbar.cckd64: model 3390-9 cyls 10017 heads 15 tracks 150255 trklen 56832

VOLSER:  A3DBAR    "a3dbar.cckd64"

Dsname                                       CREDT ORG RECFM LRECL BLKSZ Key  Trks%Use#Ext 2ndry_alloc
SYS1.VTOCIX.A3DBAR                           17307 PS  F      2048  2048   0    15 100   1 TRK       0
SYS1.VVDS.VA3DBAR                            17307 VS  U            4096   0    30   3   1 TRK      15
IBMUSER.S0W1.SPFTEMP0.CNTL                   17340 PS  FB       80   800   0     1   6   1 BLK     100
IBMUSER.S0W1.SPFLOG1.LIST                    17340 PS  VA      125   129   0     9   1   1 BLK     582
BLZ.#CUST.CLMTABL                            17308 PO  FB       80  3120   0    15   7   1 CYL       1
BLZ.#CUST.CLMLOG                             17308 PO  FB      255 32640   0    30   3   1 CYL       1
BLZ.#CUST.CLM002.CMD                         17308 PO  FB       80  3120   0     3  33   3 BLK       1
BLZ.#CUST.CLM002.UTILJOB                     17308 PO  FB       80  3120   0     2  50   2 BLK       5

End of dasdls; rc=0
```

There is no problem with dasdls. It appears to be working just fine.

**Comment by Fish-Git** [comment] 2021-05-15 18:33
@peter-sylvester

Okay, I've managed to trigger what I _believe_ you may have been trying to report.

I also fully understand that English is likely not your native tongue, and so might have difficulty accurately describing your problem as a result, just as I do sincerely apologize to you for my inability to understand you as a result. I do appreciate the challenge of trying to describe a problem in a language other than your own, and apologize for not initially understanding you.

I have done some additional testing with various different dasds and shadow files, and I believe I _**was**_ able to trigger the problem you were trying to report:

```
Q:\CCKD64\zOS 2.3 (ADCD)> dasdls -info -hdr a3dis1.cckd64 sf=a3dis1_Shadow_*.cckd64 > c:\users\fish\downloads\sss.txt 2>&1

HHC02499I Hercules utility dasdls - List DASD image file contents - version 4.3.0.10296-SDL-ga4db8213
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 27 2020 at 10:51:04

HHC00476I 0:0000 CKD64 file a3dis1.cckd64: opened r/o
HHC00470I 0:0000 CKD64 file a3dis1.cckd64: model 3390-9 cyls 10017 heads 15 tracks 150255 trklen 56832

VOLSER:  A3DIS1    "a3dis1.cckd64"

Dsname                                       CREDT ORG RECFM LRECL BLKSZ Key  Trks%Use#Ext 2ndry_alloc
SYS1.VTOCIX.A3DIS1                           17300 PS  F      2048  2048   0    15 100   1 TRK       0
SYS1.VVDS.VA3DIS1                            17300 VS  U            4096   0    30   3   1 TRK      15
EPH.AEPHPLIB                                 15261 PO  VB      255 27998   0     1  20   1 TRK       1
AOP.AAOPEXEC                                 15261 PO  FB       80 27920   0     2  90   1 TRK       1
IZU.AIZUFS                                   15261 PO  VB      259 32760   0  6770   0   1 TRK     470
SYS1.AFONTHFS                                17094 PO  VB      255 27998   0 27000 100   1 TRK    4163
AOP.AAOPHFS                                  15261 PO  VB      255 27998   0HHC00311E 0:0001 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0001 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
  2753 149   9 TRK     254
AOP.AAOPMENU                                 15261 PO  FB       80 27920   0     3  69   1 TRK       1
AOP.AAOPMOD1                                 15261 PO  U           32760   0   170 100   1 TRK      21
AOP.AAOPPENU                                 15261 PO  FB       80 27920   0    74  99   1 TRK       9
HLA.AASMMAC1                                 17116 PO  FB       80 27920   0    11  91   1 TRK       2
HLA.AASMMAC2                                 17116 PO  FB       80 27920   0     4  92   1 TRK       1
HLA.AASMMOD1                                 17116 PO  U           32760   0    35  94   2 TRK       4
HLA.AASMMOD2                                 17116 PO  U           32760   0    99 100   1 TRK      12
HLA.AASMPUT2                                 17116 PO  FB       80 27920   0   116  99   1 TRK      14
HLA.AASMSAM1                                 17116 PO  FB       80 27920   0    21  97   1 TRK       3
HLA.AASMSAM2                                 17116 PO  FB       80 27920   0    10  94   1 TRK       2
CBC.ACCNCMP                                  15261 PO  U           32760   0HHC00311E 0:0002 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0002 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
  4775   0   5 TRK     411
SYS1.AEAGJENU                                17116 PO  FB       80 27920   0     3  86   1 TRK       1
SYS1.AEAGMENU                                17116 PO  VB      255 27998   0     1  47   1 TRK       1
SYS1.AEAGMOD1                                17116 PO  U           32760   0     2  74   1 TRK       1
SYS1.AEAGSAM                                 17116 PO  FB       80 27920   0     1  31   1 TRK       1
SYS1.AACBCNTL                                15261 PO  FB       80 27920   0    24  97   1 TRK       3
SYS1.AADFMAC1                                15261 PO  FB       80 27920   0     1  53   1 TRK       1
SYS1.AADRLIB                                 15261 PO  U           32760   0    95 100   1 TRK      11
SYS1.AADRYLIB                                15261 PO  FB       80 27920   0     9  97   1 TRK       2
SYS1.AAXREXEC                                15261 PO  VB      255 27998   0    18 100   2 TRK       2
SYS1.ABDTCLI0                                15261 PO  FB       80 27920   0     3  74   1 TRK       1
SYS1.ABDTHELP                                15261 PO  FB       80 27920   0     2  81   1 TRK       1
SYS1.ABDTMAC                                 15261 PO  FB       80 27920   0   101  99   1 TRK      13
SYS1.ABDTMOD                                 15261 PO  U           32760   0    33  98   1 TRK       4
SYS1.ABDTMSG                                 15261 PO  FB       80 27920   0     1  43   1 TRK       1
SYS1.ABDTPNL0                                15261 PO  FB       80 27920   0     6  89   1 TRK       1
SYS1.ABDTSAMP                                15261 PO  FB       80 27920   0     9  96   1 TRK       2
SYS1.ABLSCLI0                                15261 PO  FB       80 27920   0   315  90   2 TRK      34
SYS1.ABLSKEL0                                15261 PO  FB       80 27920   0     6  97   1 TRK       1
SYS1.ABLSMSG0                                15261 PO  FB       80 27920   0     8  90   1 TRK       2
SYS1.ABLSPNL0                                15261 PO  FB       80 27920   0   354  89   2 TRK      40
CBC.ACCNSR1                                  15261 PO  FB       80 27920   0    61  99   1 TRK       8
CBC.ACCNSR2                                  15261 PO  FB       80 27920   0HHC00311E 0:0003 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0003 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
    25 150   8 TRK       3
SYS1.ABLSTBL0                                15261 PO  FB       80 27920   0     5  99   1 TRK       1
CBC.ACCNSR3                                  15261 PO  FB       80 27920   0HHC00311E 0:0004 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0004 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
    37 153   8 TRK       4
SYS1.ABMFMOD0                                15261 PO  U           32760   0    33  88   2 TRK       4
CBC.ACCNSR4                                  15261 PO  FB       80 27920   0HHC00311E 0:0005 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0005 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
    25 151   8 TRK       3
SYS1.ABPXEXEC                                15261 PO  FB       80 27920   0    40  98   2 TRK       4
CBC.ACCNSR5                                  15261 PO  FB       80 27920   0HHC00311E 0:0006 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0006 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
   114 103  16 TRK       6
SYS1.ABPXMENU                                15261 PO  FB       80 27920   0     9  94   1 TRK       2
SYS1.ABPXMOD1                                15261 PO  U           32760   0   364  94   3 TRK      35
CBC.ACLBDLL                                  15261 PO  U           32760   0    85 100   1 TRK      11
CBC.ACLBDLL2                                 15261 PO  U           32760   0   341   0   1 TRK      31
SYS1.ABPXPENU                                15261 PO  FB       80 27920   0    29  99   1 TRK       4
SYS1.ABPXSPC                                 15261 PO  U           32760   0     4  75   1 TRK       1
CBC.ACLBHFS1                                 15261 PO  VB      255 27998   0  5717  97   2 TRK     401
SYS1.ABPXTENU                                15261 PO  FB       80 27920   0     1  44   1 TRK       1
SYS1.ABPXXMLS                                15261 PO  VB      256 27998   0     3  85   1 TRK       1
SYS1.ACBDCLST                                15261 PO  FB       80 27920   0     1  94   1 TRK       1
SYS1.ACBDHENU                                15261 PO  U           32760   0   394 100   1 TRK      42
SYS1.ACBDMENU                                15261 PO  FB       80 27920   0    17  97   1 TRK       3
SYS1.ACBDMOD1                                15261 PO  U           32760   0   344  91   2 TRK      39
SYS1.ACBDMOD2                                15261 PO  U           32760   0     5  81   1 TRK       1
SYS1.ACBDPENU                                15261 PO  FB       80 27920   0    72 100   1 TRK       9
SYS1.ACBDTEMP                                15261 PO  FB       80 27920   0    15  96   1 TRK       2
SYS1.ACBDTENU                                15261 PO  FB       80 27920   0     1  95   1 TRK       1
SYS1.ACBRDBRM                                15261 PO  FB       80 27920   0HHC00311E 0:0007 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0007 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
    10 118   5 TRK       1
SYS1.ACBRMOD0                                15261 PO  U           32760   0   165  91   2 TRK      17
SYS1.ACCRHFS                                 15261 PO  VB      256 27998   0     2  95   1 TRK       1
SYS1.ACCRMOD                                 15261 PO  U           32760   0    22 100   1 TRK       3
SYS1.ACDMMOD0                                15261 PO  U           32760   0    47  99   1 TRK       6
SYS1.ACDRMODS                                15261 PO  U           32760   0     7  92   1 TRK       2
SYS1.ACDRTABL                                15261 PO  FB       80 27920   0   246 100   1 TRK      29
CBC.ACLBOBJ                                  15261 PO  FB       80 27920   0   110 100   1 TRK      13
SYS1.ACLMMOD0                                15261 PO  U           32760   0   270  90   2 TRK      28
CBC.ACLBSR1                                  15261 PO  FB      120 27960   0    15  96   1 TRK       2
CBC.ACTVMOD                                  15261 PO  U           32760   0    10  98   1 TRK       2
SYS1.ACMDLIB                                 15261 PO  U           32760   0    35  92   2 TRK       4
CBC.ACTVSRC                                  15261 PO  FB       80 27920   0     2  90   1 TRK       1
SYS1.ACSSLIB                                 15261 PO  U           32760   0    76 100   1 TRK       9
CDS.ACDSHFS                                  15261 PO  VB      255 27998   0   485 100   1 TRK      57
SYS1.ACUNHF                                  15261 PO  VB      255 27998   0     9  99   1 TRK       1
SYS1.ACUNJCL                                 15261 PO  FB       80 27920   0     2  92   1 TRK       1
SYS1.ACUNLOCL                                15261 PO  FB       80 27920   0   834 100   1 TRK      98
CDS.ACDSSAMP                                 15261 PO  FB       80 27920   0     2  92   1 TRK       1
CEE.AAFHMOD1                                 15261 PO  U           32760   0   144 100   1 TRK      17
CEE.AAFHSRC1                                 15261 PO  FB       80 27920   0    15  97   1 TRK       3
CEE.ACEEMOD1                                 15261 PO  U           32760   0   525  93   3 TRK      47
SYS1.ACUNMAC                                 15261 PO  FB       80 27920   0HHC00311E 0:0008 CCKD file[1] a3dis1_Shadow_1.cckd64: shadow file name collides with 0:0000 file[1] a3dis1_Shadow_1.cckd64
HHC00007I Previous message from function 'cckd64_sf_init' at cckddasd64.c(3165)
HHC00300E 0:0008 CCKD file: error initializing shadow files
HHC00007I Previous message from function 'cckd64_dasd_init_handler' at cckddasd64.c(90)
    97 137   7 TRK      10
SYS1.ACUNMENU                                15261 PO  VB      259 27998   0     1  73   1 TRK       1
SYS1.ACUNMJPN                                15261 PO  VB      259 27998   0     1  20   1 TRK       1
SYS1.ACUNMOD                                 15261 PO  U           32760   0    73  91   2 TRK       8
CEE.ACEEMOD2                                 15261 PO  U           32760   0 22958   0   2 TRK    2260
SYS1.ACUNSAMP                                15261 PO  FB       80 27920   0    36  99   1 TRK       5
SYS1.ACUNTBL                                 15261 PO  FB      256 27904   0 42033  90   2 TRK    4152
SYS1.AFOMHDRS                                15261 PO  FB       80 27920   0    19  99   1 TRK       3
CEE.ACEESRC1                                 15261 PO  FB       80 27920   0   146 100   1 TRK      18
CEE.ACEESRC2                                 15261 PO  FB      120 27960   0   100  99   1 TRK      12
CEE.ACEESRC3                                 15261 PO  FB      120 27960   0    16 100   1 TRK       3
CEE.AEDCCPP1                                 15261 PO  FB       80 27920   0    15  95   1 TRK       2
CEE.AEDCMOD1                                 15261 PO  U           32760   0  1372  90   2 TRK     145
CEE.AEDCMOD2                                 15261 PO  U           32760   0    10 100   1 TRK       2
CEE.AEDCMSEP                                 15261 PO  FB      150 27900   0     1  55   1 TRK       1
CEE.AEDCOBJ1                                 15261 PO  FB       80 27920   0     7  86   1 TRK       2
CEE.AEDCSRC6                                 15261 PO  FB       80 27920   0   612 100   1 TRK      77
CEE.AIBMSRC3                                 15261 PO  FB       80 27920   0    32  97   3 TRK       4
CEE.AIGZMOD1                                 15261 PO  U           32760   0   124  90   2 TRK      13
CEE.AIGZSRC1                                 15261 PO  FB       80 27920   0    27  99   1 TRK       4
CSF.ACSFCLI0                                 15261 PO  FB       80 27920   0    26  99   1 TRK       4
CSF.ACSFHDRS                                 15261 PO  FB       80 27920   0     5  87   1 TRK       1
CSF.ACSFMOD1                                 15261 PO  U           32760   0     1  31   1 TRK       1
CSF.ACSFOBJ                                  15261 PO  FB       80 27920   0     1  36   1 TRK       1
CSF.ACSFSKL0                                 15261 PO  FB       80 27920   0     1  62   1 TRK       1
CSF.ACSFTLIB                                 15261 PO  FB       80 27920   0     1  27   1 TRK       1
EOY.AEOYBENU                                 15261 PO  FB       80 27920   0     1  56   1 TRK       1
CSQ800.SMPLTS                                14195 PO  U            6144   0    51   2   1 TRK      10
CSQ800.SMPMTS                                14195 PO  FB       80  8800   0     1   9   1 TRK      10
CSQ800.SMPSCDS                               14195 PO  FB       80  8800   0     1  32   1 TRK      10
CSQ800.SMPSTS                                14195 PO  FB       80  8800   0     1  32   1 TRK      10
CSQ901.SMPMTS                                17012 PO  FB       80  8800   0     1   9   1 TRK      10
CSQ901.SMPLTS                                17012 PO  U            6144   0     9  11   1 TRK      10
CSQ901.SMPSCDS                               17012 PO  FB       80  8800   0     1  69   1 TRK      10
CSQ901.SMPSTS                                17012 PO  FB       80  8800   0     1  32   1 TRK      10
MVS.GLOBAL.CSI.DATA                          17116 VS  U            4096   0  3900   0   1 CYL      25
MVS.GLOBAL.CSI.INDEX                         17116 VS  U            4096   0    30   3   1 CYL       1
MVS.MVSD.CSI.DATA                            17116 VS  U            4096   0  3000   0   1 CYL      25
MVS.MVSD.CSI.INDEX                           17116 VS  U            4096   0    30   3   1 CYL       1
MVS.MVST.CSI.DATA                            17116 VS  U            4096   0  3000   0   1 CYL      25
MVS.MVST.CSI.INDEX                           17116 VS  U            4096   0    30   3   1 CYL       1
CSQ800.CSQ800D.CSI.DATA                      14198 VS  U            4096   0   135   1   1 CYL       1
CSQ800.CSQ800D.CSI.INDEX                     14198 VS  U            4096   0    45   2   1 TRK       1
CSQ800.CSQ800T.CSI.DATA                      14198 VS  U            4096   0   240   0   1 CYL       1
CSQ800.CSQ800T.CSI.INDEX                     14198 VS  U            4096   0    45   2   1 TRK       1
CSQ901.CSQ901D.CSI.DATA                      17012 VS  U            4096   0   165   1   1 CYL       1
CSQ901.CSQ901D.CSI.INDEX                     17012 VS  U            4096   0    45   2   1 TRK       1
CSQ901.CSQ901T.CSI.DATA                      17012 VS  U            4096   0   270   0   1 CYL       1
CSQ901.CSQ901T.CSI.INDEX                     17012 VS  U            4096   0    45   2   1 TRK       1

End of dasdls; rc=0
```
&nbsp;
The good news is I was able to find the problem (poorly written dasdls!) and a fix will be forthcoming.

Thank you for reporting this problem (or rather, thank you for _TRYING_ to report this problem!).

**Comment by Fish-Git** [comment] 2021-05-15 19:03
FYI: the problem is not always triggered, even for volumes that have datasets with multiple extents. I did not bother to try and determine the exact condition(s) that cause it to occur, but I believe it is when a dataset has multiple extents and updates to the dataset exist in multiple shadow files. (I think.)

The final resolution was to simply fix dasdls's overall design to only open a given dasd image file _once_ instead of multiple times like the way it was currently erroneously doing. `(*)`

`(*)` _I suspect the original author of dasdls did not fully understand how shadow files actually worked and thus wrote his program to open the dasd image file **again** (i.e. multiple times!) during processing. instead of just once at the beginning. But that's just a guess of course. We'll ultimately never know what the original author was thinking and it is largely immaterial anyway. The only important thing is that the problem has now been identified and fixed and the commit will be forthcoming in due course._

**Comment by Fish-Git** [comment] 2021-05-17 00:49
Fixed by commit 71245340c5c0273922b99f57799da5b97964f6da.

Peter? (@peter-sylvester) Can you please confirm that your problem is now fixed? Thanks!

**Comment by peter-sylvester** [comment] 2021-05-17 04:06
Yes. Probmem is gone.   Great.

**Comment by Fish-Git** [comment] 2021-05-17 12:21
> > Peter? Can you please confirm that your problem is now fixed?
> Yes. Probmem is gone.

Thanks. Closing.

**Closed as completed by Fish-Git** 2021-05-17 12:21 UTC
Labels: BUG
