### ISSUE TITLE
z/VM 6.2 and 6.3 with latest SDL leads to non-IPLable system due abend on IPL (no more swap space)

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#149] opened 2018-10-18 19:32 UTC
I use z/VM 6.2 and 6.3 with non-compressed disks (due to mod 9 requirement). When I IPL a freshly installed system everything is fine. I let the system up and running for  a few days, upload some text files and start and stop guests, and everything is still fine.

But when I then shutdown the system gracefully, and try to IPL it again, it abends saying "no more space on swap volume".

This doesn't' happen with other versions of Hercules or Hyperion.

Thanks.

**Comment by Fish-Git** [comment] 2018-12-04 17:42
I don't have z/VM 6.2, but I _do_ have z/VM 6.3, so I would like to try and reproduce this problem if possible.

Is the stopping/starting of guests and/or the uploading of text files a requirement in order to reproduce this problem? Or can I just leave the system up and running (essentially idle) for a few days?  If not, what type of guests are you stopping/starting and what type of text files are you uploading (how large and to which guest, etc). As I said, I would like to try and reproduce this problem if possible, but I need to know the parameters for doing so.

Does the same problem occur when you use _compressed_ dasd images instead of non-compressed?

**Comment by Fish-Git** [comment] 2018-12-04 19:13
It appears this issue might be a duplicate of issue #154: "[z/VM 6.3 fails to re-IPL](https://github.com/SDL-Hercules-390/hyperion/issues/154)", so I am going to close this issue and mark it as Duplicate.

If it turns out that this is a completely different issue then either I or you can re-open it again.

**Closed by Fish-Git** 2018-12-04 19:13 UTC
Labels: BUG, Researching...
