### ISSUE TITLE
10 seconds intermittent delay with multiple paths to a DASD device

### ISSUE THREAD

**Issue by SE20225** [SDL-Hercules-390/hyperion#624] opened 2024-02-12 15:53 UTC
I have an interest in the 370 style multiprocessors running MVS (now TK5 with an IOGEN to reduce the number of UCBs, add up to 4 paths to DASD (the MVS/370 maximum, two from each processor) and bring in the CRH-function, which is of special interest although it is not involved in the 'problem' discussed here. (CRH is to provide function to handle I/O which is only physically connected to the processor that was 'lost' due to a HW problem.)

On the initial attempts it was suggested that I achieve multiple paths by specifying like:

>029F 3390 dasd/tk5res.390
>1:029F 3390 localhost::029F

but this caused some intermittent malfunctions. Instead I now specify like:

>0F9F 3390 dasd/tk5res.390
>0:029F 3390 localhost::0F9F
>1:029F 3390 localhost::0F9F

where the F9F device is not used from the MVS system. The malfunctions (false EQCs and other) are gone, but instead one can observe a few 10 sec delays.

The first unexpected delay occurs already while the config is created is 10 seconds per additional path established.  I do not know how or what to trace at this time and there is no I/O from the virtual machine at this time. 

In the book I found the command `msglevel +dasd +channel`, but they generate an error message. 

Occasionally there is also a 10 seconds delay when the system is up and running and all cases I have looked into occur when MVS happens to swtich from CPU 0 to CPU1 (or the other way around) for the next I/O to the traced device (which is the syssres volume). PURGE (cached tracks in the DASD sharing scheme) processing is always active at the time. But when scanning the trace there are also occasions of switching to the other CPU with no delays.

I also noted that 10 seconds appear in the config file and changed TIMERINT to 5000 or cckd GCINT to 5 but these 10 seconds delay remained unchanged.

Could this be a tuning problem?   With cache etcetera?  

The delay during machine establishment is 16:23:26 to 16:23:36 and the traced delay when the TSO user is logged on is from 16:28:24 to 16:28:33. The delay is clearly noticeable for the TSO user and  sometimes console commands are delayed.  At 16:25:48 is an example of a quick switch to the other CPU.

The documentation provided in the below DELAY.zip attachment is: 

* The config file
* The Hercules log
* The MVS log

The delay during configuration processing should be easy to recreate since no  host code is (yet) involved.  It might have a different cause though!  

Anders Edlund    andersedlund@telia.com

* [DELAY.zip](https://github.com/SDL-Hercules-390/hyperion/files/14241768/DELAY.zip)

**Comment by SE20225** [comment] 2024-02-12 15:57
Adding the actual doc!

[DELAY.zip](https://github.com/SDL-Hercules-390/hyperion/files/14240640/DELAY.zip)

**Comment by Fish-Git** [comment] 2024-02-12 21:21
> Instead I now specify like:
> 
> > 0F9F 3390 dasd/tk5res.390
> > 0:029F 3390 localhost::0F9F
> > 1:029F 3390 localhost::0F9F
> 
> where the F9F device is not used from the MVS system. The malfunctions (false EQCs and other) are gone, but instead one can observe a few 10 sec delays.

> The first unexpected delay occurs already while the config is created is 10 seconds per additional path established. I do not know how or what to trace at this time and there is no I/O from the virtual machine at this time.

> The delay during configuration processing should be easy to recreate since no host code is (yet) involved.

I will try to reproduce the startup delay that occurs when Hercules is first started but before any IPL, since that should be pretty easy to reproduce since all of my test dasds can be dummy/empty volumes since I won't be IPLing anything.

**Comment by Fish-Git** [comment] 2024-02-13 22:07
_**GOOD NEWS!**_

I was able to reproduce the 10-second delay problem and I have a fix for it!

I will be committing it within the next day or so. Possibly later tonight.

**Comment by Fish-Git** [comment] 2024-02-14 05:04
Fixed by commit 79a14889f3602d28e376aa2897b224d523c58ca9.

Closing.

**Closed as completed by Fish-Git** 2024-02-14 05:04 UTC
Labels: BUG

**Comment by SE20225** [comment] 2024-02-15 21:34
I found the changes you had made on the git sysstem and edited the same changes into my source and rebuilt Hercules. 
Both reported problems are gone. I guess the times lowered are not really TIMEOUTs byt rather the time before anyther attempt. As a TSO user one no longer notices any unusual delay.   Thanks !

**Comment by Fish-Git** [comment] 2024-02-16 04:47
> Both reported problems are now gone!

That's good to hear!

> I guess the lowered times are not really TIMEOUTs, but rather the time before another attempt.

Correct.

> As a TSO user, one no longer notices any unusual delays! Thanks!

You are very welcome, Anders. &nbsp;`:)`
