### ISSUE TITLE
Crashes with "ctc debug" commands

### ISSUE THREAD

**Issue by racingmars** [SDL-Hercules-390/hyperion#536] opened 2022-12-29 08:53 UTC
**Hercules version**: 4.5.0.10830-SDL-g58578601
**Host OS**: Arch Linux x86_64. Linux kernel version 6.1.1-arch1-1

When I use Hercules console commands such as `ctc debug on 502` and `ctc debug off 502`, things work as expected. However, if I enter partial commands such as `ctc debug` or `ctc debug off`, Hercules crashes with:

```
    +++ OOPS! +++

Hercules has crashed! (Segmentation fault)
```

This also happens with what I believe to be a complete valid command, `ctc debug on all`.

This is reproducible with the following minimal hercules.cnf file:

```
0502 CTCE 15620 127.0.0.1 15600
```

**Expected behavior**: if the command supplied is incomplete or requires more arguments, I would expect an error message, not a crash. Furthermore, the `help ctc` text suggests to me that `ctc debug on` and `ctc debug off` (without optional device number or `ALL` keyword) should be valid.

**Comment by Fish-Git** [comment] 2022-12-29 09:32
Hi Matthew!

I was able to reproduce the crash and am working on a fix right now. Thank you for reporting this.

While I have not completed my analysis yet, I believe the bug is being caused by the fact that the device in question has not established a connection to the other system yet, and thus has not fully initialized yet. (Some internal device fields are still NULL.) I suspect if you try the same thing _after_ the device has finished initializing (i.e. has finished connecting to the other system) the crash would probably not occur. But I will try to confirm that.

In any case, the problem is being actively looked into and a fix for it will be forthcoming.

**Comment by Fish-Git** [comment] 2022-12-29 11:20
Fixed by commit 0afad3bdc3fccbc25b25170bad76c2e602342283.

Closing.

**NOTE:** &nbsp;As it turns out, the crash was _not_ caused by the CTCE device not being connected. It would have also crashed even if it _was_ already connected. The bug was actually caused by some missing code for CTCE devices in the `ctc debug` command itself, causing it to be erroneously handled / processed / treated as a _PTP_ device instead of a CTCE device. &nbsp;_(Oops!)_

**Closed as completed by Fish-Git** 2022-12-29 11:20 UTC
Labels: BUG

**Comment by Fish-Git** [comment] 2022-12-29 11:23
P.S. To get the fix you will of course need to do a `git pull` and then rebuild Hercules. Otherwise you'll just have to wait until the next release.

**Comment by Fish-Git** [comment] 2022-12-29 11:25
P.S. \#2: I also added support for entering the `ctc debug` command by itself _(i.e. without any other operands)_ to list the current CTC debugging state for all CTC devices.

**Comment by racingmars** [comment] 2022-12-29 21:13
Thanks Fish! I've pulled the develop branch and `ctc debug ...` is behaving perfectly now.
