### ISSUE TITLE
Program interrupt 03B against CMPSC 

### ISSUE THREAD

**Issue by MartinTr2** [SDL-Hercules-390/hyperion#475] opened 2022-02-23 10:29 UTC
### Problem:

Program under VSE 5.2 abends with program interrupt 03B against a CMPSC instruction.

The dump prepared by op-sys has all areas used/addressed in it:

```
R2- see Herc dump further down
R4- see Herc dump further down
R1- x'60' bytes 
00425000 01000000 00000000 01010000 00000000 01020000 00000000 01030000 00000000   10   ................................
00425020 01040000 00000000 01050000 00000000 01060000 00000000 01070000 00000000        ................................
00425040 01080000 00000000 01090000 00000000 010A0000 00000000 010B0000 00000000  
```

### Information from Herc console:

```
HHC00801I Processor CP00: Region-third-translation exception code 003B ilc 4
HHC02324I PSW=0715100080000000 00000000040978D4 INST=B2630024 CMPSC 2,4                    cmpsc_2012
HHC02326I V:0000000000400848:K:16=79E7E7E7 E7790000 00000000 00000000  `XXXX`..........
HHC02326I V:0000000000402359:K:16=1E4E73 9CE739C7 9420E7D9 4A70A7A7 A7 .+..X.Gm.XR..xxx
HHC02269I R0=0000000000002300 R1=0000000080425000 R2=0000000000400848 R3=0000000000000050
HHC02269I R4=0000000000402359 R5=000000000000000D R6=0000000000400958 R7=0000000000388614
HHC02269I R8=00000000000D2062 R9=00000000A04005E0 RA=000000000040207A RB=000000000040107A
HHC02269I RC=000000006040007A RD=0000000000401F20 RE=0000000000400718 RF=00000000840978B4
HHC02271I C0=000000000D84EE40 C1=0000000001000004 C2=000000000005FC00 C3=0000000040400001
HHC02271I C4=0000000000000001 C5=0000000001138040 C6=0000000010000000 C7=0000000001000004
HHC02271I C8=0000000000000000 C9=0000000000000000 CA=0000000000000000 CB=0000000000000000
HHC02271I CC=0000000000000000 CD=0000000001000004 CE=00000000C0081136 CF=000000000005EE40
```

### Hercules version as reported during start:

```
HHC01413I Hercules version 4.4.0.0-SDL-gbf377f63 (4.4.0.0)
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I Built using Hercules-Helper (version: v0.9.6-84-g0b13f4b)
HHC01415I Build date: Dec 21 2021 at 16:14:33
HHC01417I Built with: GCC 8.3.0
HHC01417I Build type: GNU/Linux x86_64 host architecture build
```

**Comment by Fish-Git** [comment] 2022-02-23 17:47
> Program under VSE 5.2 abends with program interrupt 03B against a CMPSC instruction.

How do you know it abended? What are you basing this on? Was a message issued to the z/VSE operator console _saying_ your job abended? Did your job listing report that your job (program) abended?

A Region-third-translation exception (code 003B) is a completely normal thing. It is very similar to a page-fault, and is normally something to not worry about and something that should _not_ normally cause a program to abend.

Are you perhaps simply _presuming_ that your job/program abended simply because you are seeing the Hercules message? Such messages are usually automatically filtered out by Hercules (are suppressed) and not displayed. What [**`OSTAILOR`**](https://sdl-hercules-390.github.io/html/hercconf.html#OSTAILOR) value are you using?

> The dump prepared by op-sys has all areas used/addressed in it:
> 
> ```
> R2- see Herc dump further down
> R4- see Herc dump further down
> R1- x'60' bytes 
> 00425000 01000000 00000000 01010000 00000000 01020000 00000000 01030000 00000000   10   ................................
> 00425020 01040000 00000000 01050000 00000000 01060000 00000000 01070000 00000000        ................................
> 00425040 01080000 00000000 01090000 00000000 010A0000 00000000 010B0000 00000000  
> ```

May we see the _entire_ dump please? &nbsp;The above does _not_ look like an operating system dump! &nbsp;It looks like you simply copy & pasted a few lines. &nbsp;May we see the _**complete** (entire)_ dump please? _(from beginning to end?)_

Or better, may we see the entire _**job listing**_ itself instead?  The one containing the report that your job abended and which contains the dump itself?

Thanks!

_(It is **very** unlikely that the `CMPSC` instruction is buggy. It is probably one of the most thoroughly tested instructions in all of Hercules!)_

**Comment by MartinTr2** [comment] 2022-02-23 18:48
Fish, I understand what you are saying and will send dump of partition as VSE produced it when i am near to the PC ( around 23:00 my time). However, the compress variant may not be used that often in VSE- the uncompress variant is used very often. The code in question ist not available in source (IBM OCO). The function i used was last used by me in 1996 on real iron.The data (as adress by R1) is from the dump.Martinfrom a mobile=brief and fill of typosAm 23.02.2022 18:47 schrieb Fish-Git ***@***.***>:



Program under VSE 5.2 abends with program interrupt 03B against a CMPSC instruction.



How do you know it abended? What are you basing this on? Was a message issued to the z/VSE operator console saying your job abended? Did your job listing report that your job (program) abended?

A Region-third-translation exception (code 003B) is a completely normal thing. It is very similar to a page-fault, and is normally something to not worry about and something that should not normally cause a program to abend.

Are you perhaps simply presuming that your job/program abended simply because you are seeing the Hercules message? Such messages are usually automatically filtered out by Hercules (are suppressed) and not displayed. What OSTAILOR value are you using?



The dump prepared by op-sys has all areas used/addressed in it:

R2- see Herc dump further down

R4- see Herc dump further down

R1- x'60' bytes 

00425000 01000000 00000000 01010000 00000000 01020000 00000000 01030000 00000000   10   ................................

00425020 01040000 00000000 01050000 00000000 01060000 00000000 01070000 00000000        ................................

00425040 01080000 00000000 01090000 00000000 010A0000 00000000 010B0000 00000000  





May we see the entire dump please?  The above does not look like an operating system dump!  It looks like you simply copy & pasted a few lines.  May we see the complete (entire) dump please? (from beginning to end?)

Or better, may we see the entire job listing itself instead?  The one containing the report that your job abended and which contains the dump itself?

Thanks!

(It is very unlikely that the CMPSC instruction is buggy. It is probably one of the most thoroughly tested instructions in all of Hercules!)

**Comment by Fish-Git** [comment] 2022-02-23 19:57
> I understand what you are saying and will send dump of partition as VSE produced it when I am near to the PC (around 23:00 my time).

Thank you. The dump should contain everything needed to reproduce the problem. (The dictionaries and input and output buffers are the most important.)

> The code in question is not available in source (IBM OCO).

I do not need to see IBM's code. I only need to see what it was trying to do and what data it was using (input and output buffers and dictionaries, etc). With that information it is a very simple matter to reproduce _exactly_ what the instruction was trying to do.

> The data (as addressed by R1) is from the dump.

Understood. But that is not enough. I need to see _**everything**_. I need to see the _exact_ input buffer contents (including its alignment, i.e. what boundary it was aligned on (byte, fullword, etc)), as well as the exact output buffer contents (including its boundary alignment as well), and the same thing for the dictionary that was using too (i.e. its _exact_ contents and how it too was aligned).

The actual compression or expansion parameters that were passed to (used by) the instruction itself (CBN, CDSS, dictionary format, etc) can be easily determined by simply looking at GR0 and GR1 of course.

But it's the actual input, output and dictionary buffer contents and alignment that is most important, which is what the dump should tell us. That's why I need to see the dump.

I  will likely also eventually need to see the Control Registers, Access Registers and all DAT tables too, since, according to the PSW, the instruction was executed in DAT 31-bit Secondary-space mode, and IMO, that is the most likely place for the bug (if there is one) to exist.

That is to say, I'm _doubting_ the problem is with the `CMPSC` instruction, but I want to be 100% certain of that before proceeding. Instead, I suspect the bug _(if there even is one!)_ is more likely in Herc's DAT logic somewhere. [We've had trouble with it before](https://github.com/SDL-Hercules-390/hyperion/issues/338).

**Comment by MartinTr2** [comment] 2022-02-23 23:13
Here is the dump and the JCL used to produce it.... the ODST parm in POWER JECL is unique to my machine - as well as the display of the bear (not relevant here) ....also JCL has SETPARM ...leftovers from debugging ...no relevance here.
[TESTJCL.TXT](https://github.com/SDL-Hercules-390/hyperion/files/8128419/TESTJCL.TXT)
[TESTLST.TXT](https://github.com/SDL-Hercules-390/hyperion/files/8128420/TESTLST.TXT)

**Comment by MartinTr2** [comment] 2022-02-24 08:30
Fish,
here is more 

>> I will likely also eventually need to see the Control Registers, Access Registers 

in the dump already

>> and all DAT tables too, 

that will become tricky- haven't seen them in ages since,

>>  according to the PSW, the instruction was executed in DAT 31-bit 

Yes EA/BA (bit 31 32) are 01 

>> Secondary-space mode, 

where do you see that? AS CC (16-19) is 00 01. That is in my book primary  space mode (with T on) and whatever condition code. 

If you have a hard time reproducing it, I can any time even with whatever diagnostic you want to be added.

Martin

**Comment by Fish-Git** [comment] 2022-02-24 09:17
> > Secondary-space mode,
> 
> Where do you see that? AS CC (16-19) is 0001. That is in my book primary space mode (with T on) and whatever condition code.

Yeah, my bad. Sorry. I was seeing things. I saw the `10` in the PSW (`071510...`) and my brain misinterpreted it for the AS field (AS 10 = Secondary). Careless mistake. Sorry.

> If you have a hard time reproducing it, I can any time even with whatever diagnostic you want to be added.

Thanks. I ran my **[cmpsctst tool](https://github.com/Fish-Git/cmpsctst#readme)** against the values your z/VSE was using, and it worked perfectly of course, but then we already knew that was going to be the case. cmpsctst only tests the logic of the instruction itself, not Hercules's address translation logic, which is where the problem obviously lies.

So now I need to build you a special debug version of Hercules for you to try, with special code to try and capture what `translate_addr` is doing. That's going to take me a short while of course _(day or three?)_, so hang loose for a bit, and I'll come knock at you when it's ready. Cool?

**Comment by MartinTr2** [comment] 2022-02-24 09:42
If I can be of any help (patching the offending code  to whatever included) - let me know. No need to hurry- I haven't used this for 20 years- and apparently nobody else in VSE land every does it on herc.

**Comment by MartinTr2** [comment] 2022-02-24 15:01
I looked again at the registers and tried just one little test: extra LA (4110 1000) so that the high order bit is off.... It works. So my conclusion: the handling of R1 in CMPSC does not ignore high order bit when in 31 bit mode (or VSE does it wrong)...

**Comment by Fish-Git** [comment] 2022-02-24 20:10
> I looked again at the registers and tried just one little test: extra LA (4110 1000) so that the high order bit is off.... It works. So my conclusion: the handling of R1 in CMPSC does not ignore high order bit when in 31 bit mode (or VSE does it wrong)...

Interesting! 

I will take a close look at CPMSC's logic!

**Comment by Fish-Git** [comment] 2022-02-24 20:58
_**\*\* &nbsp;BINGO!&nbsp; \*\***_

Please apply the following patch and rebuild Hercules and confirm that the problem has now been fixed:

```diff
From: Fish (David B. Trout) <fish@infidels.org>
Date: Thu, 24 Feb 2022 12:19:42 -0800
Subject: Fix missing ADDRESS_MAXWRAP in CMPSC instruction

--- hyperion-1/cmpsc_2012.c	2022-02-19 16:03:31.312939500 -0800
+++ hyperion-0/cmpsc_2012.c	2022-02-24 12:12:44.868200100 -0800
@@ -1200,7 +1200,7 @@
 
 #if defined( FEATURE_PER_ZERO_ADDRESS_DETECTION_FACILITY )
     if (0
-        || GR_A( 0,  regs ) == 0
+        || GR_A( 1,  regs ) == 0
         || GR_A( r1, regs ) == 0
         || GR_A( r2, regs ) == 0
     )
--- hyperion-1/cmpscmem.c	2022-01-06 16:29:25.077416900 -0800
+++ hyperion-0/cmpscmem.c	2022-02-24 12:16:33.858325900 -0800
@@ -696,13 +696,13 @@
     pCMPSCBLK->r1       =  r1;
     pCMPSCBLK->r2       =  r2;
 
-    pCMPSCBLK->pOp1     = GR_A( r1,   regs );
-    pCMPSCBLK->pOp2     = GR_A( r2,   regs );
+    pCMPSCBLK->pOp1     = GR_A( r1,   regs ) & ADDRESS_MAXWRAP( regs );
+    pCMPSCBLK->pOp2     = GR_A( r2,   regs ) & ADDRESS_MAXWRAP( regs );
     pCMPSCBLK->nLen1    = GR_A( r1+1, regs );
     pCMPSCBLK->nLen2    = GR_A( r2+1, regs );
 
     GR0 = regs->GR_L( 0 );
-    GR1 = GR_A( 1, regs );
+    GR1 = GR_A( 1, regs ) & ADDRESS_MAXWRAP( regs );
 
 //  pCMPSCBLK->e        = (GR0 >>  8) & 0x01;   // (no such field)
     pCMPSCBLK->f1       = (GR0 >>  9) & 0x01;
```

If the above fixes the problem (which I suspect it will), I'll commit it to the repository.

Thanks!

**Comment by MartinTr2** [comment] 2022-02-24 21:12
Fish, I am not familiar with that format- do the colors imply anything (remove red/ add green or whatever)? 

I will check tomorrow morning - so if you have any advise for a mainframe only person- let it out now.

Thank you anyway for finding this so fast

Martin

**Comment by Fish-Git** [comment] 2022-02-24 21:21
Martin,

1. Copy the above lines and place them into a file called "cmpsc.patch" (or whatever name desired).
2. Place that patch file in the Hercules source directory (just to make things easier).
3. Use the command "patch -i cmpsc.patch" to apply the patch to the Hercules source.
4. Rebuild Hercules.

**Comment by Fish-Git** [comment] 2022-02-24 21:28
https://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html/sn-Fixing_the_Code-What_is_a_Patch.html

https://www.oreilly.com/library/view/git-pocket-guide/9781449327507/ch11.html

**Comment by wrljet** [comment] 2022-02-24 21:32
> Martin,
> 
>     1. Copy the above lines and place them into a file called "cmpsc.patch" (or whatever name desired).
>     2. Place that patch file in the Hercules source directory (just to make things easier).
>     3. Use the command "patch -i cmpsc.patch" to apply the patch to the Hercules source.
>     4. Rebuild Hercules.

May I add... I noticed in the logs that Martin had used Hercules-Helper to do his build.
In that situation, you can apply the patch in the `hyperion` directory (with all the C source code).
Then, to rebuild with those changes, using your existing setup/config:

```
cd build
make
make check
make install
```

Please do not hesitate to ask for help.
Bill

**Comment by Fish-Git** [comment] 2022-02-24 21:44
> Do the colors imply anything (remove red/ add green or whatever)?

Essentially, yes.

Basically, the "---" and "+++" lines identify the file to be patched, the "@@" lines tell you the line number where the modifications are to be made, and the '-' and '+' signs in the first column of a line means "delete this line" and "add this line" respectively.

The other lines (that _don't_ have a +/-/@ in the first column) are there simply for context (so you know you're patching the right spot).

Patch files are created via the `diff` tool, and applied via the `patch` tool.

HTH

**Comment by MartinTr2** [comment] 2022-02-25 09:02
It does not verify. My understanding of C is near zero and I do not dare to correct this.

The files created (by me and the patch-cmd) are attached. (had to add .txt to convince github to accept them) 

note: the patch against  "cmpscmem.c" was apparently successful (judging by the change-date  not by looking at code)

3 files follow

[cmpsc_2012.c.orig.txt](https://github.com/SDL-Hercules-390/hyperion/files/8139890/cmpsc_2012.c.orig.txt)
[cmpsc_2012.c.rej.txt](https://github.com/SDL-Hercules-390/hyperion/files/8139891/cmpsc_2012.c.rej.txt)
[cmpsc.patch.txt](https://github.com/SDL-Hercules-390/hyperion/files/8139892/cmpsc.patch.txt)

**Comment by Fish-Git** [comment] 2022-02-25 11:06
> It does not verify.

(Oops!) My bad. My patch included an unrelated change in addition to your change. Sorry about that.

> My understanding of C is near zero and I do not dare to correct this.

Actually, there is nothing you need to correct. What you did actually accomplished what we wanted (needed) to accomplish. We only wanted (needed) to change the `cmpscmem.c` file. The accidental additional change to `cmpsc_2012.c` (that was rejected) did _not_ need to be changed.

I forgot that you are using the official 4.4.0 release. The change my patch was attempting to make to `cmpsc_2012.c` only exists in the 4.5.0 DEV (development) version, which you don't have.

So the only thing you need to do (if you want to; it's entire optional!) is to delete both the `cmpsc_2012.c.orig.txt` and `cmpsc_2012.c.rej.txt` files, and rebuild Hercules!

I have corrected my earlier patch. As you can see, the only change was my deleting the change for `cmpsc_2012.c`, which should not have been there. The only file we needed to change was  `cmpscmem.c`, which succeeded.

So you should be good to go. Just rebuild Hercules and give is a test!

It should hopefully fix you problem.

Please let me know whether it does.

Thanks!

_(and sorry about that!)_

**Comment by MartinTr2** [comment] 2022-02-25 13:16
Works (as advertised)

Bill - I used sudo make install (it complained when I did it without sudo at first)

**Comment by wrljet** [comment] 2022-02-25 15:41
Martin,

If you're interested, you can also switch your clone to the `develop` branch easily.

```
cd hyperion
git stash
git checkout develop
```

Then reapply your patch.

Bill

**Comment by Fish-Git** [comment] 2022-02-26 00:08
> Works (as advertised)

Fantastic! Fix committed. (397460bf7119071e1d2d97903e5e25a741a193a6)

Closing.

**Closed as completed by Fish-Git** 2022-02-26 00:08 UTC
Labels: BUG
