### ISSUE TITLE
Instruction Trace: TRTE and TRTRE 

### ISSUE THREAD

**Issue by JamesWekel** [SDL-Hercules-390/hyperion#501] opened 2022-09-01 05:03 UTC
An instruction trace for both the `TRTE` and `TRTRE` instructions includes storage references for the second operand register. The second operand register is a only a destination register for the Function Code and is not a source/destination address register. Depending on the register contents, you can get _"Translation exception 0005 (Addressing exception)"_ notices.

For example:

<pre>
22:35:07 HHC02324I PSW=000800000000020A INST=B9BF0024     TRTE  2,<b><i>4</i></b>,0                  translate_and_test_extended
22:35:07 HHC02326I R:00010000:K:00=00000000 00000000 00000000 00000000  
<b><i>22:35:07 HHC02326I R:00BBCCDD: Translation exception 0005 (Addressing exception)</i></b>
22:35:07 HHC02269I GR00=00000000 GR01=00110000 GR02=00010000 GR03=00000001
22:35:07 HHC02269I <b><i>GR04=AABBCCDD</i></b> GR05=00000000 GR06=00000000 GR07=00000000
22:35:07 HHC02269I GR08=40000200 GR09=00000000 GR10=00000000 GR11=00000000
22:35:07 HHC02269I GR12=00000000 GR13=00000000 GR14=00000000 GR15=00000000
</pre>

Only a reference for the first instruction operand register is valid and the second `HHC02326I` message should be removed.

I'm attaching two test scripts that demonstrate the issue and a log showing the problem. The Hercules configuration files used was the `tests.conf` configuration used for `runtest`.

 * [TRTE-trace.txt](https://github.com/SDL-Hercules-390/hyperion/files/9466933/TRTE-trace.txt)
* [TRTE-trace.log](https://github.com/SDL-Hercules-390/hyperion/files/9466934/TRTE-trace.log)
* [TRTRE-trace.txt](https://github.com/SDL-Hercules-390/hyperion/files/9466935/TRTRE-trace.txt)

I hope that I've sufficiently described the problem.

Jim

**Comment by Fish-Git** [comment] 2022-09-01 17:31
This is normal Hercules behavior.

The logic that traces instructions does so according to the instruction's _format_, not its opcode.

The `TRTE` instruction function itself (that _executes_ the `TRTE` instruction) is obviously smart enough to know the operand-2 register is not used to address storage, but the `RRF` format instruction _tracing_ function isn't. All it knows is that the instruction it is tracing is an `RRF` format instruction and noting more. It contains no special logic to allow it to determine whether operand-2 addresses storage or not, and therefore will always attempt to resolve it as such, leading to the Addressing Exception you are seeing.

Closing as Invalid: working as designed.

**Closed as completed by Fish-Git** 2022-09-01 17:31 UTC
Labels: WON'T FIX

**Comment by Fish-Git** [comment] 2022-09-01 17:34
Removing improper "Invalid" label and relabeling as more proper "Won't Fix" instead: "The requested change was rejected or the described behavior is by design."
