### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#422] opened 2021-09-12 12:48 UTC
I haven't built an up-to-date SDL Hercules since mid-March, and now I can't, see attached console output. I'm using Fedora 34 x64 and I believe I have all of the packages I need installed.

* [console.txt](https://github.com/SDL-Hercules-390/hyperion/files/7149578/console.txt)

What am I missing?

Ian

**Comment by mcisho** [comment] 2021-09-12 15:08
Hercules Helper builds Hercules successfully, until I change the source repository to SDL-Hercules-390, whereupon it doesn't. Have I fallen foul of, as hercules-helper.conf puts it, "some git commit stuff"?

btw, I added opt_no_envscript=true and opt_no_bashrc=true options to hercules-helper.conf to prevent changes to my environment variables and bashrc, and got the following message: 
Skipping step: create environment variables script (--no-envscript)
./hyperion-buildall.sh: line 3608: shell: unbound variable

Hercules Helper = very good.

**Comment by wrljet** [comment] 2021-09-12 15:12
Ian,
 
> btw, I added opt_no_envscript=true and opt_no_bashrc=true options to hercules-helper.conf to prevent changes to my environment variables and bashrc, and got the following message:
> Skipping step: create environment variables script (--no-envscript)
> ./hyperion-buildall.sh: line 3608: shell: unbound variable
> 
> Hercules Helper = very good.

I'll fix that for you.

Bill

**Comment by wrljet** [comment] 2021-09-12 15:25
> 
> 
> I haven't built an up-to-date SDL Hercules since mid-March, and now I can't, see attached console output. I'm using Fedora 34 x64 and I believe I have all of the packages I need installed.
> 
>     * [console.txt](https://github.com/SDL-Hercules-390/hyperion/files/7149578/console.txt)
> 
> 
> What am I missing?
> 
> Ian

I believe you have fallen into a trap related to the ongoing pissing contest between gcc and recent attempts to improve Hercules inlined function performance.  I suspect gcc 11 *might* be related here.

If you checkout commit eb1cf2b it will predate some of this activity and build correctly on Fedora 34 with gcc 11.2.

I'm trying Fedora 34 out now with an older gcc.

Bill

**Comment by mcisho** [comment] 2021-09-12 16:10
The reason I was trying to build was to make sure the commit I made earlier today (the LCS SNA support commit) hadn't cocked things up completely, but apparently I much too late to that party!

**Comment by wrljet** [comment] 2021-09-12 16:15
Actually those changes don't build.  You can see the Travis output here:

`https://app.travis-ci.com/github/SDL-Hercules-390/hyperion/jobs/536855697`

**Comment by wrljet** [comment] 2021-09-12 19:39
Ian,

After much cussing, I suggest you (for now, anyways) use Clang on the Fedora 34 system, in place of your gcc 11.2.

```
sudo dnf install clang
```

You can get past your failing commit (until that is repaired) by checking out the previous commit:

```
git checkout 77a23a2
```

And then tell `configure` to use Clang by prefacing the command with `CC=clang`.

```
CC=clang ./configure \
    --prefix=/home/irs/Hercules.run \
    --enable-optimization="-O2" \
    --disable-object-rexx \
    --disable-regina-rexx

make clean && make
```

Bill

**Comment by Fish-Git** [comment] 2021-09-12 21:03
> Actually those changes don't build. You can see the Travis output here:

They do now! You can see the Travis output here:

* https://github.com/SDL-Hercules-390/hyperion/runs/3581085285
* https://app.travis-ci.com/github/SDL-Hercules-390/hyperion/builds/237469815

Can this issue be closed now?

**Comment by wrljet** [comment] 2021-09-12 21:45
> Can this issue be closed now?

Well, I have reproduced the linking error with gcc 11 on another system.

```
/usr/bin/ld: ./.libs/libherc.so: undefined reference to `z900_or_4K_storage_key'
/usr/bin/ld: ./.libs/libherc.so: undefined reference to `s390_or_4K_storage_key'
/usr/bin/ld: ./.libs/libherc.so: undefined reference to `s370__or_storage_key'
```

So perhaps we should leave this (or a new) issue open until that eventually gets fixed.

Until then we just don't support gcc 11.

Bill

**Comment by mcisho** [comment] 2021-09-12 22:46
Thanks to those who have fixed my errors.

I have switched to clang and the build now works.

Bill, now that I have modified ``hercules-helper.conf`` I can't do a ``git pull`` of the changes you have made. Perhaps ``hercules-helper.conf`` should be shipped as, for example, ``hercules-helper.conf.sample``? I can't imagine I'm the only person who might want to change the conf.

**Comment by wrljet** [comment] 2021-09-13 14:23
That is a good idea, Ian.  I will rename the sample conf file.

**Comment by Fish-Git** [comment] 2021-09-14 05:46
> Until then we just don't support gcc 11.

That is unfortunately what it looks like for now, yes. &nbsp; `:(`

In the mean time I have changed this issue from "Bug" to "Unknown" instead and will leave it open until we eventually determine what the actual problem is.

_(I sure wish we knew what the FRICK was going on with gcc!)_ &nbsp; `:(`

**Comment by wrljet** [comment] 2021-09-14 14:59
Additional info...

Kubuntu 21.04 (I assume plain Ubuntu 21.04 as well, but didn't check) comes default with gcc 10.3.

I fails the same way as gcc 11.

gcc 9.3 (from package `gcc-9`) works.  Compiles, links, and passes checks.
(we do test this one in our latest Travis setup)

**Comment by wrljet** [comment] 2021-09-14 20:39
I've come up with some changes that seem (so far) to work.

Compiles and passes checks with gcc 9 and 10, and Clang 11, with -O2 and -O3, and Windows with VS2017.
(haven't actually IPLed anything, though)

The changes aren't too involved.

... developing ...

**Comment by Fish-Git** [comment] 2021-09-14 21:48
> I've come up with some changes that seem (so far) to work...

_**FANTASTIC!**_ &nbsp; Please let me know when they're ready! I'd _very_ much like to see them! &nbsp; `:-D`

**Comment by wrljet** [comment] 2021-09-14 22:09
Fish,

Are the new checks (209 tests vs. the older 327) more involved regarding the storage keys?

I'm seeing slightly faster `time make check` for the older code vs. the current.

Bill

**Comment by Fish-Git** [comment] 2021-09-14 23:07
> Are the new checks (209 tests vs. the older 327) more involved regarding the storage keys?

Yes.

My new "skey..." (skey370 and skey390z) tests (introduced by my "Fix skey handling part 6 of 6" commit made on Aug 1) perform a _much_ more thorough test of storage key handling than the previous tests, which weren't really testing much of anything.

> I'm seeing slightly faster `time make check` for the older code vs. the current.

That's not surprising given the tests we now have are doing a much more though job of testing.

Out of curiosity, what's the difference in run times? My own runtest script does calculate how long the full runtest suite of tests takes to complete, but only does so to the nearest second, and I've never bothered to maintain any type of history to see whether they're getting faster or slower, so I don't know. I would of course _expect_ them to get slower and slower (or rather, to take longer and longer to complete) as time goes by and we add more and more tests to the suite.

**Comment by wrljet** [comment] 2021-12-04 15:17
From my tests on any different *Nix systems with various compilers, I believe our 'inline' related compiler issues have been addressed.  Most recent with commit https://github.com/SDL-Hercules-390/hyperion/commit/b648263e8bfc6effd554f98baba81fba2dae916c.

I think we could probably close this issue now.

Bill

**Closed as completed** 2021-12-04 15:22 UTC
Labels: BUG, L
