### ISSUE TITLE
Hyperion confirms tape mounted to OS even the aws file does not exist

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#215] opened 2019-06-18 14:23 UTC
Matter of discussion:

Hyperion version: Hercules version 4.2.0.0-SDL-**g0f1b54b5**-modified (4.2.0.0)

I observed the following behavior during tape mount of an emulated 3590 tape device:

1. A MVS job requests to mount a tape on e.g. UA 760.

2. On MVS system console the correct mount request appears.

3. On the Hyperion console, I do enter the required DEVINIT command: `devinit 760 /path/to/tape/tape1.aws` and press enter.

However, by accident, a wrong path to the file was entered, so the aws file was not found.

Hyperion issued following messages :

```
13:30:04 HHC00221I 0:0760 Tape file /local/sys1/tape/nbcdmp.aws, type aws: format type AWS Format tape file
13:30:04 HHC00224I 0:0760 Tape file /local/sys1/tape/nbcdmp.aws, type aws: display " NT RDY "
13:30:04 HHC00205E 0:0760 Tape file /local/sys1/tape/nbcdmp.aws, type aws: error in function open(): No such file or directory
```

The mount message on the OS disappears as it is satisfied but of course the job does not abend or further error processing. It can not further process the error and "sits" there without any operator information on MVS side. 

Is this behavior works as designed or should the program logic be changed in such a way that first the existence of the aws file is checked AND only after successful verification of the existing file messages HHC00221I and HHC00224I  will be issued and the mount request is satisfied for the OS?

Here is the CCW trace on the device 760 from Hyperion:

* [tape760.ccw.txt](https://github.com/SDL-Hercules-390/hyperion/files/3301389/tape760.ccw.txt)

**Comment by Fish-Git** [comment] 2019-06-21 06:29
> Is this behavior works as designed or should the program logic be changed in such a way that first the existence of the aws file is checked AND only after successful verification of the existing file messages HHC00221I and HHC00224I will be issued and the mount request is satisfied for the OS?

This is, for convenience, by design:

* https://sdl-hercules-390.github.io/html/hercconf.html#AUTOINIT

```
HHC01603I help autoinit
HHC01603I 
HHC01602I Command               Description
HHC01602I ----------------      -------------------------------------------------------
HHC01602I autoinit             *Display/Set auto-create-empty-tape-file option
HHC01603I 
HHC01603I Format: "AUTOINIT  [ ON | OFF ]"
HHC01603I 
HHC01603I The AUTOINIT option controls whether emulated tape drive device files
HHC01603I will be automatically created or not when it is discovered they do not
HHC01603I yet exist.
HHC01603I 
HHC01603I When AUTOINIT is ON (the default), a devinit command specifying a file
HHC01603I that does not yet exist causes the tape driver to automatically create
HHC01603I an unlabeled tape volume consisting of just two tapemarks whenever it
HHC01603I discovered the specified file does not exist.
HHC01603I 
HHC01603I When AUTOINIT is OFF, a devinit command instead fails with an expected
HHC01603I "file not found" error if the specified tape file does not exist.
HHC01603I 
HHC01603I Entering the command without any arguments displays the current setting.
HHC01603I 
HHC01603I autoinit
HHC02203I AUTOINIT      : ON
```

**Comment by Fish-Git** [comment] 2019-06-21 06:33
In retrospect, due to the "Surprise!" factor of this change (commit a0b476264033aa35ef0f326632a8892f9b34a8b1), I'm now thinking I should probably revert the default setting back to "OFF" instead.

How do others feel about this?

**Comment by fbi-ranger** [comment] 2019-06-21 08:24
In the case described here, the file was an input file (ADRDSSU-dump) to a restore JOB. 
In case the file would have been created automatically and opened by the restore job it would have found an empty file and probably would abend or terminate. However, it did nothing. 

Checking in the filesystem, I didn't see any file created because the Hercules process has no write privilege in the directory I  accidentally specified. 
Because the output file can not be created automatically, even with AUTOINIT ON, the mount request should NOT BE confirmed to MVS. 

The creation of the file should be done as first step based on AUTOINIT option. Based on the return code of the creation the program logic either process further confirming the mount or in case the creation failed it should leave the mount pending.

**Comment by Fish-Git** [comment] 2019-06-23 16:12
Bug found. Fix will be committed shortly. Thank you for your patience.

**Closed** 2019-06-23 16:16 UTC
Labels: BUG, IN PROGRESS...

**Comment by Fish-Git** [comment] 2019-06-23 16:36
@fbi-ranger Florian,

Commit f5264129e7f05a7e2bf884f41df9f8a14cd73b5c should resolve this issue. Please confirm. Thanks.

(and thank you for reporting it!)
