### ISSUE TITLE
Multiple CPUs looping at 100% utilization (RARE)

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#270] opened 2019-12-20 21:27 UTC
&nbsp;
_**EDIT:** it appears this problem does not necessarily happen only under z/VM. I have personally experienced it while running z/OS natively. The title of this GitHub Issue has therefore been updated appropriately._
___
I've seen this occurring under z/VM 6.3. All CPUs that have not been stopped due to VM Vertical SRM scheduling are sometimes going into a tight loop. The system becomes completely unresponsive. The only solution is to IPL the system again.

This must be a _VERY_ subtle bug somewhere since it occurs so _very rarely_ (I've only had it occur to me twice inside of one year).

_**If anyone runs into this, please... PLEASE .. Issue a `RESTART` command from the Hercules console to create a dump, and then send it to me!!**_

_(If you don't know how to do that, **ask** and I'll assist you!)._

**Comment by Fish-Git** [comment] 2019-12-22 05:13
> If anyone runs into this, please... PLEASE .. Issue a `RESTART` command from the Hercules console to create a dump, and then send it to me!!

Wouldn't the following be better?

1. `t+` to start an instruction trace on all processors.
2. After waiting _(a few seconds?)_, `t-` to stop the trace.
3. `stop all` to stop all processors.
4. `store status` to save system information (registers, etc.)
5. `restart` to force a restart interrupt to cause z/VM to take a stand-alone dump)

The idea here is, in my years of experience as both a system operator and system programmer, a stand-alone dump without a "store status" beforehand is pretty much worthless. IMHO it is _**critically important**_ to _always_ do a "store status" _before_ issuing the "restart" to take the stand-alone dump. Only by doing that acn you be sure that the registers and other system values that appear in your dump correspond to the rest of the dump.

Or does z/VM's system restart routine do that for you automatically?

**Comment by ivan-w** [comment] 2019-12-22 10:23
Actually, the first thing z/VM does when it gets a SYSTEM RESTART interrupt on a running system is send a Store Status CPU Signal to all CPUs so as to get the current status of everything. Then it dumps supervisor/hypervisor storage to a spool file (or to a dedicated tape depending on how CP dump has been configured - Virtual machines storage is not dumped). This dump can then be read using IPCS (the series of VM tools used to read dumps).
It's however quite possible the "system restart" won't even work because such a behavior may indicate a catastrophic failure within herc and things may no longer behave as expected.
The problem is that it is a VERY rare occurrence, and I have not (yet) found a way to reproduce it.

**Comment by ivan-w** [comment] 2020-03-23 09:21
Finally got a dump ! So there is progress

**Comment by Fish-Git** [comment] 2020-06-19 22:20
I have updated the title of this GitHub Issue (and added an edit in the original description too) since I myself (and others as well) have experienced this issue running e,g, z/OS natively. Ivan is correct however in that it appears to occur most often under z/VM whenever it does occur, but the problem (which I believe I _may_ know what's causing it) is _NOT_ limited to only z/VM.

_**I would therefore like to ask anyone who experiences this problem to please do a 1-3 second instruction trace** (`t+`, wait 1-3 seconds, `t-`) **whenever the problem occurs, and submit your resulting logfile to me for analysis!**_

Thanks.

**Comment by Peter-J-Jansen** [comment] 2020-07-29 20:48
Please find a Hercules log [here](https://www.dropbox.com/s/b3x01dka368ppb6/Hercules_log_462_P0.txt?dl=0) of a 100% utilization looping with four (4) CPU's. From a quick look at it, each of these 4 CPU's is on a different tight loop of less than a screenfull of instructions. It was for a z/VM 6.3 system with a z/OS 2.3 system running 2nd level. The only way out of this was two Hercules quit commands.

HTH

Cheers,

Peter

**Comment by Fish-Git** [comment] 2020-07-30 22:18
Downloaded. Thanks. I'll take a look at it when I get a chance.

One thing I did notice however (that slightly concerns me), is the following:

<pre>
10:11:37 HHC90013E 'initialize lock(&dev->ctceEventLock)' failed: rc=17: already init'ed; tid=00007000123f9000, loc=ctcadpt.c:3529
10:11:37 HHC00007I Previous message from function 'loglock' at hthreads.c(104)
10:11:37 HHC90028I lock &dev->ctceEventLock was already initialized at ctcadpt.c:3529
</pre>

Bug in CTCE?

**Comment by Peter-J-Jansen** [comment] 2020-07-31 08:54
Thanks Fish.

The `dev->ctceEventLock was already initialized` is a different minor issue that I already forgot about as it does not hurt. It started appearing after the checking for this was added, and can be caused when a `DEVINIT ccuu` command for a CTCE device is being issued. It re-initializes the CTCE `dev` but without zeroing the memory as it should be able to re-initialize with the initial CTCE parameters. And the re-initialization also re-initializes that lock. I checked into the possibility to un-initialize that lock, but currently there is no such function available. I thought that just zeroing the right bits of memory of the lock might do it, but was uncertain whether that would be the correct approach. And as it didn't hurt, I left it as is for the time being. I think we need such `unitialize_lock` function, that would be the correct approach. 

But, as I said, a minor issue for another day.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2020-07-31 19:01
> I checked into the possibility to un-initialize that lock, but currently there is no such function available.

Nonsense:

* _The [**pthread_mutex_destroy()**](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_destroy.html) function shall destroy the mutex object referenced by mutex; the mutex object becomes, in effect, uninitialized._

> I think we need such `unitialize_lock` function, that would be the correct approach.

We already do: &nbsp;it's called **`destroy_lock`**.

> But, as I said, a minor issue for another day.

No time like the present! &nbsp; `:)`

**Comment by Peter-J-Jansen** [comment] 2020-08-01 12:00
> We already do:  it's called destroy_lock

Thanks for making me aware of this.

> No time like the present!   :)

You're right, so I've fixed it. I am about to start testing that fix, which actually did not need `destroy_lock`. It was a genuine bug of mine in CTCE, so you were also right on that one.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2020-08-12 22:13
I need to look into your #315 problem first, but I'll try to take a look at your loop problem too if I get a chance.

**Comment by Fish-Git** [comment] 2021-02-07 04:58
Ivan! &nbsp;(@ivan-w)

I managed to capture an occurrence of z/VM 7.1 looping on _ONE_ cpu at 100%!

The problem occurred during an IPL of z/OS 2.4 under z/VM 7.1.

I did a `t+` and let the instruction trace run for a few seconds, and then `t-` to stop the trace, followed by `stopall`, `store` (Store Status) and finally `restart`, and z/VM dutifully created a nice DUMP for me:

<pre>
HHC02229I Instruction tracing off
HHC01603I stopall
HHC01603I store
HHC00817I Processor CP00: store status completed
HHC01603I restart
HHC02228I restart key pressed
HHC00814I Processor CP00: SIGP Store status                     (0E) CP01, PARM 0000000000B49200: CC 0
HHC00814I Processor CP00: SIGP Store status                     (0E) CP02, PARM 0000000000B4B200: CC 0
HHC00814I Processor CP00: SIGP Store status                     (0E) CP03, PARM 0000000000B4D200: CC 0
HHC00814I Processor CP00: SIGP Store status                     (0E) CP04, PARM 0000000000B4F200: CC 0
HHC00814I Processor CP00: SIGP Store status                     (0E) IP05, PARM 0000000000B51200: CC 0
20:14:12 HCPWRP963I SHUTDOWN STEP SGPST - STOP OTHER PROCESSORS
20:14:13 HCPWRP959I ZVM71    SYSTEM TERMINATION IN PROGRESS ON 2021-02-06
20:14:13 HCPWRP963I SHUTDOWN STEP TXTDS - TERMINATE DATA TRACES
20:14:13 HCPWRP963I SHUTDOWN STEP SVACV - ACTIVATE TERMINATION SAVE AREAS
20:14:14 HCPWRP963I SHUTDOWN STEP CHMOF - DISABLE CHANNEL MEASUREMENT
20:14:14 HCPWRP963I SHUTDOWN STEP ISHDA - DISABLE ALL DEVICES

(...separated for emphasis...)

<b>20:14:15 HCPWRP963I SHUTDOWN STEP DMPDK - TAKE DUMP
20:14:10 HCPDMP908I SYSTEM FAILURE ON CPU 0000, CODE - SVC002
20:14:10 HCPDMP908I 2021-02-06 SYSTEM ZVM71
20:14:15 HCPDMP9252I DUMPING TO DASD
20:14:17 HCPDMP9260I 25% OF THE DUMP HAS BEEN COMPLETED
20:14:19 HCPDMP9260I 50% OF THE DUMP HAS BEEN COMPLETED
20:14:20 HCPDMP9260I 75% OF THE DUMP HAS BEEN COMPLETED
20:14:21 HCPDMP9261I DUMP COMPLETE ON 2021-02-06, CODE SVC002</b>

(...separated for emphasis...)

20:14:21 HCPWRP963I SHUTDOWN STEP CKPSH - TAKE A CHECKPOINT
20:14:21 HCPWRP963I SHUTDOWN STEP OPRCK - SAVE OPERATOR CONSOLE LIST
20:14:22 HCPWRP963I SHUTDOWN STEP MCWMD - DETERMINE MACHINE CHECK STATUS
20:14:22 HCPWRP963I SHUTDOWN STEP SDVRS - RESET IBM DASD CU CHARACTERISTICS
20:14:23 HCPWRP963I SHUTDOWN STEP SGQXX - RESET OTHER PROCESSORS
20:14:23 HCPWRP9277I SYSTEM TERMINATION COMPLETE, ATTEMPTING RESTART
20:14:23 HCPWRP9277I 2021-02-06 SYSTEM ZVM71
20:14:23 HCPWRP963I SHUTDOWN STEP SVADV - DEACTIVATE TERMINATION SAVE AREAS
20:14:24 HCPWRP963I SHUTDOWN STEP MTORS - RESET THE CONFIGURATION
</pre>

I haven't looked at the Hercules log yet to see what was going on (what the loop was and why it was occurring) because z/VM is still running at the moment. (After it took the dump it automatically restarted itself.)

I did a "`cp q rdr OPERATNS all`" and see a nice DUMP for you waiting in the reader:

<pre>
<b>cp q rdr OPERATNS all</b>
ORIGINID FILE CLASS RECORDS  CPY HOLD DATE  TIME     NAME      TYPE     DIST
SYSTEM   0002 D SYS 00038261 001 NONE 02/06 20:14:10 CPDUMP    CPDUMP   SVC002
SYSTEM   0003 D SYS 00000000 001 NONE OPEN- SYS                HCPDUMP
SYSTEM   0004 D SYS 00000000 001 NONE OPEN- SYS      CPDUMP    CPDUMP
Ready; T=0.01/0.01 20:23:48
</pre>

What do I have to do to (dump? transfer? copy?) this spool file to tape so I can send it to you for analysis? It's been too many years since I've done anything like this! I used to know how, but I've since forgotten.

_**HELP!**_ &nbsp; `:(`

Thanks.

**Comment by Fish-Git** [comment] 2021-02-07 16:23
> What do I have to do to (dump? transfer? copy?) this spool file to tape so I can send it to you for analysis? It's been too many years since I've done anything like this! I used to know how, but I've since forgotten.
> 
> _**HELP!**_   `:(`

&nbsp;
Okay, I used the command:
```
spxtape dump 590 user operatns rdr spid 002
```
and it seems to have worked. Here's the resulting .het tape file:

* [CPDUMP.SVC002.zip](https://github.com/SDL-Hercules-390/hyperion/files/5939403/CPDUMP.SVC002.zip)

Let me know if you discover anything. In the mean time I'm going to start taking a look at the loop to see if anything jumps out at me.

Thanks.

**Comment by Fish-Git** [comment] 2021-02-07 17:01
**CORRECTION:** &nbsp;The looping was _not_ on just one cpu. It was between _two_ cpus: CP03 and IP05. Original report corrected.

**Comment by Fish-Git** [comment] 2021-02-09 19:58
> **CORRECTION:**  The looping was _not_ on just one cpu. It was between _two_ cpus: CP03 and IP05. Original report corrected.

_**RE-CORRECTION:**_ &nbsp;The looping was not between just two CPUs either, but was in fact between _all **six**_ cpus (i.e. CP00-CP04 and IP05).

_And_ ... It is beginning to look like the cause for the loop was brought about by a _likely bug_ in our current **TXF "PPA"** (Perform Processor Assist) support too. I'm looking into it.

_Nevertheless,_ Just to be sure, I would appreciate someone taking a quick peek at the z/VM dump anyway if they could, to see if anything happens to jump out at them.

Thanks.

**Comment by Fish-Git** [comment] 2021-03-29 18:53
Has anyone experienced this issue recently? Or is it as rare as I hope it is? I'd like to close it!

**NOTE:** I _have_ admittedly experienced _rare_ occurrences of this problem myself, but it was during early TXF development and I suspect it was due to a bug in TXF and not Hercules per se. **AND** we have also corrected some bugs in Hercules since this problem was first reported too (such as our AR mode MVCOS bug), so it might no longer be relevant/current.

So ... should we close it? Or keep it open? I vote for closing it.

If it happens again we can either re-open it or create a new GitHub Issue for the new occurrence.

Yes?

**Comment by mgrossmann** [comment] 2021-03-31 20:49
Hi guys,

I'm not quiet sure I commenting the right issue. But I have a similar problem. If I am trying to IPL a VM/ESA with Main storage set
to 2048, the processor_cp00 thread is looping at 100%. Problem could be avoided by simply decreasing the memory to 2047. 

/MIkeG

**Comment by Fish-Git** [comment] 2021-08-02 19:29
> but I have a similar problem: When I try to IPL VM/ESA with main storage set to 2048, the processor `CP00` thread starts looping at 100%. Problem can be avoided by simply decreasing the memory to 2047.

I've experience the same phenomenon in the past with early versions of z/VM too (e.g. z/VM 5.3), and yes, reducing `mainsize` to a value of, say, 2000MB, resolved the problem.

**Comment by Fish-Git** [comment] 2021-08-02 19:29
> So ... should we close it? Or keep it open? I vote for closing it.
> 
> If it happens again we can either re-open it or create a new GitHub Issue for the new occurrence.
> 
> Yes?

Closing issue.

**Closed by Fish-Git** 2021-08-02 19:29 UTC
Labels: (Unknown), HELP!, QUESTION..., Waiting to close...
