### ISSUE TITLE
DASD Formatting under z/VM extremely slow

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#201] opened 2019-04-21 04:58 UTC
I run SDL latest as of today on my system: SSD disks, i7 CPU, lots of RAM. 

Under SDL Hyperion, formatting a new volume (CKD, uncompressed) under z/VM with `CPFMTXA` takes about 15 seconds per 100 tracks. _(So you can do the math how long it takes for a 3390-9!)_

On the exact same system with zPDT, the same type of CKD uncompressed volume, with the same version of z/VM (version doesn't really matter), I get a whole 3390-9 formatted in less than 10 seconds.

I wonder why zPDT is so much faster?? Something must be sub-optimal in the DASD emulation under SDL if it takes so much longer...

thanks

M

**Comment by Fish-Git** [comment] 2019-04-25 02:00
What steps are needed to reproduce? Logon to z/VM userid, attach dasd, enter `CPFMTXA` command? What was the exact `CPFMTXA` command that you used? Thanks.

**Comment by Fish-Git** [comment] 2019-04-25 10:41
Okay, I did some speed testing of my own on regular spinning dasd (I don't have SSD) using z/VM 6.3, and my results, while significantly faster than yours, are still much slower than I would have expected.

Using latest SDL Hyperion 4.2 and uncompressed 64-bit CKD dasd, I'm getting the following:

```
-----------------------------------------------------------------

(freshly DASDINIT64'ed -- 64-bit CKD64 using SDL Hyperion 4.2)


FORMATTING OF CYLINDER 10016 ENDED AT: 19:31:46
FORMATTING OF CYLINDER   0 STARTED AT: 19:27:59
                                           3:47

44 cyl/sec
2.3 secs/100 cyls


-----------------------------------------------------------------

(CPFMTXA again on same volume)


FORMATTING OF CYLINDER 10016 ENDED AT: 20:17:31
FORMATTING OF CYLINDER 0   STARTED AT: 20:04:21
                                          13:10

13 cyl/sec
7.9 secs/100 cyls


-----------------------------------------------------------------

(CPFMTXA again on same volume)


FORMATTING OF CYLINDER 10016 ENDED AT: 20:49:22
FORMATTING OF CYLINDER 0   STARTED AT: 20:36:18
                                          13:04

(about the same)


-----------------------------------------------------------------

(detached and re-DASDINIT64'ed)


FORMATTING OF CYLINDER 10016 ENDED AT: 21:00:52
FORMATTING OF CYLINDER 0   STARTED AT: 20:56:09
                                           4:43

35 cyls/sec
2.8 secs per 100 cyls
                                           

-----------------------------------------------------------------

(CPFMTXA again on same volume)


FORMATTING OF CYLINDER 10016 ENDED AT: 21:09:10
FORMATTING OF CYLINDER 0   STARTED AT: 21:04:29
                                           4:41

(about the same)


-----------------------------------------------------------------

(CPFMTXA again on same volume)


FORMATTING OF CYLINDER 10016 ENDED AT: 21:17:32
FORMATTING OF CYLINDER 0   STARTED AT: 21:13:07
                                           4:25

(about the same)


-----------------------------------------------------------------
```

&nbsp;
&nbsp;
&nbsp;
I'm not sure why two of the runs were over 13 minutes, but I'm guessing there _may_ have been something running in the background that I just didn't notice. (such as AV rootkit scan perhaps?) Except for the very first run, all of the other runs were fairly consistent with one another.

I then fell back to SDL Hyperion 4.1 and tried the same thing using 32-bit uncompressed CKD dasd:
&nbsp;
&nbsp;
&nbsp;

```
-----------------------------------------------------------------

(freshly dasdinit'ed -- 32-bit CKD using SDL Hyperion 4.1)


FORMATTING OF CYLINDER 10016 ENDED AT: 02:23:10
FORMATTING OF CYLINDER 0   STARTED AT: 02:16:55
                                           4:15

39 cyls/sec
2.5 secs per 100 cyls


-----------------------------------------------------------------

(CPFMTXA again on same volume)


FORMATTING OF CYLINDER 10016 ENDED AT: 02:30:51
FORMATTING OF CYLINDER 0   STARTED AT: 02:25:05
                                           5:46

29 cyls/sec
3.5 secs per 100 cyls


-----------------------------------------------------------------
```

&nbsp;
As you can see its performance is virtually identical to 4.2's (or close enough for government work anyway).

So yeah, I'd say the performance of Hercules's dasd emulation I/O -- _**in this particular case**_ -- pretty much, um, well ... _sucks._ &nbsp;`:(`

Understand too that this is z/VM `CPFMTXA` we're talking about here too, which likely does its dasd formatting much differently than other programs on other operating systems (such as `ICKDSF` on z/OS for example). I mention this because one thing I did notice while the format was running was that it was doing MT (MultiTrack) I/O. That may be where the inefficiency is.

Or maybe that's just the normal speed of Hercules dasd I/O? &nbsp; _&lt;shrug&gt;_

I'm not sure _where_ the inefficiencies are in Hercules dasd emulation I/O. There might not be any at all. The inefficiency _might_ be elsewhere. (_Where,_ I'm not sure.)

That's all I have for now.

I'm going to leave this issue labeled as "Unknown" rather than "Bug" since I'm not sure there's an actual bug anywhere. It certainly appears there is definitely room for improvement in this area. I'll try to take a look at the code in more depth when I find the time (which could well be never!), but for now I would consider this a low priority item. Hercules's dasd I/O emulation appears to be working fine. Is it slower than expected? Most certainly. _(in this particular case!)_

But I wouldn't consider it a bug.

I'll leave this issue open for now so others can maybe do some testing of their own to try and maybe figure out what's going on.

Fair enough?

**Comment by moshix** [comment] 2019-04-25 14:10
Fish

yes, fair enough, thank you much. 

On my system with CCKD64 DASDs it's consistenly much slower, but yes, even at the better speeds you encountered it's still too slow, especially considering that zPDT does it faster by an order of magnitutde. 

thanks

M

**Comment by Fish-Git** [comment] 2019-04-25 16:27
> ... zPDT does it faster by an order of magnitude.

Why are you so surprised by that??

By all measurements (not just I/O speed but also CPU (instruction execution) speed as well) the zPDT is typically _at least_ an order of magnitude (10 times) faster than Hercules! This has _always_ been the case.

Comparing the performance of Hercules against that of the zPDT is like comparing apples to oranges. They're completely different under the hood.

**Comment by moshix** [comment] 2019-04-25 16:30
Didn't say I am surprised, and I know that it's different under the hood. Not comparing either. 

What I am saying is that with a different emulation architecture it's apparently possible to have faster I/O (and other things, too). 

I think Hyperion is amazing already, especially for free software. But it's ok to strive to improve all the time. 

thanks for your efforts Fish and Ivan

**Comment by Fish-Git** [comment] 2019-04-25 16:32
> On my system with CCKD64 DASDs it's consistently much slower

I see virtually no difference in performance between CKD and CKD64 nor between CCKD and CCKD64. In all the tests I have ever done they have each perform virtually identically to each other.

**Comment by Fish-Git** [comment] 2019-04-25 17:01
> Didn't say I am surprised, and I know that it's different under the hood. Not comparing either.

Okay. I apologize then for misinterpreting you comment. My bad.

> What I am saying is that with a different emulation architecture it's apparently possible to have faster I/O (and other things, too).

Duh!&nbsp;`:)`

Hercules could easily be made to be _much_ faster. But then it wouldn't be portable either, which is one of our primary goals.

> I think Hyperion is amazing already, especially for free software.

Aye!! Me too!!

> But it's ok to strive to improve all the time.

Of course! That's one of _my_ primary goals!!&nbsp;`;-)`

> Thanks for your efforts Fish and Ivan

Ivan and I are just two people amongst many, _many_ dozens who have contributed to Hercules over the years, helping to make it the fine product it is today.

Roger Bowler himself should of course be the very _first_ person to thank, for taking the time and effort and imagination / determination to even _write (create)_ Hercules in the first darn place, Jan Jaeger for adding SIE and z/Architecture support, Jay Maynard as its maintainer and primary evangelizer for so many years, etc.

Refer to [FAQ question 6.01](https://sdl-hercules-390.github.io/html/hercfaq.html#6.01) for the official list.

**Comment by moshix** [comment] 2019-04-25 17:08
yes, and I did thank them all also in my video a couple of months ago. 

again, appreciate all your efforts. Simply amazing. 

M

**Comment by Fish-Git** [comment] 2019-04-25 17:14
> Yes, and I did thank them all also in my video a couple of months ago.
> 
> Again, appreciate all your efforts. Simply amazing.

We all stand on the shoulders of the giants that came before us. They're the true heroes.

**Comment by Fish-Git** [comment] 2019-08-07 05:03
Just an interesting FYI tidbit I happened to come across on IBM's web site for the `CPFMTXA` command:

https://www.ibm.com/support/knowledgecenter/en/SSB27U_6.4.0/com.ibm.zvm.v640.hcpb7/cpfmtxac.htm

Notice the timing:

```
FORMATTING OF CYLINDER 0 STARTED AT: 09:33:52
.
.
.
FORMATTING OF CYLINDER 544 ENDED AT: 09:37:58
```

That's about 3 seconds per 100 cylinders, which is the [same throughput that I was getting in my own tests under Hercules!](https://github.com/SDL-Hercules-390/hyperion/issues/201#issuecomment-486621027)

Interesting, no? &nbsp; `:)`

**Comment by Fish-Git** [comment] 2019-08-07 05:36
### _\*\*\* CORRECTION \*\*\*_

And _actually_, I must have been drunk _(not really, just tired probably)_ when I did the math on my [original test run](https://github.com/SDL-Hercules-390/hyperion/issues/201#issuecomment-486621027), because an elapsed time of **3:47** is 227 seconds, and 10017 cylinders is 150255 tracks, which comes out to a rate of _662 tracks-per-second_, or about _0.0015 seconds-per-track_, yielding an effective _seconds-per-100-tracks_ rate of _**0.15**_ seconds (not 2.3), which is needless to say _**100 times faster**_ than your purported _**15** seconds-per-100-tracks_ rate.

Are you sure you did _your_ calculations correctly? Because if you did then there must be either something serious wrong with your hard drives or else maybe some background process was interfering with (impacting) your z/VM `CPFMTXA` run! I mean, 15 seconds to format 100 tracks means each track is taking about 150 milliseconds! (which needless to say I'm having a hard time believing!)

**Comment by ivan-w** [comment] 2019-08-07 05:51
Oh FYI (reread some of he comments) CPFMTXA *IS* ICKDSF !

**Comment by Fish-Git** [comment] 2019-08-07 06:11
>... `CPFMTXA` _**is**_ `ICKDSF`!

Thanks, Ivan. I appreciate the confirmation. I thought they were pretty much the same but wasn't sure.

**Comment by ivan-w** [comment] 2019-08-07 06:15
Under modern z/VM, CPFMTXA EXEC is a REXX script that is just a front-end used for invoking ICKDSF.. There is a CPFMTXA MODULE file.. which is just a front end to invoking CPFMTXA EXEC !

**Comment by Fish-Git** [comment] 2019-08-13 20:42
Okay, I've done some more testing and there does appear to be an inefficiency _somewhere_ in Hercules greatly impacting ICKDSF formatting of CKD64 dasd.

(I didn't bother testing CKD as I suspect the inefficiency, whatever it is, would be the same; CKD and CKD64 are essentially identical. Only _**C**CKD_ (compressed CKD) is different between CCKD64 and CCKD.)

I did a CPFMTXA of a uncompressed CKD64 _**3390-9**_ dasd (8GB) under z/VM, traced the I/O, and then used that to create a simple Hercules stand-alone ICKDSF loadcore program that does the same thing. In this way I could run "ICKDSF" natively directly under Hercules or indirectly from a z/VM guest userid. I also did the same test (natively from Hercules and from z/VM) using a _compressed_ **C**CKD64 dasd as well to see if there was any difference and if so, how much _(and there was! **A lot!**)_.

Here are my timings:

<pre>
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------

<b>NATIVE, CKD64 (uncompressed):  about 4 minutes = 34MB/sec</b>


2019/08/10 21:54:34.307 HHC00809I Processor CP00: disabled wait ...
2019/08/10 21:50:11.760 HHC02228I restart key pressed
           ------------
               4:23

2019/08/10 22:07:11.920 HHC00809I Processor CP00: disabled wait ...
2019/08/10 22:03:05.854 HHC02228I restart key pressed
           ------------
               4:06

2019/08/10 23:43:41.610 HHC00809I Processor CP00: disabled wait ...
2019/08/10 23:39:50.478 HHC02228I restart key pressed
           ------------
               3:51

2019/08/11 22:32:37.335 HHC00809I Processor CP00: disabled wait ...
2019/08/11 22:26:26.408 HHC02228I restart key pressed
           ------------
               6:11

2019/08/11 23:03:20.379 HHC00809I Processor CP00: disabled wait ...
2019/08/11 22:59:25.177 HHC02228I restart key pressed
           ------------
               3:55

-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------

<b>NATIVE, CCKD64 (compressed):  about 1.5 minutes = 90MB/sec</b>


2019/08/10 23:54:37.601 HHC00809I Processor CP00: disabled wait ...
2019/08/10 23:53:45.551 HHC02228I restart key pressed
           ------------
               0:52

2019/08/10 23:59:52.767 HHC00809I Processor CP00: disabled wait ...
2019/08/10 23:58:19.639 HHC02228I restart key pressed
           ------------
               1:33

2019/08/11 00:02:47.711 HHC00809I Processor CP00: disabled wait ...
2019/08/11 00:01:09.767 HHC02228I restart key pressed
           ------------
               1:38

2019/08/11 00:10:44.998 HHC00809I Processor CP00: disabled wait ...
2019/08/11 00:08:59.271 HHC02228I restart key pressed
           ------------
               1:45

-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------

<b>Z/VM, CKD64 (uncompressed):  about 14 minutes = 10MB/sec</b>


00: TIME IS 14:02:30 PDT SUNDAY 08/11/19
00: TIME IS 13:48:48 PDT SUNDAY 08/11/19
            --------
               13:42

00: TIME IS 22:11:20 PDT SUNDAY 08/11/19
00: TIME IS 21:57:21 PDT SUNDAY 08/11/19
            --------
               13:59

-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------

<b>Z/VM, CCKD64 (compressed):  about 2 minutes = 68MB/sec</b>

00: TIME IS 21:54:10 PDT SUNDAY 08/11/19
00: TIME IS 21:52:18 PDT SUNDAY 08/11/19
            --------
                1:52

00: TIME IS 22:19:45 PDT SUNDAY 08/11/19
00: TIME IS 22:17:54 PDT SUNDAY 08/11/19
            --------
                1:51

-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
</pre>

Notice that using **compressed** CKD dasd (i.e. _C_CKD or _C_CKD64) _dramatically_ reduces the runtime. I believe this is due to much less actual data being physically written/read to/from the host's file. ICKDSF formats each track with 12 (twelve) 4K binary zero records, which, for CCKD, gets compressed to practically nothing.

So as I said, there _does_ appear to be an incredible inefficiency somewhere in Hercules's channel I/O logic related to SIE, but I have no idea where. My next task is to try and pinpoint where the inefficiency is and fix it (if possible).

_**But I need my fellow Hercules developers' help on this!**_

_Because I have **no idea** where to begin looking!_&nbsp;`:(`

If any of you have any ideas or suggestions, please let me know.

Thanks.

___
p.s. Here's my stand-alone ICKDSF program that I used (which includes the loader program too, for running it under z/VM):

* [ICKDSF.zip](https://github.com/SDL-Hercules-390/hyperion/files/3498775/ICKDSF.zip)

**Comment by Fish-Git** [comment] 2019-08-17 11:47
@ivan-w 

Ivan,

I suspect you might find the following to be _VERY interesting!_

What I did was convert the `MADDRL` macro into a function, and then added some test code to count how often a TLB hit and TLB miss was occuring, and for the misses, which of the 5 conditions was most frequently causing the miss to occur. &nbsp;_(see the attached patch(*) at the end for details)_

**`maddrl`** (previously `MADDRL` macro) conditions:

1. (regs->AEA_AR( arn ))

2. (
        (regs->CR( regs->AEA_AR( arn )) == regs->tlb.TLB_ASD( TLBIX( addr )))
     || (regs->AEA_COMMON( regs->AEA_AR( arn )) & regs->tlb.common[ TLBIX( addr ) ])
   )

3. ( akey == 0 || akey == regs->tlb.skey[ TLBIX( addr ) ])

4. ( ((addr & TLBID_PAGEMASK) | regs->tlbID) == regs->tlb.TLB_VADDR( TLBIX( addr ) ))

5. ( acctype & regs->tlb.acc[ TLBIX( addr ) ])

I then ran my "ICKDSF" test both natively directly under Hercules (in both z/Arch as well as S/390 mode), as well as from a z/VM guest machine (after ipling cms (S/390 mode) and ipling zcms (z/Arch mode)). The results are below.

First, the native (directly under Hercules) tests:

<pre>
--------------------------------------------------------------------------------

<b>ICKDSF64, Native, z/Arch</b>

HHC02204I ARCHLVL        set to z/Arch
HHC01603I loadcore "c:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ICKDSF64\ICKDSF64.core"
HHC02250I Loading file c:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ICKDSF64\ICKDSF64.core to location 0
HHC02249I Operation complete
HHC01603I $test fish start
HHC00001D fish: start!
HHC01603I restart
HHC02228I restart key pressed
HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000000000
HHC01603I $test fish stop
HHC00001D fish: stop!
HHC00001D
HHC00001D HOST:                0 HITS   (  0.00%)
HHC00001D HOST:        <b><i>2,734,670 MISSES (100.00%)</i></b>
HHC00001D HOST:        2,734,670 TOTAL
HHC00001D                      0 times cond 1 was false (  0.00%)
HHC00001D              <b>2,734,668 times cond 2 was false (100.00%)</b>
HHC00001D                      0 times cond 3 was false (  0.00%)
HHC00001D                      2 times cond 4 was false (  0.00%)
HHC00001D                420,725 times cond 5 was false ( 15.38%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D
HHC00001D GUEST:               0 HITS   ( -1.#J%)
HHC00001D GUEST:               0 MISSES ( -1.#J%)
HHC00001D GUEST:               0 TOTAL
HHC00001D                      0 times cond 1 was false ( -1.#J%)
HHC00001D                      0 times cond 2 was false ( -1.#J%)
HHC00001D                      0 times cond 3 was false ( -1.#J%)
HHC00001D                      0 times cond 4 was false ( -1.#J%)
HHC00001D                      0 times cond 5 was false ( -1.#J%)
HHC00001D                      0 times cond 6 was false ( -1.#J%)
HHC00001D                      0 times cond 7 was false ( -1.#J%)
HHC00001D                      0 times cond 8 was false ( -1.#J%)
HHC00001D                      0 times cond 9 was false ( -1.#J%)
HHC00001D

--------------------------------------------------------------------------------

<b>ICKDSF32, Native, S/390</b>

HHC02204I ARCHLVL        set to ESA/390
HHC01603I loadcore "c:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ICKDSF32\ICKDSF32.core"
HHC02250I Loading file c:\Users\Fish\Documents\Visual Studio 2008\Projects\MyProjects\ASMA-0\ICKDSF32\ICKDSF32.core to location 0
HHC02249I Operation complete
HHC01603I $test fish zero
HHC00001D fish: zero!
HHC01603I $test fish start
HHC00001D fish: start!
HHC01603I restart
HHC02228I restart key pressed
HHC00809I Processor CP00: disabled wait state 000A0000 00000000
HHC01603I $test fish stop
HHC00001D fish: stop!
HHC00001D
HHC00001D HOST:                0 HITS   (  0.00%)
HHC00001D HOST:        <b><i>2,734,670 MISSES (100.00%)</i></b>
HHC00001D HOST:        2,734,670 TOTAL
HHC00001D                      0 times cond 1 was false (  0.00%)
HHC00001D              <b>2,734,668 times cond 2 was false (100.00%)</b>
HHC00001D                      0 times cond 3 was false (  0.00%)
HHC00001D                      2 times cond 4 was false (  0.00%)
HHC00001D                420,725 times cond 5 was false ( 15.38%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D
HHC00001D GUEST:               0 HITS   ( -1.#J%)
HHC00001D GUEST:               0 MISSES ( -1.#J%)
HHC00001D GUEST:               0 TOTAL
HHC00001D                      0 times cond 1 was false ( -1.#J%)
HHC00001D                      0 times cond 2 was false ( -1.#J%)
HHC00001D                      0 times cond 3 was false ( -1.#J%)
HHC00001D                      0 times cond 4 was false ( -1.#J%)
HHC00001D                      0 times cond 5 was false ( -1.#J%)
HHC00001D                      0 times cond 6 was false ( -1.#J%)
HHC00001D                      0 times cond 7 was false ( -1.#J%)
HHC00001D                      0 times cond 8 was false ( -1.#J%)
HHC00001D                      0 times cond 9 was false ( -1.#J%)
HHC00001D

--------------------------------------------------------------------------------
</pre>

The above results are not too terribly interesting since the 100% TLB miss rate can be easily explained as being the result of running "real" (i.e. with DAT _off_).

The below results for the _same test_ running under a z/VM _guest_ however, are _**very**_ interesting!!

<pre>
--------------------------------------------------------------------------------

<b>z/VM 6.3, ICKDSF32, S/390 guest (ipl cms)</b>

HHC01603I $test fish start
HHC00001D fish: start!
HHC01603I $test fish stop
HHC00001D fish: stop!
HHC00001D
HHC00001D HOST:      319,827,175 HITS   ( 95.14%)
HHC00001D HOST:       16,348,787 MISSES (  4.86%)
HHC00001D HOST:      336,175,962 TOTAL
HHC00001D                139,098 times cond 1 was false (  0.85%)
HHC00001D                550,887 times cond 2 was false (  3.37%)
HHC00001D                480,825 times cond 3 was false (  2.94%)
HHC00001D                450,677 times cond 4 was false (  2.76%)
HHC00001D             15,317,546 times cond 5 was false ( 93.69%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D
HHC00001D GUEST:       <b>2,742,644 HITS   ( 84.97%)</b>
HHC00001D GUEST:         <b>485,094 MISSES ( 15.03%)</b>
HHC00001D GUEST:       3,227,738 TOTAL
HHC00001D                      0 times cond 1 was false (  0.00%)
HHC00001D                      <b>0 times cond 2 was false (  0.00%)</b>
HHC00001D                 10,705 times cond 3 was false (  2.21%)
HHC00001D                 89,798 times cond 4 was false ( 18.51%)
HHC00001D                435,487 times cond 5 was false ( 89.77%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D

--------------------------------------------------------------------------------

<b>z/VM 6.3, ICKDSF64, z/Arch guest (ipl zcms)</b>

HHC01603I $test fish start
HHC00001D fish: start!
HHC01603I $test fish stop
HHC00001D fish: stop!
HHC00001D
HHC00001D HOST:      325,226,666 HITS   ( 95.20%)
HHC00001D HOST:       16,385,810 MISSES (  4.80%)
HHC00001D HOST:      341,612,476 TOTAL
HHC00001D                138,869 times cond 1 was false (  0.85%)
HHC00001D                518,603 times cond 2 was false (  3.16%)
HHC00001D                490,790 times cond 3 was false (  3.00%)
HHC00001D                409,339 times cond 4 was false (  2.50%)
HHC00001D             15,378,275 times cond 5 was false ( 93.85%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D
HHC00001D GUEST:         <b><i>461,937 HITS   ( 14.52%)</i></b>
HHC00001D GUEST:       <b><i>2,720,210 MISSES ( 85.48%)</i></b>
HHC00001D GUEST:       3,182,147 TOTAL
HHC00001D                      0 times cond 1 was false (  0.00%)
HHC00001D              <b>2,682,974 times cond 2 was false ( 98.63%)</b>
HHC00001D                 10,397 times cond 3 was false (  0.38%)
HHC00001D                 88,436 times cond 4 was false (  3.25%)
HHC00001D                434,683 times cond 5 was false ( 15.98%)
HHC00001D                      0 times cond 6 was false (  0.00%)
HHC00001D                      0 times cond 7 was false (  0.00%)
HHC00001D                      0 times cond 8 was false (  0.00%)
HHC00001D                      0 times cond 9 was false (  0.00%)
HHC00001D

--------------------------------------------------------------------------------
</pre>

_VERY_ interesting (not to mention _enlightening!_), yes?!

The TLB hit/miss rate has flip-flopped completely between running in z/Arch mode as compared to running in S/390 mode! In normal S/390 mode (ipl cms), the hit rate is 85% and the miss rate is 15%, but when the same test is run in z/Arch mode, the TLB hit/miss rate flip-flops to a 15% TLB hit rate and an _85%_ TLB _miss_ rate!

And look at which of the 5 conditions is causing the TLB miss most often: condition 2! The second of the 5 required conditions for a TLB hit to occur:

```C
(
     (regs->CR( regs->AEA_AR( arn )) == regs->tlb.TLB_ASD( TLBIX( addr )))
  || (regs->AEA_COMMON( regs->AEA_AR( arn )) & regs->tlb.common[ TLBIX( addr ) ])
)
```
___
_SIDE BAR: the exact same phenomenon occurs when your `toto exec` test is run under zcms as opposed to running under cms too! A complete flip-flop of the TLB hit/miss rates! (but in the case of the `toto exec` test, the rates are even worse! 100% hit, 0%miss for S/390 cms to a 0% hit and 100% miss for z/Arch zcms! Refer to my posted test results in the "Performance issue in z/Arch architecture mode (visible under SIE)" issue #222._
___

I'm not sure why condition 2 is failing but that will definitely be my next goal. I'm going to stick some PTT traces in the `maddl` function to see what values are being passed to the function and what the values in the TLB entry are. Something very weird (or very _wrong!_) is going on somewhere!

When I have something more to share I'll post them, but probably in issue #222 and not here since I firmly believe whatever is causing the issue #222 slowdown is very likely the same problem (same bug) that's causing Moshix's dasd formatting under z/VM problem too (i.e. this very issue, #201).

That's all for now. I'm going to stop working on this issue and concentrate my efforts on _your_ issue, issue #222.

Thanks for listening.

______
(*) **NOTE:** the attached patch was created _before_ you did your "Move MADDRL Logic from feature.h to dat.h" commit, so it probably won't apply cleanly to current git:

* [fish-maddrl.zip](https://github.com/SDL-Hercules-390/hyperion/files/3511906/fish-maddrl.zip)

I'll pull your commit and re-work my patch and post a new updated patch in a few minutes(?). I just wanted to get my test results posted as soon as I could since they're so enlightening!

**Comment by moshix** [comment] 2019-08-17 12:30
thanks, Fish and Ivan. Will try this out once you have a decided how to patch this, and will report back here. 

thanks

M

**Comment by Fish-Git** [comment] 2019-08-18 12:36
> Thanks, Fish and Ivan. Will try this out once you have a decided how to patch this, and will report back here.
> 
> thanks
> 
> M

There's nothing to try out yet!

Once we have a fix ready we'll let you know. &nbsp;_**THEN**_ you'll have something to try out!

**Comment by Fish-Git** [comment] 2019-09-17 19:41
**FYI:** I'm still looking into this issue. It's going very slow (much like the formatting! Heh!), but I'm starting to make some _gradual_ (incremental) progress...

**Comment by Fish-Git** [comment] 2019-09-20 10:14
I have pulled my hair out for months on this issue and have made absolutely no progress whatsoever towards determining the cause. All evidence points to this is just how z/VM behaves. The bulk of the inefficiency _appears_ to be with the overheard involved in z/VM's CCW translation logic translating CMS guest I/O. (There is a slight inefficiency involved in performing the actual I/O and interrupt handling too, compared with performing native (non-z/VM, i.e. stand-alone) I/O, but I could not find the cause of that either.)

I am going to have to close this issue as unresolved as I honestly feel no more progress can be made in trying to resolve it. If anyone else wants to give it a try I encourage them to give it a try. As for myself, I'm giving up!

**Closed by Fish-Git** 2019-09-20 10:14 UTC
Labels: (Unknown), HELP!, Ongoing, Researching...

**Comment by Fish-Git** [comment] 2019-09-20 10:23
One thing we _could_ maybe do is maybe write a new ICKDSF Hercules utility to format a dasd the same way that ICKDSF does. This utility would perform the format under the host, just like `dasdinit`, etc, and thus would be _much_ faster than doing the same thing under z/VM. If such a utility is desirable let me know and I'll try to code one.

_(**OR...** we could maybe add a new option to `dasdinit` instead, similar to the existing `-linux` option.)_
