### ISSUE TITLE
ABEND S0CD RSN=xxxx08xx in JES2 in z/OS 2.4

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#310] opened 2020-06-14 11:14 UTC
And ABEND S0CD RSN=xxxx08xx occurs in JES2 in z/OS 2.4, running first or second level (i.e. natively _or_ under z/VM): 
```
IEA045I AN SVC DUMP HAS STARTED AT TIME=08.19.33 DATE=06/14/2020 
FOR ASIDS(001C,0003,0001)                                        
ERROR ID = SEQ00022 CPU03 ASID001C TIME08.19.33.3                
QUIESCE = YES                                                    
$HASP078 CKPTONDA SUBTASK FAILED - ABEND S03C RC=2D000810        
IEA794I SVC DUMP HAS CAPTURED: 597                               
DUMPID=002 REQUESTED BY JOB (JES2    )                           
DUMP TITLE=COMPON=RSM,COMPID=SC1CR,ISSUER=IARQFDMP,FAILMOD=IAXV  
           H+0777C,EP=IARVHPGF,AB=S03C,RSN=2D000810              
``` 
The System Codes manual states : 

> **03C**
> 
> **Explanation:** A page, a segment, or an ASTE fault occurred. RSM detected one of the following conditions.
> 
> Register 15 contains a hexadecimal reason code. In the reason code, the bytes designated x contain diagnostic data that may be requested by IBM.
> 
>  &nbsp; **Code &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Explanation**
> **xxxx08xx**&nbsp; &nbsp; &nbsp; A program disabled for interrupts held the RSM lock, or a higher lock, when a fault occurred.
> 
> **Source:** &nbsp; &nbsp; &nbsp; &nbsp; Real storage manager (RSM)

I suspect this to be caused by a bug in SDL-Hyperion.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2020-06-26 03:35
> I suspect this to be caused by a bug in SDL-Hyperion.

IMPOSSIBLE! SDL Hyperion is PERFECT!  It contains absolute NO BUGS WHATSOEVER! &nbsp; `;-)`

&lt;jk&gt;

**Comment by Fish-Git** [comment] 2020-06-26 20:06
Given that this error is being reported by the "Real storage manager (RSM)" and the fact that we know our TXF implementation is still incomplete and has known problems, I feel this issue too also deserves to be MOVED into the existing Transactional-Execution Facility GitHub Issue #263.

**Comment by Fish-Git** [comment] 2020-06-27 20:56
I have changed my mind!

In order to better track problems likely being caused by our current incomplete/buggy Transactional-Execution Facility implementation, I have decided to create a _**new GitHub Issue Label**_ called _**"TXF"**_ that should be assigned to issues such as this one where we believe the reported problem is likely being caused by our current incomplete (and still buggy) TXF implementation.

While we continue to work on addressing (fixing) various TXF related bugs, problems such as the one this one describes, are likely to occur more and more, and in order to better manage resolving such problems, it is probably better to _**report such problems individually**_ rather than in our existing Issue #263 thread _(which is already very, very long!)._

I have therefore re-opened this issue and have assigned it the new _**"TXF"**_ Label so that we can better track our progress trying to resolve each TXF issue.

My apologies to Peter for originally closing it!

**Comment by Fish-Git** [comment] 2020-08-12 22:26
Since this bug was reported well _before_ my "NUT CRACKED!" series of TXF commits made on July 23, I need to ask whether this problem (bug report) is still valid or not, or whether it can now be closed?

Thanks.

**Comment by Peter-J-Jansen** [comment] 2020-08-13 07:49
Since the "NUT CRACKED!" series of TXF commits this problem was no longer experienced by me. So perhaps we should close this one.

I've just only now discovered your latest series of TXF related commits, so I will be trying these and respond to your other replies as soon as I have something useful to tell.

Thanks,

Peter

**Closed as completed** 2020-08-14 15:35 UTC
Labels: BUG, TXF
