### ISSUE TITLE
Hyperion performance hit - recently introduced

### ISSUE THREAD

**Issue by wably** [SDL-Hercules-390/hyperion#365] opened 2021-01-25 13:18 UTC
Hey Fish,  (@Fish-Git )

After the fresh repo clone this morning to test your MVCOS patch, SDL Hyperion seems to have taken a significant performance hit when compared to the previous repo clone that I was using.

My previous clone of the repo was done on January 4.  The latest was this morning, Jan 25.

I thought the new repo build seemed slower but then I confirmed it with some simple, straight-up tests.   Depending on the test, execution times have increased 50%, to over 100% in another case.  Here are some examples:

Using MVS 3.8 TK4, a simple assembly of the Stage1 system generation macros. Clock time:
1/4 repo:  29 sec
1/25 repo:  63 sec

Using VM/370 R6 Sixpack, 10 smaller assemblies back to back in an EXEC.  Clock time:
1/4 repo:  9 sec
1/25 repo:  15 sec

Obviously, this was not your MVCOS patch as neither of these systems use that instruction. But something was committed since January 4 that is pretty expensive.

Regards,
Bob

**Comment by wably** [comment] 2021-01-25 16:11
Here is some documentation; two MVS and Hercules logs. One from the Jan 4 repo, and one from Jan 25 repo.  At the top of each log of course is the Hyperion version info, and at the end of the logs is the simple assembly job HERC01S.  Look at the times for start and end for that job in each log.

The version information shows modified; for Jan 25 that is the MVCOS.patch that was applied this morning.  For the Jan 23 build (which is from the Jan 4 repo) I have a small modification to ecpsvm.c, which is not in play in these timing tests; since this is MVS and not VM.

[repo0125.txt](https://github.com/SDL-Hercules-390/hyperion/files/5867816/repo0125.txt)
[repo0104.txt](https://github.com/SDL-Hercules-390/hyperion/files/5867817/repo0104.txt)

Regards,
Bob

**Comment by Fish-Git** [comment] 2021-01-25 20:54
> Obviously, this was not your MVCOS patch as neither of these systems use that instruction.

I beg to differ.

The patch, which fixes the MVCOS problem, had to be made to the _**`maddr_l`**_ function in `dat.h`, which is _**the**_ primary address translation function in Hercules! (that checks for a TLB hit and if found, returns the already previously translated mainstor address to the caller, or else does a full blown address translation on a TLB miss)

This affects the address translation of _all_ Hercules supported architectures, including System/370, _regardless_ of whether the MVCOS instruction is being executed or not.

I suspect the problem is that the function itself is now slightly more complicated (i.e. larger) whereas before it was much simpler and more straightforward (i.e. smaller, code-wise).

Almost all of the extra code that was added (i.e. the extra complication that I added that makes the function slightly larger than it was before) was to, for the special `USE_ARMODE` case (which seems to be mostly (only?) used by the MVCOS instruction and apparently _very_ rarely used (if at all!) in all other cases), determine the correct CR to use in the subsequent TLB hit check logic which immediately follows it (and which all other non-USE_ARMODE cases use extensively). That's why I added those LOGMSG statements: I wanted to see how often such specialized `USE_ARMODE` calls were being made to `maddr_l` and thus whether or not it would be worth trying to check for a TLB hit or not in such situations. Apparently it's not, as it introduces too much extra code for _very_ little benefit.

The likely fix (to this, your newly reported performance issue) is probably to rip our all of that code and to instead simply force a TLB miss for the special `USE_ARMODE` case. Doing that would only add two instructions to the function's existing code path (possibly less, depending on how the optimizer ends up optimizing it): one `if` statement and another to set `aea_crn` to zero to bypass the TLB hit logic:

(Existing experimental MVCOS fix logic):
```C
    int  aea_crn;
    U16  tlbix    = TLBIX( addr );
    BYTE *maddr   = NULL;

    /* Forced AR-mode address translation? */
    if (arn >= USE_ARMODE)
    {
        /* Retrieve ALET from AR */
        U32 alet = (ARN( arn ) == 0) ? 0 :
                   /* Guest ALET if XC guest in AR mode */
                   (SIE_ACTIVE( regs ) && MULTIPLE_CONTROLLED_DATA_SPACE( GUESTREGS ))
                   ? GUESTREGS->AR( ARN( arn )) :
                   /* If SIE host but not XC guest in AR mode then alet is 0 */
                   SIE_ACTIVE( regs ) ? 0 :
                   /* Otherwise alet is in the access register */
                   regs->AR( ARN( arn ));

LOGMSG("    +++ USE_ARMODE! +++\n");
        /* Convert ALET to corresponding CR number, if possible */
        switch (alet)
        {
            case ALET_PRIMARY:   aea_crn =  1; break;
            case ALET_SECONDARY: aea_crn =  7; break;
            case ALET_HOME:      aea_crn = 13; break;
            default:             aea_crn =  0; break;
        }
    }
    else
    {
        /* Normal PSW-based address translation */
        aea_crn = regs->AEA_AR( arn );
    }
```

(Proposed new MVCOS fix logic):
```C
    int  aea_crn  = (arn >= USE_ARMODE) ? 0 : regs->AEA_AR( arn );
    U16  tlbix    = TLBIX( addr );
    BYTE *maddr   = NULL;
```

Doing that instead would probably speed things back up to the same performance level we were at before (while still  resolving our MVCOS problem too).

Give that a try and let me know whether it helps any.

Thanks.

**Comment by wably** [comment] 2021-01-25 21:06
Fish,

Just so that I am clear, am I to replace the *entire* large code block in your prior post with the short proposed 3 line code block?  Or, am I to leave the large code block in place and just replace only the first three lines of that block with the statements in the proposed smaller block in your post?

Bob

**Comment by Fish-Git** [comment] 2021-01-25 21:09
> Just so that I am clear, am I to replace the _entire_ large code block in your prior post with the short proposed 3 line code block? Or, am I to leave the large code block in place and just replace only the first three lines of that block with the statements in the proposed smaller block in your post?

The former: replace the _entire_ code block with just those three statements.

**Comment by wably** [comment] 2021-01-25 21:53
Fish,

Ok, I made the change (shown below for your confirmation).  It did not improve the performance at all; the timings are the same as earlier.  My MVCOS test suite still completes successfully as well.

here's the change I made and then did a Clean then Build.  I also show just a tiny bit of the  statements preceeding and after this change, for your placement reference:

>        (which is many, many instructions)
    */

    int  aea_crn  = (arn >= USE_ARMODE) ? 0 : regs->AEA_AR( arn );
    U16  tlbix    = TLBIX( addr );
    BYTE *maddr   = NULL;

> // int aea_crn;
// U16 tlbix = TLBIX( addr );
// BYTE maddr = NULL;
//
// / Forced AR-mode address translation? /
// if (arn >= USE_ARMODE)
// {
// / Retrieve ALET from AR /
// U32 alet = (ARN( arn ) == 0) ? 0 :
// / Guest ALET if XC guest in AR mode /
// (SIE_ACTIVE( regs ) && MULTIPLE_CONTROLLED_DATA_SPACE( GUESTREGS ))
// ? GUESTREGS->AR( ARN( arn )) :
// / If SIE host but not XC guest in AR mode then alet is 0 /
// SIE_ACTIVE( regs ) ? 0 :
// / Otherwise alet is in the access register /
// regs->AR( ARN( arn ));
//LOGMSG(" +++ USE_ARMODE! +++\n");
// / Convert ALET to corresponding CR number, if possible /
// switch (alet)
// {
// case ALET_PRIMARY: aea_crn = 1; break;
// case ALET_SECONDARY: aea_crn = 7; break;
// case ALET_HOME: aea_crn = 13; break;
// default: aea_crn = 0; break;
// }
// }
// else
// {
// / Normal PSW-based address translation */
// aea_crn = regs->AEA_AR( arn );
// }

   
   /* Non-zero AEA Control Register number? */
    if (aea_crn)

Sorry, I know that this didn't paste nicely, but these blocks above are all continuous in the order shown, in dat.h

Regards,
Bob

**Comment by wably** [comment] 2021-01-25 22:18
Fish,

Just to be sure of things, I eliminated the MVCOS patch by just now re-cloning the repo and fresh build.  No MVCOS patch.   As expected, my MVCOS test suite fails.  As for the performance issue, it is a lot better but still not as good as the January 4th repo.  So, here are the updated numbers  (all MVS TK4  stage1 assembly job clock time)

Jan 4 repo:  29 sec
Jan 25 repo w MVCOS patch (either one):  63 sec
Jan 25 repo direct clone, no changes:  39 sec

Regards,
Bob

**Comment by wrljet** [comment] 2021-01-25 22:29
Bob,

If you're not aware of it, there is a feature of `git` called `bisect`, that is useful for tracking down things like this.

Basically `git bisect` keeps track of doing a binary search for you.  But you will have to build and test manually at
each step for a project this complex.

I used it successfully when the non-SDL Hyperion didn't work for me while installing zLinux.

Bill

**Comment by wably** [comment] 2021-01-25 23:15
Bill,

Thanks; I was not aware of this tool.  I just read about it though after your mention and it looks ideal.  What should be specified for the revision number for bisect good or bisect bad?  Something like the 10386 commit number, etc?

Does it reclone the repo each time into a new directory or does it just modify your existing clone to match the commit in the binary search ?

Bob

**Comment by wrljet** [comment] 2021-01-25 23:26
Bob,

You use the commit hash ID.  It will accept an abbreviated hash.  The last commit before Jan 4 is:

`https://github.com/SDL-Hercules-390/hyperion/commit/cee323ba234487574ff2fc90e724181e3aa3b38b`

So you can specify `cee323ba` for that commit.

Something like this should work:
```
git checkout master
git stash save
git bisect start
git bisect bad
git bisect good cee323ba
```

Then build everything and test.

If it worked correctly, you next use:
```
git bisect good
```

If it didn't work correctly, you next use:
```
git bisect bad
```

Then rebuild and test again.
And keep looping with good and bad until it tells you the commit that is the first bad one.

I recommend writing down the steps you're taking and the commit hashes, as it's easy
to get confused with it all.

Bill

**Comment by ivan-w** [comment] 2021-01-25 23:37
Bill,

"git bisect log" is good for that too ;)

--Ivan

**Comment by wably** [comment] 2021-01-25 23:38
Bill,

I'm on my way; already building the first bisect indicated.  Great stuff, thanks!

Bob

**Comment by wably** [comment] 2021-01-26 00:09
Ok, it looks like it is commit ac43035 from January 5.  See the attached image.  This build resulted in a 39 second run time, so a 10 second increase from the prior commit, or roughly 30% worse performance for this test case.

![Image1](https://user-images.githubusercontent.com/25064540/105781523-b7bb8e80-5f40-11eb-8aa9-ffe2541059a4.jpg)

Bob

**Comment by Fish-Git** [comment] 2021-01-26 00:30
> Ok, it looks like it is commit [ac43035](https://github.com/SDL-Hercules-390/hyperion/commit/ac430350c4d17851589e292fbc61677b6c109932) from January 5. See the attached image. This build resulted in a 39 second run time, so a 10 second increase from the prior commit, or roughly 30% worse performance for this test case.

_&lt;BOGGLE!&gt;_

That doesn't make any sense! WTF does defining a longer facility list (with more modifiable bits in it) have to do with _performance?!_

I'm confused! &nbsp; _(whimper)_

&nbsp; `:(`

**Comment by wably** [comment] 2021-01-26 00:53
I agree.  I am at a loss myself.   Is there a git command that I can use to set my copy of the project to the commit immediately before ac43035 ?

Bob

**Comment by Fish-Git** [comment] 2021-01-26 01:19
> Is there a git command that I can use to set my copy of the project to the commit immediately before [ac43035](https://github.com/SDL-Hercules-390/hyperion/commit/ac430350c4d17851589e292fbc61677b6c109932)?

I don't know. Probably. But in such situations I've always just "exported" the desired commit to a .zip file somewhere, and then built and tested using that. Of course, being an export, the git repository control information is not included so Herc's reported version number will not include the commit hash. It'll just report a generic "4.4.9999".

I'm not that skilled at git myself! I cheat and use TortoiseGit instead, which provides a nice GUI to it integrated nicely into Windows itself, thereby making doing routine git things trivially easy. But I've never used it to do any git bisects or what you're wanting to do. Sorry! Maybe someone more skilled at git can tell us how we can maybe do it via the command-line?

**Comment by Fish-Git** [comment] 2021-01-26 04:50
> Using VM/370 R6 Sixpack, 10 smaller assemblies back to back in an EXEC.

Can you post your exec? And the assembler files it's compiling? I'd like to try it for myself.

Because I just did a quick test of my own using DOS/VS R34: an assembly of the DOS/VS supervisor, which is quite large, and should serve nicely IMO as a reasonably comparable test, and across 4 back-to-back assemblies, there was no difference in speed (job duration) between official 4.3 and current git.

So I'm apparently not seeing the same performance degradation that you're seeing.

But like I said, I'd like to try doing a more closely similar test using VM/370 R6, so if you could post the source for the file being assembled as well as your little test EXEC that assembles them, I'd like to see if I can reproduce your claimed performance hit, because in all my tests I'm not seeing _ANY_ type of performance hit whatsoever.

&lt;shrug&gt;

Thanks.

**Comment by wably** [comment] 2021-01-26 12:32
Fish,

I withdraw my complaint.

After a fresh clone and build this morning, I find that I cannot recreate the performance issue, either with VM or MVS.  I have no explanation.  Maybe I had something contaminated in my builds yesterday, even though I followed the same procedure today.  My PC was shutdown overnight and had a fresh re-boot this morning.  Those are literally the only differences.

As a side note, since you committed the MVCOS fix yesterday, my test suite still passes on this morning's build, so it all looks good.

I sincerely apologize to you and Bill for the apparent false alarm and for the time wasted over it.

Regards,
Bob

**Comment by wrljet** [comment] 2021-01-26 14:57
> I agree. I am at a loss myself. Is there a git command that I can use to set my copy of the project to the commit immediately before [ac43035](https://github.com/SDL-Hercules-390/hyperion/commit/ac430350c4d17851589e292fbc61677b6c109932)?
> 
> Bob

`git checkout HEAD^1` will move you to the commit just before the one you're sitting out.
Moving forward is more complicated so I'll skip that for now.

`git checkout <hash>` will move you to any specific commit.
In this case `git checkout 093ce24b`

You can find the hash for the commit you're interested in by looking on GitHub at the commit history.

Bill

**Comment by wrljet** [comment] 2021-01-26 15:03
> Bill,
> 
> "git bisect log" is good for that too.  `;-)`
> 
> --Ivan

Thanks for that tip.

**Comment by Fish-Git** [comment] 2021-01-26 17:24
> I withdraw my complaint.
> 
> After a fresh clone and build this morning, I find that I cannot recreate the performance issue, either with VM or MVS. I have no explanation. &nbsp;[ ... ]&nbsp; My PC was shutdown overnight and had a fresh re-boot this morning. Those are literally the only differences.

Great! (I think?)

It is indeed good to news the problem has disappeared, although it's not such good news that we don't know what was causing it in the first place of course. _That's_ somewhat worrisome.

Oh well. I guess we could blame our favorite scapegoat: Microsoft! (i.e. Windows!) &nbsp;`;-)`

Closing issue.

> I sincerely apologize to you and Bill for the apparent false alarm and for the time wasted over it.

There's no need for any apology IMO, Bob, but I accept it anyway. These things occasionally happen from time to time, and you did the right thing by reporting it.

Take care.

**Closed as completed by Fish-Git** 2021-01-26 17:24 UTC
Labels: User Error, Unknown

**Comment by wrljet** [comment] 2021-01-26 17:31
The more you know about all this computer stuff, the more amazing it is that _anything ever works_! :-)

And now more people know about `git bisect`, so there's a plus for the exercise.

Bill
