### ISSUE TITLE
FreeBSD port - "devtype 3270 not recognized"

### ISSUE THREAD

**Issue by vmisev** [SDL-Hercules-390/hyperion#568] opened 2023-06-01 08:07 UTC
___
_**NOTE:** &nbsp; This issue appears to be a **duplicate** of issues [**431**](https://github.com/SDL-Hercules-390/hyperion/issues/431) and [**552**](https://github.com/SDL-Hercules-390/hyperion/issues/552)._
___
I'm trying to make FreeBSD port/pkg for SDL-Hercules-390 / hyperion / Release_4.5
(It will be nice for users to just ```pkg install hyperion``` )

Hyperion 4.5 code builds and runs, but I'm having problem with 
```
"devtype 3270 not recognized; Previous message from function 'attach_device' at config.c(1310)"; 
```
also, same for devtype 3088, 3215 and 3287.

hercifc is built w setuid: ```--enable-setuid-hercifc```

All relevant files (ports Makefile, patches and tk4- start_herc and log/3033.log) are here:
https://github.com/vmisev/hyperion-freebsd-port

Two patch files in the https://github.com/vmisev/hyperion-freebsd-port/tree/main/hyperion/files are moded from FreeBSD port emulator/hercules (v3.13)

I also have an old manual build (not using FreeBSD ports infra; code from @srorso) v4.0.0.8852 and on FreeBSD 12.0 that build works - x3270 connects, but on 13.2-RELEASE there is the same problem: "devtype 3270 not recognized"

My OS is FreeBSD 13.2-STABLE; amd64; kernel 1302505

**Comment by wrljet** [comment] 2023-06-01 15:36
Vladimir,

Your 3270 problem is not related to `hercifc`.  Hercules cannot find its loadable modules.

These would normally be installed in a `lib/hercules` directory sitting parallel to the `bin` dir.

Try pointing `LD_LIBRARY_PATH` to the `lib` directory created by your `make install` and see if that helps.

But, a *lot* has changed in the overall configure and build process between Hercules 3.x and SDL-Hercules Hyperion 4.x.

Bill

**Comment by Fish-Git** [comment] 2023-06-01 16:04
Bill is correct: the build procedure for SDL Hercules 4.x is different from Hercules 3.x.

You need to _CLOSELY_ follow the build procedure as documented here:

* https://sdl-hercules-390.github.io/html/hercinst.html#install

Pay especially close attention to step 5: the building of the External Packages.

Bill has written a helper script that completely automates the building of SDL Hyperion 4.x Hercules, called "hercules-helper" (https://github.com/wrljet/hercules-helper). I recommend using it to build SDL Hercules with rather than try building it yourself.

Closing as duplicate of 431 and 552.

**Closed as completed by Fish-Git** 2023-06-01 16:04 UTC
Labels: Duplicate, User Error

**Comment by wrljet** [comment] 2023-06-01 20:58
Vladimir,

Hercules-Helper builds the external packages.
And it prepares a simple script at the end to set the PATH and LD_LIBRARY_PATH to match what was built.
(normally added to `.bashrc`)

It also will create a build log with all the steps that were actually performed.
While not 100% ready to run, that will show you all the important things, like the `configure` options used, etc.

Bill

**Comment by vmisev** [comment] 2023-06-01 20:59
Using [hercules-helper](https://github.com/wrljet/hercules-helper) from @wrljet everything builds and runs okay, on FreeBSD 13.2-STABLE (even with using clang 15)

The thing is, now all executables and libs are in the same dir; 
God help me with making a port out of that :wink: 

Thank you very much for your help. :smile: 

![SDL-Hyperion](https://github.com/SDL-Hercules-390/hyperion/assets/1068869/c6ca03e7-c891-41f7-928c-e4707c96fb12)

**Comment by vmisev** [comment] 2023-06-01 21:03
Using [hercules-helper](https://github.com/wrljet/hercules-helper) from @wrljet everything builds and runs okay, on FreeBSD 13.2-STABLE (even with using clang 15)

The thing is, now all executables and libs are in the same dir;
God help me with making a port out of that :wink: 

Thank you very much for your help. :smile: 

![Screenshot_20230601_230134](https://github.com/SDL-Hercules-390/hyperion/assets/1068869/b9d6e813-34e6-4a2d-811d-73f293bc1be2)

**Comment by wrljet** [comment] 2023-06-01 21:06
The resulting layout should look like this (give or take):

```
[bill@freebsd132-vm /usr/home/bill/herctest/herc4x]$ ls bin
cckd2ckd        cckddiag        cfba642fba      dasdconv64      dasdlist        dasdser         hercules        tapecopy        vmfplc2
cckd642ckd      cckddiag64      ckd2cckd        dasdcopy        dasdload        dmap2hrc        hetget          tapemap
cckdcdsk        cckdmap         ckd2cckd64      dasdcopy64      dasdload64      fba2cfba        hetinit         tapesplt
cckdcdsk64      cckdswap        convto64        dasdinit        dasdls          fba2cfba64      hetmap          tfprint
cckdcomp        cckdswap64      dasdcat         dasdinit64      dasdpdsu        hercifc         hetupd          tfswap
cckdcomp64      cfba2fba        dasdconv        dasdisup        dasdseq         herclin         maketape        txt2card
[bill@freebsd132-vm /usr/home/bill/herctest/herc4x]$ ls lib
hercules                libherc.la              libhercd.so             libherct.la             libhercu.so
libhdt3420_not_mod.la   libherc.so              libhercs.la             libherct.so
libhdt3420_not_mod.so   libhercd.la             libhercs.so             libhercu.la
[bill@freebsd132-vm /usr/home/bill/herctest/herc4x]$ ls lib/hercules
dyncrypt.la     hdt1052c.la     hdt2703.la      hdt3088.la      hdt3420.la      hdt3525.la      hdtdummy.la     hdtptp.la       hdttcpnje.la
dyncrypt.so     hdt1052c.so     hdt2703.so      hdt3088.so      hdt3420.so      hdt3525.so      hdtdummy.so     hdtptp.so       hdttcpnje.so
dyngui.la       hdt1403.la      hdt2880.la      hdt3270.la      hdt3505.la      hdt3705.la      hdteq.la        hdtqeth.la      hdtzfcp.la
dyngui.so       hdt1403.so      hdt2880.so      hdt3270.so      hdt3505.so      hdt3705.so      hdteq.so        hdtqeth.so      hdtzfcp.so
```

The executable programs and shared libraries are not in the same directory.

Bill

**Comment by vmisev** [comment] 2023-06-01 21:26
ah, sorry I was looking into hercules-helper/hyperion/build

everything is neat in hercules-helper/herc4x

**Comment by wrljet** [comment] 2023-06-01 21:28
Hercules-Helper does an out-of-source-tree build.  The `build` dir is where that happens.

By default it "installs" in `herc4x`.  But that, and almost everything else, is configurable.
You can configure it to install in /usr/local if desired.

Bill
