### ISSUE TITLE
Building SDL Hercules from source on 32-bit (i686) Debian 10.6

### ISSUE THREAD

**Issue by AllardKrings** [SDL-Hercules-390/hyperion#333] opened 2020-11-21 11:40 UTC
Hi,

I am trying to build SDL Hercules from source from inside VirtualBox having installed Debian 10.6 inside the VirtualBox. The Guest OS is Windows 10.

I have followed the [instructions on Geronimo's site](https://geronimo370.nl/s370/hercules-installing/installing-sdl-hyperion/) but I get an error when compiling the external packages.

```
crypto ...
   64-bit Debug...
   FAILED
```

Maybe this has to do with cpu unknown?

Any ideas how I can fix this?

Allard

**Comment by wrljet** [comment] 2020-11-21 15:45
Allard,

I will do my best to help you figure this out.

If you followed the Geronimo directions exactly, you would have attempted to build the external packages before
cloning the Hercules repo and have not yet run `bldlvlck`.

If this is the case, I recommend that you first do this:

```
mkdir ~/sdl42
cd ~/sdl42
git clone https://github.com/SDL-Hercules-390/hyperion.git
cd hyperion
util/bldlvlck
```

Post the output from `bldlvlck` here.

And please post:
- your bash command history showing your build steps
- output from  `uname -m`

Take a look at  `extpkgs/build/crypto/crypto.log`
If it's not too long, you could post that as well, or if it seems to be very long, look at the end for a hint of
what's wrong and post that.

Thanks,
Bill

**Comment by AllardKrings** [comment] 2020-11-22 07:05
Hi Bill,

thanks for your quick reply!

Below is the output :

Output bldlvlck:
===========

This utility will check the level of various utilities needed to build
hercules. Checking is done against versions that are KNOWN to work.
This doesn't mean a build will NOT succeed with older versions
of the utilities, but will give a hint as to what package may need
an upgrade if the build ever fails with some odd reason.


OK	autoconf requires 2.64, found 2.69

OK	automake requires 1.9, found 1.16.1

OK	cmake requires 3.2, found 3.13.4

OK	flex requires 2.5, found 2.6.4

OK	gawk requires 3.0, found 4.2.1

OK	gcc requires 4.6.2, found 8.3.0

OK	grep requires 1, found 3.3

OK	ld requires 2.22, found 2.31.1

OK	m4 requires 1.4.6, found 1.4.18

OK	make requires 3.79, found 4.2.1

OK	perl requires 5.6, found 5.28.1

OK	sed requires 3.02, found 4.7

Output of uname -m:
================

i686

Hope this helps!

Kind regards Allard

**Comment by AllardKrings** [comment] 2020-11-22 07:09
and here's the output of cmdline = extpkgs.sh c d s t

action         =  BUILD
crypto_repo    = "/home/allard/extpkgs/repos/crypto-0"
decnumber_repo = "/home/allard/extpkgs/repos/decNumber-0"
softfloat_repo = "/home/allard/extpkgs/repos/SoftFloat-0"
telnet_repo    = "/home/allard/extpkgs/repos/telnet-0"
install_dir    = "/home/allard/extpkgs/."
cpu            = "unknown"
crypto ...
  64-bit Debug ...
  FAILED!

**Comment by AllardKrings** [comment] 2020-11-22 07:18
and finally crypto.log:

mdline = build --pkgname . --rebuild --cpu unknown --arch 64 --config Debug --install /home/allard/extpkgs/.

Build of 64-bit Debug version of crypto begun on zo 22-11-20 at 08:07:29

Configuring crypto64.Debug ...

-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ SOURCE_DIR '/home/allard/extpkgs/repos/crypto-0' 
++ BINARY_DIR '/home/allard/extpkgs/build/crypto/crypto64.Debug' 
++ BINARY_DIR_NAME 'crypto64.Debug' 
++ TRUNCATED_BINARY_DIR '/home/allard/extpkgs/build/crypto' 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
++ BINARY_HLQ '/home/allard/extpkgs/build/crypto' 
++ BINARY_DIR 'crypto64.Debug' 
++ _xxxxx 'crypto64' 
++ CONFIG 'Debug' 
++ CMAKE_BUILD_TYPE 'Debug' 
++ BASENAME 'crypto' 
++ BITNESS '64' 
++ CONFIG 'Debug' 
++ DBGCHAR 'd' 
++ SUFFIX '64d' 
++ FULLNAME 'crypto64d' 
++ CMAKE_BINARY_DIR '/home/allard/extpkgs/build/crypto/crypto64.Debug' 
++ CMAKE_INSTALL_PREFIX '/home/allard/extpkgs' 
++ LIB_INSTALL_DIR 'lib/unknown' 
-- Found Git: /usr/bin/git (found version "2.20.1") 
++ GIT_COMMIT_COUNT '38' 
++ GIT_HASH7 '53dda21' 
++ GIT_MODIFIED '' 
Building crypto64d version 1.0.0.38-g53dda21
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test OK
-- Performing Test OK - Success
++ CMAKE_C_FLAGS_DEBUG '-g           -D LITTLE_ENDIAN=1234 -D BIG_ENDIAN=4321 -D BYTE_ORDER=LITTLE_ENDIAN          -D HAVE_PLATFORM_H -D DEBUG          -D VERS_STRING=1.0.0.38-g53dda21          -m64 -fPIC' 
++ CMAKE_C_FLAGS_RELWITHDEBINFO '-O2 -g -DNDEBUG  -D LITTLE_ENDIAN=1234 -D BIG_ENDIAN=4321 -D BYTE_ORDER=LITTLE_ENDIAN -D HAVE_PLATFORM_H -D VERS_STRING=1.0.0.38-g53dda21 -m64 -fPIC' 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/allard/extpkgs/build/crypto/crypto64.Debug

Building crypto64.Debug ...

Scanning dependencies of target crypto64d
[ 16%] Building C object CMakeFiles/crypto64d.dir/crypto_version.c.o
[ 33%] Building C object CMakeFiles/crypto64d.dir/source/rijndael.c.o
In file included from /home/allard/extpkgs/build/crypto/crypto64.Debug/platform.h:31,
                 from /home/allard/extpkgs/repos/crypto-0/source/rijndael.c:39:
/usr/include/string.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/crypto64d.dir/build.make:76: CMakeFiles/crypto64d.dir/source/rijndael.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/crypto64d.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

ERROR: make has failed! rc=1

Build FAILED on zo 22-11-20 at 08:07:31

**Comment by AllardKrings** [comment] 2020-11-22 07:37
SOLVED!:

Hi Bill, by looking at the crypto log and after doing some googling i installed:

apt-get install gcc-multilib to install the missing 32 bit libraries.

and thtat did the trick:

cmdline = extpkgs.sh c d s t

action         =  BUILD
crypto_repo    = "/home/allard/extpkgs/repos/crypto-0"
decnumber_repo = "/home/allard/extpkgs/repos/decNumber-0"
softfloat_repo = "/home/allard/extpkgs/repos/SoftFloat-0"
telnet_repo    = "/home/allard/extpkgs/repos/telnet-0"
install_dir    = "/home/allard/extpkgs/."
cpu            = "unknown"
crypto ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...
  SUCCESS!
decNumber ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...

**Comment by wrljet** [comment] 2020-11-22 15:01
OK, it just so happens I have a set of changes ready to send to Fish that implements build support in the extpkgs for **_i686_**.

I would say it's pretty rare at this point, though for a current installation (like Debian 10) to be a 32-bit install.

Bill

**Comment by Fish-Git** [comment] 2020-11-22 18:48
Allard wrote:

> By looking at the `crypto.log` and after doing some googling, I installed: `apt-get install gcc-multilib` to install the missing 32 bit libraries, and that did the trick:

Hi Allard!

That's good news! But the important question is, now that you have successfully built the External Packages, have you been able to successfully build _Hercules itself_ afterwards?

**Comment by Fish-Git** [comment] 2020-11-22 18:54
Bill wrote:

> But I would say it's pretty rare at this point, though, for a current installation (like Debian 10) to be a 32-bit install!

I would agree! In today's world 32-bit is indeed quite rare (and becoming rarer with each passing year). I'm thinking that perhaps a change to my `extpkgs.sh` script might be in order? To make the default to build _only_ 64-bit? 32-bit would of course still be supported, but only by request.

Should we make building only 64-bit the default? What do you think?

**Comment by wrljet** [comment] 2020-11-22 19:08
Fish,

I have a pull request sitting here waiting to send to you (for a month now) that adds a i686 target.
I've tested it on Ubuntu 12.04, Debian 8.6, and 9 (all with i686 32-bit installations).

It also acts like what I put in a while ago for 64-bit ARM.  So we don't try to cross build both 32- and 64-bit
at the same time.  No 32-bit on x86 (x64), or a 64-bit on i686 (32-bit).

The changes also document things a bit in `extpkg.sh.ini` so people will see what the universe of
know build targets are, without having to look elsewhere.

I will send it to you soon.

Bill

**Comment by wrljet** [comment] 2020-11-22 20:20
Can we edit the title of this issue to mention the Debian is i686 32-bit?

Bill

**Comment by Fish-Git** [comment] 2020-11-22 21:39
> Can we edit the title of this issue to mention the Debian is i686 32-bit?

Of course!

It would have been nice if you would have offered your own suggested title however, but since you didn't , I had no choice but to use one of my own.

If it's still not to your liking though, then feel free to _please offer your own!_ &nbsp; `;-)`

Thanks. &nbsp; `:)`

**Comment by AllardKrings** [comment] 2020-11-24 08:21
hello !

I cried victory too early!

I switched to Rasbian Desktop running in Virtual Box and started all over.

Now i get errors compiling Hercules itself:

 make  all-recursive
make[1]: Entering directory '/home/pi/sdl42/hyperion'
Making all in m4
make[2]: Entering directory '/home/pi/sdl42/hyperion/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pi/sdl42/hyperion/m4'
Making all in util
make[2]: Entering directory '/home/pi/sdl42/hyperion/util'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pi/sdl42/hyperion/util'
Making all in html
make[2]: Entering directory '/home/pi/sdl42/hyperion/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pi/sdl42/hyperion/html'
Making all in man
make[2]: Entering directory '/home/pi/sdl42/hyperion/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pi/sdl42/hyperion/man'
Making all in .
make[2]: Entering directory '/home/pi/sdl42/hyperion'
  CC       cckdcdsk.o
  CC       hsys.lo
  CCLD     libhercs.la
  CC       codepage.lo
  CC       hdl.lo
  CC       hexdumpe.lo
  CC       hostinfo.lo
  CC       hscutl.lo
  CC       hsocket.lo
  CC       hthreads.lo
hthreads.c: In function 'hthread_obtain_lock':
hthreads.c:518:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     PTTRACE2( "lock after", plk, (void*) waitdur, obtain_loc, rc, &tv );
                                  ^
hthreads.c:72:21: note: in definition of macro 'PTTRACE2'
         _msg,_data1,_data2,_loc,_result,_tv);                         \
                     ^~~~~~
hthreads.c: In function 'hthread_obtain_rdlock':
hthreads.c:737:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     PTTRACE( "rdlock after", plk, (void*) waitdur, obtain_loc, rc );
                                   ^
hthreads.c:66:21: note: in definition of macro 'PTTRACE'
         _msg,_data1,_data2,_loc,_result,NULL);                        \
                     ^~~~~~
hthreads.c: In function 'hthread_obtain_wrlock':
hthreads.c:769:36: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     PTTRACE2( "wrlock after", plk, (void*) waitdur, obtain_loc, rc, &tv );
                                    ^
hthreads.c:72:21: note: in definition of macro 'PTTRACE2'
         _msg,_data1,_data2,_loc,_result,_tv);                         \
                     ^~~~~~
hthreads.c: In function 'lsortby_nam':
hthreads.c:1247:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return rc == 0 ? ((int)((S64)p1->il_addr - (S64)p2->il_addr)) : rc;
                             ^
hthreads.c:1247:48: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return rc == 0 ? ((int)((S64)p1->il_addr - (S64)p2->il_addr)) : rc;
                                                ^
In file included from msgenu.h:18,
                 from hercules.h:104,
                 from hthreads.c:19:
hthreads.c: In function 'locks_cmd':
printfmt.h:124:33: warning: format '%x' expects argument of type 'unsigned int *', but argument 3 has type 'TID *' {aka 'long unsigned int *'} [-Wformat=]
   #define SCN_TIDPAT            "%"PRIx32       // complete format spec
                                 ^~~
hthreads.c:1286:31: note: in expansion of macro 'SCN_TIDPAT'
     else if (sscanf( argv[1], SCN_TIDPAT "%c", &tid, &c ) != 1)
                               ^~~~~~~~~~
In file included from htypes.h:26,
                 from hstdinc.h:312,
                 from hthreads.c:14:
/usr/include/inttypes.h:120:19: note: format string is defined here
 # define PRIx32  "x"
In file included from msgenu.h:18,
                 from hercules.h:104,
                 from hthreads.c:19:
hthreads.c: In function 'threads_cmd':
printfmt.h:124:33: warning: format '%x' expects argument of type 'unsigned int *', but argument 3 has type 'TID *' {aka 'long unsigned int *'} [-Wformat=]
   #define SCN_TIDPAT            "%"PRIx32       // complete format spec
                                 ^~~
hthreads.c:1554:31: note: in expansion of macro 'SCN_TIDPAT'
     else if (sscanf( argv[1], SCN_TIDPAT "%c", &tid, &c ) != 1)
                               ^~~~~~~~~~
In file included from htypes.h:26,
                 from hstdinc.h:312,
                 from hthreads.c:14:
/usr/include/inttypes.h:120:19: note: format string is defined here
 # define PRIx32  "x"
  CC       logger.lo
  CC       logmsg.lo
  CC       memrchr.lo
  CC       parser.lo
  CC       pttrace.lo
  CC       version.lo
  CC       ltdl.lo
  CCLD     libhercu.la

*** Warning: Linking the shared library libhercu.la against the
*** static library /home/pi/extpkgs/lib/libcrypto64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library /home/pi/extpkgs/lib/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library /home/pi/extpkgs/lib/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library /home/pi/extpkgs/lib/libtelnet64.a is not portable!
/usr/bin/ld: i386:x86-64 architecture of input file `/home/pi/extpkgs/lib/libcrypto64.a(crypto_version.c.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/pi/extpkgs/lib/libdecNumber64.a(decnumber_version.c.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/pi/extpkgs/lib/libSoftFloat64.a(softfloat_version.c.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/pi/extpkgs/lib/libtelnet64.a(telnet_version.c.o)' is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2082: libhercu.la] Error 1
make[2]: Leaving directory '/home/pi/sdl42/hyperion'
make[1]: *** [Makefile:2489: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/sdl42/hyperion'
make: *** [Makefile:1829: all] Error 2

Indeed it is strange that Hercules tries to compile 32 bit when the VirtualBox runs on a host that is 64 bit Windows. 

Maybe a problem in Virtual Box processor settings?

Kind regards

Allard

**Comment by AllardKrings** [comment] 2020-11-24 11:29
I have to add that on the Raspbian Buster Desktop 

uname -m gives the result : x86-64

Kind regards

Allard

**Comment by AllardKrings** [comment] 2020-11-24 11:43
I am willing to test the new instalation script on Raspbian Buster Desktop aswell as Debian 10.6.

**Comment by wrljet** [comment] 2020-11-24 14:14
I will install a Raspbian Buster Desktop today and see what's up.

Bill

**Comment by AllardKrings** [comment] 2020-11-24 14:55
Great!

Raspbian Buster Desktop uname -m : X86-64
Raspbian Buster Desktop -v : 1 SMP Debian 4.19.152-1 (2020-10-18)

Thanks a lot, if I can contribute anything, welcome.

I am a great fan of SDL Hyperion Hercules

Allard

**Comment by wrljet** [comment] 2020-11-24 16:58
I have reproduced this issue, under VMware.  (I'm not a Virtual Box guy)

The basic problem is the Raspberry Pi Desktop for PC and Mac installed a 64-bit kernel
(thus the `uname -m` -> x86-64), but it installs all 32-bit userland programs.  Including
the GNU development tools.

This causes no end of trouble trying to build complex programs using the autoconf/automake
tools, because it sets most things based on the `uname -m`, which then doesn't match what
gcc/ld, etc. actually are internally configured for when they were built.

This one is a real ball-buster.  Not to be confused with Debian Buster. :-)
And a stupid way the Raspberry Pi Foundation has set up that image.

... developing...

Bill

**Comment by AllardKrings** [comment] 2020-11-24 19:54
Hi Bill,

and how about Debian 10.6, the one I started with inside a VirtualBox, that also was e dead-end street.

I am glad I introduced a ball-buster and not a RTFM issue;-)

I am still on the road of adventure , learning Linux, learning Hercules SDL Hyperion on Linux, writing my own zabbix agent within z/OS, using Python, Rexx, Java. Almost retired, but never bored !

Kind regards

Allard

**Comment by wrljet** [comment] 2020-11-24 20:54
I'm quite certain your Debian 10.6 will work with my (uncommitted) i686 changes.
I'll set it up can you can grab them and try out.

Bill

**Comment by wrljet** [comment] 2020-11-26 22:13
Status update...

My automatic prepare script and build scripts, are now tested 100% from a fresh Linux install through to a working SDL-Hercules-390 build on Debian 10.6 32-bit, and on Pi 4 Ubuntu Mate 20.10 64-bit (Issue #334 ).

In the tweaking and cleaning phase now.  Then I will rerun tests on the other VMs and Pi images I have set up for this.
The full suite of test systems now includes (all on VMware except as note):

- Debian 8.6 (32-bit)
- Debian 9 (32-bit)
- Debian 10.x (64-bit)
- Debian 10.6 (32-bit)
- Ubuntu 12.04 (32-bit)
- Ubuntu 18.04 (64-bit)
- Ubuntu 20.04 (64-bit (WSL2)
- Mint 20 (64-bit)
- Centos 7.8 (64-bit)
- Centos 8.2 (64-bit)
- OpenSUSE 15.1 (64-bit)

- Raspberry Pi 4B RPI OS (64-bit Beta)
- Raspberry Pi Ubuntu Mate 20.10 (64-bit)
- (some other Pi images I have to refresh my list)

I have discovered VMware supports this API exposed via the Open VM Tools and `vmrun.exe` on the Windows
host side, that allows you to start, stop, send commands, and copy files to and from VMs.  Trying to use this
to prepare a completely automatic test suite.  Although at present it's still being done by-hand.

Bill

**Comment by AllardKrings** [comment] 2020-11-27 12:38
Great Bill!

**Comment by wrljet** [comment] 2020-11-30 19:27
OK, Thanksgiving is over, the Christmas lights are up, etc.  Back on track here...

I put two scripts up on GitHub to try out on your 32-bit Debian.
This will also work with Raspberry Pi 64-bit Debian-based OSes (RPI OS, Ubuntu, etc).

The current state of the scripts will pull down and include the changes I have not yet pushed up to Fish.
(I will do that as soon as this works for you)

Comments on your experience are encouraged!
But if things act up and/or don't work as expected, it is easier to track down if we know the "first unusual event".

This stuff may be obtained with:

    `git clone https://github.com/wrljet/hercules-helper.git`

or, if you don't have git, or simply prefer:

    `wget https://github.com/wrljet/hercules-helper/archive/master.zip`

You may need to `chmod +x` the two Bash scripts.

The default README at the bottom of the GitHub repo page will display some instructions.
You should check that out before doing anything else.

    `https://github.com/wrljet/hercules-helper`

But basically, this is all you need to do:

```
$ cd ~
$ git clone https://github.com/wrljet/hercules-helper.git
$ chmod +x ~/hercules-helper/*.sh

$ ~/hercules-helper/hyperion-prepare.sh

$ mkdir herctest && cd herctest
$ ~/hercules-helper/hyperion-buildall.sh -verbose --prompts --install 2>&1 | tee ./hyperion-buildall.log
```

If packages need to be installed you may need to reply with your sudo password.

You will be prompted a number of times between the major steps, to give you a chance
to see the results of the last step, and to clue you into what will be happening next.

Hercules will be "installed" if you include the --install option as shown above, into `~/herctest/herc4x`
This will not update your environment variables and stuff like that.

Bill

**Comment by AllardKrings** [comment] 2020-12-03 13:44
Hi Bill,

Thanks a lot!

"normal" working week is nearly over.

I will try this out tomorrow!

Allard

**Comment by wrljet** [comment] 2020-12-08 22:25
Fish,

I have posted 5 pull requests for your consideration, to the four extpkgs and gists, called "Build mods i686".

I have tried to be as careful as possible and tested these on many systems.
Should be safe, and only affects the 32-bit systems.

Bill

**Comment by Fish-Git** [comment] 2020-12-08 23:41
> I have posted 5 pull requests for your consideration, to the four extpkgs and gists, called "Build mods i686".
> 
> I have tried to be as careful as possible and tested these on many systems. Should be safe, and only affects the 32-bit systems.

Merged! Thanks, Bill!

**Comment by AllardKrings** [comment] 2020-12-11 12:22
Hi Bill,
after a week delay I finally was able to test the script. It works fine!! Thanks a lot!

Kind regards

Allard

**Comment by Fish-Git** [comment] 2020-12-12 23:45
You (Allard) appear to be happy so I'm presuming this issue has now been resolve to your satisfaction and so am now closing it.

If for some reason your issue has _not_ been satisfactorily resolved however, then feel free to re-open this issue.

Thanks.

Enjoy your personal mainframe. &nbsp; `:)`

**Closed as completed by Fish-Git** 2020-12-12 23:45 UTC
Labels: BUG, L

**Comment by AllardKrings** [comment] 2020-12-13 11:50
yes, you can close the issue!

thanks for all the help
