### ISSUE TITLE
Fixed point divide exception on SDL hercules 4.3.9999.0 on openSUSE linux

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#327] opened 2020-10-25 16:03 UTC
Hercules version 4.3.9999.0-SDL-g1ba20b46-modified (4.3.9999.0) is unstable for me.  I've had various issues including the divide exception below.  I also can no longer ping the TCPIP home addresses and I've had JES2 checkpoint IO errors.  Version gf701161a is stable and has been running for over a week.  I'm running openSUSE 15.1 and the os is z/OS 2.4.  The only Hercules indication I get the fixed point divide below.  I can provide more documentation if requested.

BTW, is there any way to 'refresh' the  source once  Hercules has been built, so I can move it to another machine and build it there or git an older version of Hercules?

[divide exception 2.txt](https://github.com/SDL-Hercules-390/hyperion/files/5435207/divide.exception.2.txt)

**Comment by Fish-Git** [comment] 2020-10-25 23:25
> Hercules version 4.3.9999.0-SDL-g1ba20b46-modified (4.3.9999.0)

What did you modify? The "-modified" in the version string means you are not running virgin g1ba20b46 code. One or more files were modified. What does `git status` show? Since you mention OpenSUSE, I'm going to guess you did an `autogensh`. Am I right?

Because doing that would end up re-building your ./configure file which is unnecessary. The configure script provided in the repository should be good enough to use directly. That is to say, doing an `autogen` should _NOT_ be necessary. Just do your `./configure` and `make` like normal. There's no need to "autogen" anything. The autogen has already been done for you. As it stands, with the "-modified" token in your version string, we cannot know with any certainty that you are running pure g1ba20b46 or have made some unsanctioned private modifications. We don't support private builds of Hercules. We only support official builds of Hercules.

But like I said, I'm going to presume you are indeed running unmodified g1ba20b46 and the reason it says it's been modified is because you did an autogen. Please confirm whether my guess is true or not. Thanks.

Now... as far as your Divide Exception is concerned, what makes you think the problem is with Hercules? A divide exception is a divide exception. Hercules `DR` (Divide Register) instruction has been unmodified since forever. If Hercules is reporting a Divide Exception is occurring, then you should be able to trust that it is telling the truth. You should be able to trust that your guest is indeed doing an illegal divide.

Take a look at the logfile snippet you provided:

<pre>
HHC00801I Processor CP00: Fixed-point-divide exception code 0009 ilc 2                                                                         
HHC02324I CP00: PSW=0404200080000000 0000000001377574 INST=1DE1         DR    14,1                   divide_register                           
HHC02269I CP00: R0=0000000000000000 <b><i>R1=0000000000000000                                                                                        
</i></b>HHC02269I CP00: R2=0000000000FDA9E0 R3=0000000000000000                                                                                        
HHC02269I CP00: R4=0000000002770000 R5=3FD0A43800FDA9A0                                                                                        
HHC02269I CP00: R6=000000000270689C R7=00000000027700A0                                                                                        
HHC02269I CP00: R8=0000000001376F48 R9=0000000002948800                                                                                        
HHC02269I CP00: RA=0000000002738700 RB=000000000004A500                                                                                        
HHC02269I CP00: RC=0000000002738700 RD=0000000002948874                                                                                        
HHC02269I CP00: RE=0000000000000000 RF=00000000004A3B90                                                                                        
HHC02271I CP00: C0=00800002DF9CEE20 C1=000000003D72C007                                                                                        
HHC02271I CP00: C2=0000000024239740 C3=000000020000002D                                                                                        
HHC02271I CP00: C4=000000020000002D C5=000000003EE88B40                                                                                        
HHC02271I CP00: C6=00000000FE000000 C7=000000003D72C007                                                                                        
HHC02271I CP00: C8=0000000000020000 C9=0000000000000000                                                                                        
HHC02271I CP00: CA=0000000000000000 CB=0000000000000000                                                                                        
HHC02271I CP00: CC=000000000525217F CD=000000003D72C007                                                                                        
HHC02271I CP00: CE=00000000DF8BEE87 CF=00000000029200
</pre>

Register 1 is indeed zero, Dividing ANYTHING by zero is undefined, and will cause a Fixed-point-divide exception. Hercules is telling the truth: your guest is at fault, not Hercules.

Closing as User Error.

**Closed as completed by Fish-Git** 2020-10-25 23:25 UTC
Labels: User Error

**Comment by rgschmi** [comment] 2020-10-26 02:37
I used git to retrieve the build and I did do an autogen, as I always have.  There were no modifications to Hercules I'm aware of.  I did a 'make clean' of the Sept 13 git s suggested elsewhere.  Then I did the autogen, configure, make and make install and now have a stable system.  I did gits  on Oct 20 and Oct 24, and both had issues, so I went back the the Sept 13 git and it works fine.  

I was unaware the autogen is no longer required.  I will do antother git and skip the autogen.

Thanks.

**Comment by Fish-Git** [comment] 2020-10-26 06:01
> I used git to retrieve the build and I did do an autogen, as I always have. There were no modifications to Hercules I'm aware of.

If you do a `git status` after you do your `autogen.sh`, you will notice that it reports that the `configure` script along with several `.in` files have now been modified (since they are the files that `autogen` generates):

```bash
[fish@centos-64 hercules-0]$ git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   Makefile.in
#	modified:   config.h.in
#	modified:   configure
#	modified:   html/Makefile.in
#	modified:   m4/Makefile.in
#	modified:   man/Makefile.in
#	modified:   util/Makefile.in
```

As a result, the version string that gets built has the string "-modified" appended to it to let you know that one or more files have are not the same as what they were when the repository was cloned. It lets you know _something_ was modified. It lets you know that you did not build a pristine unmodified version of Hercules. You changed something.

> I was unaware the autogen is no longer required.

The SDL Hyperion repository now includes a pre-generated `configure` script (as well as pre-generated `.in` files) so that `autogen.sh` is no longer needed. That was a change that was made quite some time ago (I forget exactly when). I will try to remember to update the build instructions and Release Notes to mention this fact so that others like you don't accidentally trip over this fact. Sorry.

> I did a 'make clean' of the Sept 13 git as suggested elsewhere. [...] I did gits on Oct 20 and Oct 24, and both had issues, so I went back the the Sept 13 git and it works fine.

There was no commit that I can see that was made on Sept 13 of this year. There was a commit made on Sept. 4, followed by a commit on Sept. 24. I don't know where you got your suggestion from. (And besides that, how the heck do you clone a version of git from a specific date?! I admit to not being a git expert, but I was unaware such a thing was even possible!)

As far as you having unspecified "issues" with the [presumably] Oct 20 and Oct 24 versions if Hercules, you should have mentioned them to someone, either to the group in general or in a new GitHub Issue like you did with this [bogus] Fixed point divide exception issue, so one of us could look into the problem for you.

But you mentioned in your original report:

> I'm running openSUSE 15.1 and the os is z/OS 2.4.

and I personally know of at least 6 or more different people who are successfully running z/OS 2.4 with absolutely no problems whatsoever (other than a rare TXF bug we're still trying to isolate), let alone any type of Fixed point divide exception! (which as far as I know _**no one**_ running z/OS 2.4 has _ever_ experienced!).

The z/OS 2.4 you have must be bad. That's the only thing I an think of. Either that, or maybe the version of GCC you're using to build Hercules with has a bug. Or maybe OpenSUSE 15.1 has a bug. (tuntap perhaps?? I don't know!)

But the bottom line is, given the evidence, I am seriously doubting that Hercules is the cause of your problems.

**Comment by Fish-Git** [comment] 2020-10-26 12:09
> I will try to remember to update the build instructions and Release Notes to mention this fact so that others like you don't accidentally trip over this fact.

Done!
