### ISSUE TITLE
IPLing z/VM 6.3 on a powerpc64le system leads to a loop

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#228] opened 2019-07-19 16:32 UTC
Apparently `machdep.h` assumes PowerPC is Big Endian BE although it can be Little Endian (ppc64le).. So all the `cmpxchg` PPC assist are returning values in the wrong order.

**Comment by ivan-w** [comment] 2019-07-20 08:33
When disabling the PPC assists (by uising lwarx/ldarx, etc..) the loop goes away. (z/VM IPL breaks somewhere else but it may be something completely unrelated - I'll get to that once this one is fixed).
I believe we should do some of the following : 
- Try to use compiler built-ins instead of assembly (if available)
- Use CSWAPxx anyway (since it will be a no-op for Big Endian systems) - and for Little Endian systems, it's essentially free anyway on any modern system (it's basically a 0 cycle instruction as it gets merged in any load/store pipeline).
I will investigate the different possible solutions.

**Comment by Juergen-Git** [comment] 2019-07-20 09:53
The future of the Power architecture clearly is little endian. Power 8 and the current Power 9 support both, and Linux distros and applications are "in transition". It is only a question of time, when all Linux for Power distros, and probably the Power architecture itself, will be little endian _only_. So, it's wise to go after that now, particularly considering that LE will be the "normal" case and BE the exception. Thanks for bringing this up, Ivan!

**Comment by ivan-w** [comment] 2019-07-20 10:09
I don't see AIX (or IBM i PASE) running LE anytime soon though !

**Comment by Juergen-Git** [comment] 2019-07-20 11:39
Sure... but then they could provide a kludge through Power(K)VM -- depending on the importance of the remaining legacy, of course. I'm curious to see how they will handle this ;-)

However, in practice one will run Linux (LE) on Power nowadays. We have some 40 Power servers running in our datacenter, all under Linux, currently about half of them LE. The rest will go to LE in the course of the regular renewal cycle, so, basically, BE will be gone within the next three years.

**Comment by Fish-Git** [comment] 2021-03-29 19:10
Ivan, &nbsp; &nbsp;(@ivan-w)

Do you have a fix for this issue that can be committed? (so we can close this issue?)

Based on your comments you already _know_ what the problem is!

If no fix is forthcoming, then maybe this issue should be closed? Just asking!

**Comment by Fish-Git** [comment] 2021-08-02 19:02
No response. Closing.

**Closed by Fish-Git** 2021-08-02 19:02 UTC
Labels: BUG, QUESTION..., Waiting to close...
