### ISSUE TITLE
MISSING: HPF (Transport-Mode) I/O

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#165] opened 2018-12-25 16:38 UTC
z/VM 6.4 uses now some "advanced CCWs". Actually HPF I/O, which the real FICON channel can execute. z/VM uses it especially for paging. In z/VM there exists an IPL option that it uses the regular CCWs instead. Unfortunately this option cannot be set during installation and therefore the install process fails in the first run. 

In this configuration UA 6400 is the SYSRES. 

```
10:05:25 HCPERP500I DASD 6400 AN OPERATION WAS TERMINATED BECAUSE A
10:05:25 HCPERP500I COMMAND REJECT ERROR OCCURRED 0
10:05:25 HCPERP6300I SENSE DATA FORMAT = 00 MSG CODE = 01
10:05:25 HCPERP6301I CHANNEL COMMAND WORD COMMAND CODE = **N/A HPF**
10:05:25 HCPERP6302I SEEK ADDRESS = 000000000000
10:05:25 HCPERP6303I SENSE = 80000000 00FFFF01 00000000 00000000 00000000
10:05:25 HCPERP6303I 00000000 00000080 00000000
10:05:25 HCPERP6304I IRB = 00C24017 074D8008 0E000000 00800000
10:05:25 HCPERP6305I USERID = SYSTEM
10:05:25 HCPERP2216I CHANNEL PATH ID = 64
10:05:25 HCPUDS1777E The directory on volume V641RS could not be initialized.
10:05:25 HCPUDS1752E No directory could be initialized.
10:05:25 HCPERP500I DASD 6400 AN OPERATION WAS TERMINATED BECAUSE A
10:05:25 HCPERP500I COMMAND REJECT ERROR OCCURRED
10:05:25 HCPERP6300I SENSE DATA FORMAT = 00 MSG CODE = 01
10:05:25 HCPERP6301I CHANNEL COMMAND WORD COMMAND CODE = **N/A HPF**
10:05:25 HCPERP6302I SEEK ADDRESS = 000000000000
10:05:25 HCPERP6303I SENSE = 80000000 00FFFF01 00000000 00000000 00000000
10:05:25 HCPERP6303I 00000000 00000080 00000000
10:05:49 HCPWRP959I PHOENIX SYSTEM TERMINATION IN PROGRESS ON 2018-12-25
HCPGIR450W CP entered; disabled wait PSW 00020000 00000000 00000000 00000902
```

This can be circumvented with following:

IPL z/VM 6.4 with LOADPARM UA of an active 3270 emulation. The Stand Alone LOADER - panel is shown. There in the IPL-Parameter field you have to enter PAGING63 as additional parameter. Then the IPL succeeds. For permanent keeping this option a new SA-Loader has to be written to the IPL volume where PAGING63 is included. 

Here is the CCW Trace during IPL:

* [zvm640.startup.zip](https://github.com/SDL-Hercules-390/hyperion/files/2708903/zvm640.startup.zip)

**Comment by Fish-Git** [comment] 2018-12-26 03:08
I've only spent a brief few _minutes_ researching this and I _believe_ what we need add to Hercules is channel support for:

* Device Control Words (DCW)
* Transport Indirect Data Address Words (TIDAW)
* Transport Control Word (TCW)
* Transport Status Block (TSB)
* Transport Command & Control Block (TCCB)

which we don't have yet and which would take a _considerable_ amount of long term effort to provide. This definitely _not_ something that can be done quickly. The changes involved are not trivial.

The good news is this is all documented in chapter 15 of the Principles of Operation manual so it's not an unknown. But it's defintely a long term project.

**Comment by fbi-ranger** [comment] 2018-12-26 06:12
Indeed, this is a long term issue, but in order to stay compatible with new OS versions, it will be needed. 
z/LINUX can use it as well.

**Comment by fbi-ranger** [comment] 2020-04-21 05:13
According to the latest announcements of z/VM 7.2 
the PAGING63 parameter and its functionality will be removed:

https://www-01.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_ca/8/897/ENUS220-088/index.html&request_locale=en

"The PAGING63 IPL parameter and associated external interfaces have been removed. z/VM paging subsystem improvements include support for High Performance FICON®, HyperPAV, encryption, and EAV, which are not available when the PAGING63 IPL parameter is specified.
This will satisfy the statement of direction from Hardware Announcement 119-027, dated September 12, 2019."

Probably it might not be possible to IPL z/VM 7.2 under Hercules as HPF I/O will not be implemented.

**Comment by arfineman** [comment] 2020-05-06 05:07
The traces show this is Command Mode I/O and not Transport Mode (ORB bit 13 is off). The channel program is simply using Prefix CCW.

**Comment by fbi-ranger** [comment] 2020-05-07 04:14
And ideas what goes wrong in this I/O?

**Comment by arfineman** [comment] 2020-05-07 17:25
It obviously ended with CE+DE+UC and sense of Command Reject, format 01, indicating it was rejected by Hercules, as it did not recognize the command. I doubt very much that the PFX command parameters are correctly displayed, because they don't make sense. Unlikely CP would issue such a command with bogus parameters.  
Does Hercules support the PFX(E7) command ? If the answer is no, then the error is explained.
If the answer is yes, but it rejected this particular command, then I can tell what the issue is if the correct parameters are displayed. 
I would recommend IPL'ing this SYSRES on a second level system that Hercules supports. Then get a CP I/O trace of that SYSRES. I can guarantee it will provide more reliable trace data.

**Comment by Fish-Git** [comment] 2020-05-07 20:03
> Does Hercules support the PFX (E7) command?

It's _supposed_ to:

&nbsp; &nbsp; &nbsp; **Revision: [4a8ad33dba76221d0e9fa56595d85aa7c13ef29b](https://github.com/SDL-Hercules-390/hyperion/commit/4a8ad33dba76221d0e9fa56595d85aa7c13ef29b
)**
&nbsp; &nbsp; &nbsp; **Date: 12/28/2018 8:31:39 PM**
&nbsp; &nbsp; &nbsp; **Message: Fix CKD suffixed Read Count bug**

&nbsp;
_**BUT...**_

Given that it's an _**[undocumented CCW](https://groups.google.com/forum/#!topic/bit.listserv.ibm-main/2Au3rRIkBAo)**_, we can't be sure whether it's correct or not. From the sounds of it, it's not. &nbsp; `:(`

> If the answer is yes, but it rejected this particular command, then I can tell what the issue is if the correct parameters are displayed.

_**Please!**_

> I would recommend IPL'ing this SYSRES on a second level system that Hercules supports. Then get a CP I/O trace of that SYSRES. I can guarantee it will provide more reliable trace data.

Florian? Can you provide that for "arfineman"? (*)

Thanks!
___
(*) What the heck is your real name?! &nbsp; `:-(`

(Or don't you want people to know?)

**Comment by arfineman** [comment] 2020-05-08 01:44
I did look at fix "4a8ad33dba76221d0e9fa56595d85aa7c13ef29b". There is nowhere in that code a sense of format_0 message_1 (Invalid Command) is generated. The command is being rejected somewhere else.

**Comment by Fish-Git** [comment] 2020-05-08 04:49
> I did look at fix "4a8ad33dba76221d0e9fa56595d85aa7c13ef29b". There is nowhere in that code a sense of format_0 message_1 (Invalid Command) is generated. The command is being rejected somewhere else.

Quite likely, yes. However, since we don't know what the actual CCW was _(VM reports it as "\*\*N/A HPF\*\*")_:

<pre>
10:05:25 HCPERP500I COMMAND REJECT ERROR OCCURRED 0
10:05:25 HCPERP6300I SENSE DATA FORMAT = 00 MSG CODE = 01
10:05:25 HCPERP6301I CHANNEL COMMAND WORD COMMAND CODE = <b>**N/A HPF**</b>
</pre>

we can't know if it was some type of data-chained non-read command, which _would_ cause a format-0 message-1 Command Reject:

```C
    /* Command reject if data chaining and command is not READ */
    if ((flags & CCW_FLAGS_CD) && code != 0x02 && code != 0x5E
        && (code & 0x7F) != 0x1E && (code & 0x7F) != 0x1A
        && (code & 0x7F) != 0x16 && (code & 0x7F) != 0x12
        && (code & 0x7F) != 0x0E && (code & 0x7F) != 0x06)
    {
        // "%1d:%04X CKD file %s: data chaining not supported for CCW %02X"
        WRMSG( HHC00422, "E", LCSS_DEVNUM, dev->filename, code );
        ckd_build_sense (dev, SENSE_CR, 0, 0,
                        FORMAT_0, MESSAGE_1);
        *unitstat = CSW_CE | CSW_DE | CSW_UC;
        return;
    }
```

Florian? When the problem occurs, do you also see a Hercules `HHC00422E` error message anywhere too?

Now I admit to knowing _**very** little_ (almost nothing as a matter of fact!) about Prefix CCWs (E7) and HPF and Hercules's dasd support or all the rest of this stuff, BUT...

Could it maybe be that for whatever reason it is z/VM itself that is rejecting the CCW? Maybe z/OS is, for whatever reason, _presuming_ the device supports **[RCS (Record Cache Subsystem)](https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.15/gtpm2/m2chdasdccw.html)** -- (perhaps because it presumes all dasd devices support it since all REAL 3390s today _should_) -- and is issuing an I/O with an E7 Prefix CCW in it and z/VM is rejecting it because it knows the device doesn't support it? (because there's no support in Hercules to report whether or not its dasds support **[RCS](https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.15/gtpm2/m2chdasdccw.html)** or not since that's likely undocumented?)

Just wild-ass guessing here! Please take everything I say on this subject with a _HEAVY_ dose of salt!

**Comment by arfineman** [comment] 2020-05-08 05:51
We know what the CCW is. Florian posted the trace in a zip file when the issue was opened. 
CP's I/O does not go thru translation and any results are what the hardware reflected.
It is very likely the above code is where the test failed and the command reject was generated.
The E7 CCW below from the test has IDA bit on. It is very unusual a control CCW have this bit on. 
It is mostly used for read/write CCWs to avoid obtaining large contagious blocks. 
I think this is what caused Hercules to display junk data for the failing CCW.
  
16:05:25 HHC01334I 0:6400 CHAN: ORB: IntP:00E4E428 Key:0 LPM:80 Flags:0C200 ....FP....H. ........ CCW:7FFAA7A8
16:05:25 HHC01315I 0:6400 CHAN: ccw E7440040 7FF9EF30=>00000001 F6820F50 FFFFFFFF FFFFFFFF ....6b.&........
16:05:25 HHC01312I 0:6400 CHAN: stat 0E00, count 0000
16:05:25 HHC01313I 0:6400 CHAN: sense 80000000 00FFFF01 00000000 00000000 00000000 00000000 00000080 00000000
16:05:25 HHC01314I 0:6400 CHAN: sense CMDREJ 
16:05:25 HHC00424I 0:6400 CKD file /local/sys1/s390/mdasd/V641RS.6400: read trk -1 cur trk -1
16:05:25 HHC01317I 0:6400 CHAN: scsw 00C24017, stat 0E00, count 0000, ccw 7FFAA7B0

**Comment by Fish-Git** [comment] 2020-05-08 09:00
> We know what the CCW is. Florian posted the trace in a zip file when the issue was opened.

_(Doh!)_ Sorry. Completely missed that. I must be getting old. I'm slipping up.

> The E7 CCW below from the test has IDA bit on. It is very unusual a control CCW have this bit on.
> It is mostly used for read/write CCWs to avoid obtaining large _**contagious**_ blocks.

Maybe it was just trying to avoid getting COVID-19! &nbsp; `;-)`

(I'm suspecting you probably meant to say "contiguous"?)

> I think this is what caused Hercules to display junk data for the failing CCW parameters.

"Junk data"? What junk data? If you're referring to what's displayed for message `HHC01315I`:
```
    HHC01315I 0:6400 CHAN: ccw E7440040 7FF9EF30=>00000001 F6820F50 FFFFFFFF...
```
That's just showing you the first IDAW in the IDAL that the CCW is pointing to. Because the IDA bit was specified in the CCW, the CCW's actual data is actually located at real address 1F6820F50. Hercules's CCW tracing logic does not have any logic that processes (dereferences) Indirect Data Address Words/Lists. It just shows you exactly what the address field in the CCW points to (16 bytes of it), which in this case is the first (in this case, _only!_) IDAW in the IDAL. So it's hardly "junk data".

Is it, in this case, helpful? Probably not. In most cases the person doing the trace more than likely wants to see the actual data, i.e. what the IDAW is pointing to, and not the IDAW itself. I agree with that. Feel free to create a new GitHub Issue for that and when someone has the time we might eventually get that fixed (or provide an I/O trace option to enabled such behavior).

But it's _not_ "junk data". &nbsp; `:)`

**Comment by fbi-ranger** [comment] 2020-05-08 12:55
Dear colleagues, 
I was in the stage of prepared for the requested traces. 

The Hercules SDL version I use is  4.3.9999.0-SDL-ga73daadd-modified (4.3.9999.0)

The system is a zVM 6.4 at Service Level 1901. I have tried to IPL a copy of the system natively on Hercules. On the SA-Loader Screen I removed the PAGING63 option and the system came up **without** any problem. 
This is shown in the attached CCW trace of the volumes 6410 (SYSRES), 6412 (PARMDISK), 6414 (Paging device). 

It seems that either a higher service level of z/VM or, even more likely, the functionality of Hercules improved that much over the years, that the issue does not happen any more. 

Well, the reported level of z/VM of this issue was the installer system of z/VM, a level without any RSU or other fixes or patches applied. This condition I could not test yet, meaning a second level install of a z/VM 6.4 

[zvm-hpf.gz](https://github.com/SDL-Hercules-390/hyperion/files/4598932/zvm-hpf.gz)

**Comment by arfineman** [comment] 2020-05-08 13:16
My bad. Fish is correct. If you throw away the 8 bytes of FFs for the command parameter the data is not junk. 
I looked at the traces Florian just posted and it does show the E7 command with the correct parameters that is being successfully executed. 
The only difference is IDA bit if off. There is no need for the second level test because the new traces show the actual parameters.   
Conclusion: Hercules does support PFX CCW, but not when IDA bit is on.

**Comment by Fish-Git** [comment] 2020-05-08 21:30
arfineman wrote:

> Conclusion: Hercules does support PFX CCW, but not when IDA bit is on.

I'm not sure I agree with that.

Hercules's handling of CCWs with the IDA flag being on is handled identically across the board, regardless of what CCW opcode is being processed. If there was a bug in Hercules's IDA handling, I'm sure we would have noticed it long before now!

I personally feel it would be a waste of time because I'm 99.999%+ sure that Hercules's IDA flag handling is correct, _regardless_ of what CCW opcode is being processed, _BUT..._

You could easily(?) verify who's claim was right and who's was wrong by means of a simply stand-alone test that issues I/O to a device using the E7 PFX CCW both with and without the IDA flag being on. They should both work fine.

**Comment by Fish-Git** [comment] 2020-05-08 21:35
Florian wrote:

> I have tried to IPL a copy of the system natively on Hercules. On the SA-Loader Screen I removed the PAGING63 option and the system came up this time **without** any problem!

Fantastic! That's _great_ new, Florian! Thank you.

> This is shown in the attached CCW trace of the volumes 6410 (SYSRES), 6412 (PARMDISK), 6414 (Paging device).

Yep! Just took a peek at it and you're right: all of the E7 (PFX) CCWs completed successfully.

> It seems that either a higher service level of z/VM or, even more likely, the functionality of Hercules improved that much over the years, that the issue does not happen any more.

Whatever the cause, the only important thing is the originally reported problem no longer exists (no longer occurs) with current Hercules, so we can now close this issue and mark it as being resolved.

Thank you Florian and thank you arfineman both for your comments.

**Closed by Fish-Git** 2020-05-08 21:35 UTC
Labels: Enhancement, HELP!, Missing

**Comment by arfineman** [comment] 2020-05-09 19:11
Fish is correct again. I did a standalone test with no IDA, 2K IDA and 4K IDA and they all worked.
More interesting, in traces when IDA is used, the corresponding data associated with that IDAW is also displayed. Good work.
CHAN: idaw 00005C00, len 040: =>01800000 00000000 00000000 40C01000 ............
CHAN: idaw 0000000000005C00, len 0040: =>01800000 00000000 00000000 40C01000 ............

**Comment by Peter-J-Jansen** [comment] 2020-05-10 08:41
In October 2016 a person “Aaron Finerman” reported a problem related to (then not yet SDL-) Hyperion Hercules DASD reserve/release.  The last e-mail on the topic was this :

 

Aaron Finerman wrote: 

> The following command should be allowed to go through, 
> even when the device is reserved: Reset Allegiance x'44', 
> Sense Path Group ID x'34', Set Path Group ID x'AF' and 
> Unconditional Reserve x'14'. 

Please create a new GitHub Issue (problem report) for this, with as much detail as possible: 

    <https://github.com/hercules-390/hyperion/issues> https://github.com/hercules-390/hyperion/issues


We can't promise when any of us will be able to "get a round tuit", but at least with it being in our list of open issues we won't forget about it. 

Thanks. 

-- 
"Fish" (David B. Trout) 
Software Development Laboratories 
 <http://www.softdevlabs.com/> http://www.softdevlabs.com

 

Fish confirmed that this was not followed up on. As I am currently encountering reserve/release problems I would like to contact this person. Could it possibly be that “arfineman” is that same person please ? if so, please feel free to contact me, or to open the issue on SDL-Hyperion directly if appropriate.

 

Thanks,

 

Peter J. Jansen

**Comment by arfineman** [comment] 2020-05-10 20:17
Issue 300 opened.
