### ISSUE TITLE
Printer Error on Hercules Console

### ISSUE THREAD

**Issue by magnum41br** [SDL-Hercules-390/hyperion#238] opened 2019-08-15 22:07 UTC
Gentlemen, I am running Hercules version **4.0.0.8904-SDL-g6359717a (4.0.0.8904)** under Windows 10 64bit.

I am trying to use the `cctape` parameter in my existing 1403 printer (00E),

After loading Hercules with the new configuration, I receive the message `HHC01111W 0:000E Printer: channel 1 is undefined` in the Hercules console.

I could not find the message in the Hercules Messages and Codes manual.

Thanks in advance.

-Nelson

The printer entry in the configuration file is `000E 1403 127.0.0.1:1403 sockdev cctape=(1=1,7=2,13=3,19=4,25=5,31=6,37=7,43=8,63=9,49=10)`.

My configuration file looks like this:

```
#
#   ===========================
#   HERCULES Configuration file
#   VM/ESA 2.4 AD distribution
#   ===========================
#
# Description:       VMESAIB
# MaxShutdownSecs:   15
# LoadUnit:          0123
# RCFile:            
# LogoFile:          
# IgnoreParseErrors: 0
# HercGUI Version:   1.12.6.3249
#


---------------------------------------------------------
#   CPU Configuration
#---------------------------------------------------------


 ARCHMODE  ESA/390
  CPUMODEL  2090
  CPUSERIAL 071030
  MAINSIZE  512
  MAXCPU    4
  ENGINES   CP,CP,CP,CP
  NUMCPU    4


---------------------------------------------------------
#   OS Tailoring
#---------------------------------------------------------


 LOADPARM  ........
  OSTAILOR  QUIET
  TZOFFSET  +0200
  PGMPRDOS  RESTRICTED


---------------------------------------------------------
#   Hercules Service Processor/Application Window
#---------------------------------------------------------


 PANRATE   FAST
  PANTITLE  "Hercules - VM/ESA Version 2, Release 4"


---------------------------------------------------------
#   Integrated Hercules I/O Controller
#---------------------------------------------------------


 CNSLPORT  3270
  HTTP PORT  8081 NOAUTH
  HTTP ROOT C:/VM370IB/Html/
  HTTP START
  DIAG8CMD  ENABLE ECHO
# parametro abaixo ON para Hercules 4,  e OFF para Hercules 3
  LEGACYSENSEID  ON


---------------------------------------------------------
#   Unit record devices
#---------------------------------------------------------
  
  000C 3505 127.0.0.1:3505 sockdev ascii trunc eof
  010C 3505 127.0.0.1:3506 sockdev ascii trunc eof
  000D 3525 C:/VM370IB/Ftp/Punches/VMESApunch.txt ascii crlf
  010D 3525 C:/VM370IB/Ftp/Punches/VSEESApunch.txt ascii crlf
  000E 1403 127.0.0.1:1403 sockdev cctape=(1=1,7=2,13=3,19=4,25=5,31=6,37=7,43=8,63=9,49=10)
  000F 1403 127.0.0.1:1404 sockdev 


---------------------------------------------------------
#   3270 Display terminals
#---------------------------------------------------------
  
  # VM/ESA Operator console
  001F 3270
  
  # 3270 Terminals
  0200.8 3270


 # 3287 Printers
  02A0 3287 CICS
  02A1 3287 VTAM


---------------------------------------------------------
#   Direct-access storage devices
#---------------------------------------------------------
  0123 3390 C:/VMESAIB/Disks/240RES.3390-3.CCKD
  0124 3390 C:/VMESAIB/Disks/240W01.3390-3.CCKD
  0125 3390 C:/VMESAIB/Disks/240W02.3390-3.CCKD
  0126 3390 C:/VMESAIB/Disks/240W03.3390-3.CCKD
  0128 3390 C:/VMESAIB/Disks/240SPL.3390-1.CCKD
  0340 3390 C:/VMESAIB/Disks/DOSRES.3390-2.CCKD
  0341 3390 C:/VMESAIB/Disks/SYSWK1.3390-2.CCKD
  0342 3390 C:/VMESAIB/Disks/SYSWK2.3390-2.CCKD
  0343 3390 C:/VMESAIB/Disks/SYSWK3.3390-2.CCKD


---------------------------------------------------------
#   Tapes
#---------------------------------------------------------


 0580 3480 *
  0581 3480 *
  0590 3480 *
  0591 3480 *


---------------------------------------------------------
#   CTC Adapters
#---------------------------------------------------------


 044A-044B    LCS     192.168.1.1
```

&nbsp;
______________________________________
_**Fish then responded with:**_

> Nelson,
> 
> I apologize for the bogus warning message.  It's quite obvious you _did_ define a channel-1 punch on your carriage-control tape.
> 
> The bug was a fairly minor mostly cosmetic bug in Hercules's `cctape` handling, which has now been fixed in the next release of SDL Hyperion (i.e. version 4.3, still in development(*)).
> 
> Thank you for reporting it.
> 
> (*) https://sdl-hercules-390.github.io/html/hercnew.html

&nbsp;
___________________________________________________________
_**At his point in the conversation, I then responded with:**_

Fish, thanks for the quick response. Well I will continue to investigate. The real problem is that I am creating a report for a 49-line form by using CMS EXEC2, and in a certain point I issue a `EXECIO 1 PRINTER ( CC 1` command line that is not producing the jump to channel 1 (jump to next page).

Regards!
-Nelson

**Comment by Fish-Git** [comment] 2019-08-16 19:09
I would very much like to see a CCW trace of your printer device 00E for the EXECIO command:

1. From hercules, enter the command `t+00e`
2. From VM, issue your EXECIO command
3. Turn off CCW tracing: `t-00e`

Then post the resulting portion of the Hercules logfile.

I highly suspect the EXECIO command you are using is issuing the "Skip to Channel 1 Immediate" CCW opcode (X'8B'), which, according to the manual, _will **NOT** skip_ -- if you're already positioned at Channel 1:


From: [GA24-3073-08 1403 Printer Component Description](http://ibm-1401.info/IBM-1403_Manual_A24-3073.pdf), page 12:

> When the paper moves in the carriage for repetitive
> skipping  (using the same channel in the control tape),
> each skipping operation should be preceded by a command
> such as WRITE AND SKIP TO CHANNEL X or initiate a spacing 
> operation and then a SKIP TO CHANNEL X. If this is not 
> done, overprinting occurs as the carriage recognizes
> that it is at channel X or at the defined line count
> and does not move the carriage.

Hercules's printer logic honors this:

https://github.com/SDL-Hercules-390/hyperion/blob/2ccc4a5e66b92b54c1abb8dab7d8c228e1ca416c/printer.c#L418-L440

&nbsp;
**I suspect it's a bug in your EXEC2 script, _not_ Hercules.**
&nbsp;

**Comment by Fish-Git** [comment] 2019-08-16 19:23
At this point in the conversation, Nelson responded with the following attachment:

* [Hercules Logfile.056.txt](https://github.com/SDL-Hercules-390/hyperion/files/3507333/Hercules.Logfile.056.txt)

Which anyone can see does _**not**_ show any type of CCW trace being done (i.e. `t+00e`) -- which is what I _specifically requested_ in my previous reply -- rendering it pretty much completely worthless as far as resolving this issue is concerned.

Until Nelson can follow my instructions and provide clear, convincing evidence that Hercules is broken _(and not his EXEC2 script which in my opinion is much more likely IMO!),_ I am going to close this as "Invalid" (i.e. User error).

___
@magnum41br 

Nelson?

You can re-open this GitHub Issue if you _need_ to, but _please,_ _**ONLY**_ do so if your attached CCW trace shows that a "Skip to Channel 1 Immediate" is _not_ being done by your script.

Because if it shows that your script _is_ doing a "Skip to Channel 1 Immediate", _**then the problem is in your script, NOT Hercules.**_

**Closed by Fish-Git** 2019-08-16 19:23 UTC
