### ISSUE TITLE
rubato_thread ate my computer!

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#370] opened 2021-02-24 09:59 UTC
My computer has an Intel i3 2-cpu (i.e. 4 thread) processor running Fedora 33 x86_64. In the old days, before TXF support, I used to be able to run half a dozen instances of Hercules all doing useful work, albeit slowly. Today, the fourth instance of Hercules, without even IPL'ing the guests, renders my computer into doorstop mode, because the rubato_threads are using all of all of the cpu threads.

The following is a **top** display of the Hercules threads of an instance of Hercules before IPL'ing the guest.
 
![image](https://user-images.githubusercontent.com/1387091/108982639-4df0ea80-768e-11eb-85f9-96789979821d.png)

Does rubato_thread need to run so often?

**Comment by Fish-Git** [comment] 2021-02-24 19:44
Wow. That certainly seems excessive! `:(`

A couple of observations:

1. Hercules currently imposes a [default `TIMERINT` value of 50 microseconds as well as a _minimum_ `TIMERINT` value of only 1 microsecond](https://sdl-hercules-390.github.io/html/hercconf.html#TIMERINT). (Refer to the `MIN_TOD_UPDATE_USECS`, `DEF_TOD_UPDATE_USECS` and `MAX_TOD_UPDATE_USECS` constants as \#defined in header `featall.h`).
&nbsp;
The minimum value of 1 microsecond however is very likely too small and should probably be increased. What the new minimum value should be however, I don't know. My own choice would be 50, the same as our current default value. I say this because of the following warning which exists in the Hercules documentation regarding `TIMERINT`:
&nbsp;
_**Caution:**  While a lower TIMERINT value may help increase the accuracy of your guest's TOD Clock and CPU Timer values, it could also have a severe negative impact on the overall performance of your host operating system depending on the priority (or 'nice' value) of the Hercules process itself._
&nbsp;
Which is very likely what you are currently experiencing. That is to say, the rubato_thread is probably dynamically adjusting Hercules's `sysblk.timerint` value down to our currently defined minimum value of 1 microsecond, which is very likely too low and likely the cause of your performance issue.

2. The rubato_thread was created exclusively to help performance of memory transactions (i.e. TXF), so if TXF (facility 73) is not enabled, then _technically_ it does not need to be running. Looking at the code however, I can now see that we appear to _always_ be starting it, which seems wrong.

So it appears there are two different (but related) bugs that are causing your problem, both of which need to be fixed:

1. The rubato_thread should _not_ be started unless Facility 73 is enabled (and of course the converse as well: if/when Facility 73 is ever _disabled_, the rubato_thread should be terminated. That is to say, the rubtao_thread should _never_ be running if Facility 73 is not enabled and only started whenever Facility 73 is enabled).

2. Our current minimum `TIMERINT` value should be increased to be greater than what it is today. My suggestion would be to define the new minimum value as being the same as our currently implemented default value of 50 microseconds, as I personally do not see the value/utility/sanity of using any smaller of a value given the known likelihood of severe negative impact to host system performance whenever a smaller value is used.

Does this seem reasonable to everyone?

**Comment by wrljet** [comment] 2021-02-24 22:47
Seems reasonable to me.  Certainly part (1).

**Comment by Fish-Git** [comment] 2021-02-25 03:43
Ian  &nbsp;(@mcisho),

Here's the patch I propose committing to fix your problem:

* [github-issue-370.patch.txt](https://github.com/SDL-Hercules-390/hyperion/files/6040362/github-issue-370.patch.txt)

Please apply it and let me know whether or not it resolves your problem. If it does and no one objects, I will go ahead and commit it.

Thanks.

**Comment by mcisho** [comment] 2021-02-25 10:52
Your fix has made a big difference.

With TXF explicitly disabled the following is a **top** display of the Hercules threads just before IPL'ing the guest.

![image](https://user-images.githubusercontent.com/1387091/109141130-acd16500-775d-11eb-951c-2ebced58a5b6.png)

With TXF explicitly enabled the following is a **top** display of the Hercules threads just before IPL'ing the same guest.

![image](https://user-images.githubusercontent.com/1387091/109142342-100fc700-775f-11eb-8b51-bf109a49f0ae.png)

The following messages appeared on the panel, which I don't recall ever seeing before, but that doesn't mean they weren't produced before!
HHC17736W TXF: TIMERINT 50 is too small; using default of 400 instead
HHC00007I Previous message from function 'txf_set_timerint' at transact.c(2537)

rubato_thread is still using quite a lot of cpu, which for guest that doesn't use TXF seems unnecessary. Perhaps rubato_thread should make it's interval time much larger if the TXF rate is repeatedly zero?

**Comment by Fish-Git** [comment] 2021-02-25 15:42
> rubato_thread is still using quite a lot of cpu, which for a guest that doesn't use TXF seems unnecessary. Perhaps rubato_thread should make it's interval time much larger if the TXF rate is repeatedly zero?

TXF should be disabled for guests which are never going to use it, thereby causing the rubtao_thread to never get started in the first place.

TXF should be enabled for guests which do or _might_ use it, requiring the rubato_thread to get started so that it can react quickly to sudden increases in the transaction rate. Thus, when it is running, it's important for its interval to remain low (small/short) enough to be able to react quickly to transaction "floods", but not so low as to introduce too much of a performance impact on the host. Thus the reason for imposing a slightly larger lower limit to the minimum `TIMERINT` value allowed (which is what warning message `HHC17736W` is informing you of).

That is to say, during periods of low transaction rate (i.e. zero or one per second for example), it's important for both the rubato_thread's as well as the timer_thread's interval to be as small as possible in order to ensure accurate TOD clock values as well as to ensure a quick reaction to any sudden unexpected increase in the transaction rate that might suddenly occur (i.e. in order to be able to quickly react to the _start_ of a transaction flood).

When a transaction flood begins, the rubato_thread must _quickly increase_ the interval for both the timer_thread as well as the rubato_thread in order to not only reduce the occurrences of transaction failures due to timer interrupts (which would only compound the problem by allowing the flood to continue for much longer than otherwise due to the increased likelihood of transactions failing and therefore having to be retried thereby prolonging the flood (thus the reason increasing the timer_thread's interval)), but _also_ to reduce the overhead of host system timer interrupts too (thereby _reducing_ the impact to the host system's performance (thus the reason increasing the rubato_thread's interval)).

So during periods of low transaction rates, the interval is short (but not _too_ short!), and much _longer_ during periods of high transaction rate (to reduce overhead to a minimum and to provide transaction "assitance" for as long as needed but not _too_ long).

Make sense?

**Comment by Fish-Git** [comment] 2021-02-26 00:08
Fixed by commit 2cb0921980588b5c0ab86107a73be9463b376525.

Closing.

**Closed as completed by Fish-Git** 2021-02-26 00:08 UTC
Labels: BUG
