### ISSUE TITLE
MIPS indicator not updating, but system is running

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#129] opened 2018-08-19 11:10 UTC
I compiled latest version (with -O3). 

Sometimes (not reproducible at will), when I IPL an operating system, the MIPS indicator stays at zero, but the total instructions executed updates as normal and the registers change also normally. 

I have a video of this behavior (screen shot alone doesn't show the behavior properly) which I can send by email on demand. (EDIT: see below)

Thanks.
___
* [Video (1).zip](https://github.com/SDL-Hercules-390/hyperion/files/2300987/Video.1.zip)

**Comment by Fish-Git** [comment] 2018-08-19 16:12
> I have a video of this behavior (screen shot alone doesn't show the behavior properly) which I can send by email on demand.

Please. My email address is on my "Contact" web page: http://www.softdevlabs.com/about.html

**Comment by moshix** [comment] 2018-08-19 16:16
Done. Just sent you an email with subject "MIPS Indicator no updating"

thanks a lot

**Comment by Fish-Git** [comment] 2018-08-19 16:17
This is Linux I presume?

> ... and the registers change also normally.

Does the problem occur on _both_ displays? (i.e. the main panel display _and_ the 'esc' alternate panel display) Or does the problem only occur on one of the displays?

**Comment by Fish-Git** [comment] 2018-08-19 16:58
> Oops the video says it's too large to send to your email.... I will put it on dropbox and send you a link by email.

That's fine. Thanks.

You could also upload it to my FTP site's "incoming" folder too:

* ftp://www.softdevlabs.com
* ftp://www.softdevlabs.com/incoming/

Be aware however it's a _**write-only**_ folder, so you will only be able to _upload_ data to it, but not download any data (nor even list its contents).

**Comment by Fish-Git** [comment] 2018-08-20 04:00
Another question: what MIPS rate does your guest report?

And yet _another_ question: does the same behavior occur with _other_ Hyperions? (or with e.g. Hercules 3.13?)

**Comment by moshix** [comment] 2018-08-20 09:34
Yes, the problem also occurs when I make the screen wider to show the full length of the app. 

the guest reports moderate MIPS (of course it's not trivial to correlate the two measures, ie inside and outside ), but z/VM shows maybe 15-20 MIPS. 

I want to highlight that this problem only manifests (so far) with the following conditions:
1. z/VM 6.2 or 6.3 (z/VM 5.3 is fine)
2. more than 2 CPs

So, this seems a race condition to me, somewhere.

**Comment by Fish-Git** [comment] 2018-08-21 04:02
> So this seems to me to be a race condition somewhere.

I'm not so sure yet. It sure _seems_ like a race condition, I'll grant you that. _But..._

...the fact that it only occurs with certain z/VM guests would seem to contradict this. I mean, I _personally_ have not yet been able to reproduce it, no matter how hard I try. (Of course, with _race_ conditions that's the usual situation! It works on most systems but not other faster/slower systems.)

Regardless, looking over the logic in `panel.c` I do see some weirdness going on that might be one or more bugs.(*)

Please apply the following patch to your Hercules, rebuild, retest and report back with your results. Thanks!

* [#mips.patch.txt](https://github.com/SDL-Hercules-390/hyperion/files/2304763/mips.patch.txt)

(The above patch is a very long shot in the dark, but I've been lucky and have hit my mark before, so it's worth taking the shot IMO.)

&lt;me: standing by with fingers crossed...&gt;
___
(*) Why these "bugs" (if that's what they really are) don't seem to impact me or others, I have no idea.

**Comment by Fish-Git** [comment] 2018-08-29 07:16
@mcisho 

(Ping!) Have you had a chance to try my patch yet? Did it help any?

**Comment by Fish-Git** [comment] 2018-08-29 07:17
_**(OOPS! Typo! Wrong person!)**_

@moshix 

(Ping!) Have you had a chance to try my patch yet? Did it help any?

**Comment by Fish-Git** [comment] 2018-08-31 06:09
@moshix 

Another question: I happened to notice that all of the problem reports related to NUMA were created by you, so I'm wondering: does _this_ problem (non-updating MIPS display) also only occur on NUMA hardware? Or does it also occur on non-NUMA hardware?

I saw your comment made in issue #130 ("z/VM on NUMA selectively turns CPs off when under moderate load") where the problem does _not_ occur with Spinhawk 3.13, so I'm left wondering whether _this_ (non-updating MIPS display) might also be NUMA related. I'm thinking that's where our problem is. I'm thinking is we can figure out what our NUMA bug is (probably a race condition somewhere), then all of these other problems might go away too.

So does this problem only occur on NUMA hardware? Or does it also occur on SMP hardware?

Thanks!

**Comment by moshix** [comment] 2018-09-01 16:47
Fish

this problem also happens on non-NUMA machines, like my very simple Dell xps i5 laptop. 

I applied the patch and i am waiting for the problem to re-present itself. Will let you know. 

Sorry for being slow in responding, I am traveling for work. 

thanks

**Comment by Fish-Git** [comment] 2018-11-24 19:17
@moshix

I was recently able to reproduce the problem as-described and am actively looking into it. I will let you know as soon as I have a fix. (The fix _might_ be the patch I offered to you earlier, but I have not tried it -- _yet_.)

**Comment by moshix** [comment] 2018-11-25 00:36
Fish, thanks a lot. 

For me, the patch didn't resolve the problem, but I anxious to hear your experience with it. 

thanks

M

**Comment by Fish-Git** [comment] 2018-11-25 13:51
False alarm. Sorry!

The bug I recently tripped over is a completely different bug from whatever bug is causing your problem.

For you, the instcount was incrementing (_quite quickly!_) but your MIPS and SIOS rates were showing as zero. For _me_, my instcount was _not incrementing at all_ (thus causing a zero MIPS rate, duh!) even though I was actually executing many instructions, but my SIOS rate was displaying normally.

This was because, for me, I was only executing 50 instructions per I/O request (code... SSCH... LPSWE... and repeat...), but the code in cpu.c's `'run_cpu'` function was coded to only update `sysblk.instcount` every _**256**_ instructions.

Thus my instcount was never changing, and thus my MIPS rate was always calculated as being zero as a result (whereas my SIOS rate, not being dependent on the instruction counter, was displaying just fine). For _this_ bug (i.e. _my_ bug), I have a fix, and I will be committing it shortly.

_Your_ bug however, is still a complete mystery to me. I have yet to reproduce it and have _no freaking clue_ why it's occurring. &nbsp;  `:(`

Sorry!  &nbsp;  `:(`

**Comment by moshix** [comment] 2018-11-26 11:02
I have to say that I haven't been able to reproduce the problem in a while. 

Just for kicks, I started z/VM 6.3 and z/VM 6.2 on (what was then) SDL latest in early October and have been running them under load ever since then. z/VM 6.2 re-IPLd randomly once early on, but since October 19 both machines have been up without problems.

**Comment by ivan-w** [comment] 2018-11-26 11:12
Maybe 10fbb0dc9b57fbd40a5ebadaf2aa8741f577c1f9 has something to do with it ;) (I know.. bragging !)

**Comment by moshix** [comment] 2018-11-26 13:02
Most likely it does have something to do with it, because before that patch I was never able to have multi-CP running well in a Hercules config with more than just a handful of GB of RAM. 

However, there are still problems.  If I IPL under z/VM 6.2 or 6.3 a guest with identically named volumes (resident, paging, etc.... as per installation instructions), when I shutdown the top z/VM and re-IPL it won't come up saying that the paging space is corrupted. 

Also, z/VM 6.2 does sometimes, early after IPL, spontaneously re-IPL itself after a PROGxx

thanks for the amazing patch, though!

**Comment by Fish-Git** [comment] 2018-12-07 00:18
> However, there are still problems. If I IPL under z/VM 6.2 or 6.3 a guest with identically named volumes (resident, paging, etc.... as per installation instructions), when I shutdown the top z/VM and re-IPL it won't come up saying that the paging space is corrupted.
> 
> Also, z/VM 6.2 does sometimes, early after IPL, spontaneously re-IPL itself after a PROGxx

This is a _**completely different problem**_ from the one you created this GitHub Issue for. You should create a _new_ GitHub Issue for this problem, or else report this behavior in an already existing related GitHub Issue.

The _original_ issue (that you created _this_ GitHub Issue for) was that the MIPS indicator not updating.

And regarding _that_ issue (i.e. _**this**_ issue, _the one you are reading right now_), your earlier comment:

> I have to say that I haven't been able to reproduce the problem in a while.
> 
> Just for kicks, I started z/VM 6.3 and z/VM 6.2 on (what was then) SDL latest in early October and have been running them under load ever since then. z/VM 6.2 re-IPLd randomly once early on, but since October 19 both machines have been up without problems.

tells me that it's probably time to now close this issue as unreproducible.

If the problem re-occurs, please let us know (and/or feel free to re-open this issue).

Thanks!

**Closed by Fish-Git** 2018-12-07 00:18 UTC
Labels: BUG, Researching...
