### ISSUE TITLE
+++ OOPS! ++++ Hercules has crashed (segmentation fault)

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#549] opened 2023-03-08 19:55 UTC
I built Hyperion from the current GIT / hyperion . It results in version: 

<pre>
<b>HHC01413I Hercules version 4.5.0.10830-SDL-g58578601</b>
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I YBI-15313-10829
HHC01415I Build date: Mar  8 2023 at 19:22:36
<b>HHC01417I Built with: GCC 7.5.0
HHC01417I Build type: GNU/Linux x86_64 host architecture build</b>
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 12
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I Without ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    "Optimized" instructions
HHC01417I With    OPTION_USE_SKAIP_AS_LOCK
HHC01417I With    OPTION_SIE2BK_FLD_COPY
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
HHC01417I Running on: hercules (Linux-5.3.18-150300.59.106-default x86_64) MP=8
HHC01417I Built with crypto external package version 1.0.0.52-ga5096e5
HHC01417I Built with decNumber external package version 3.68.0.102-g3aa2f45
HHC01417I Built with SoftFloat external package version 3.5.0.105-g4b0c326
HHC01417I Built with telnet external package version 1.0.0.63-g729f0b6
</pre>

I then IPL **z/VM 6.4**, and it starts, but later in the process when some of common VMs start, Hercules crashes with segmentation fault: 

<pre>
HIS EXEC - RACIPLXI - MAY BE TAILORED TO YOUR NEEDS
RACFVM  : RDR FILE 0007 SENT FROM RACFVM   CON WAS 0007 RECS 0061 CPY  001 T NOHOLD NOKEEP
20:45:15 AUTO LOGON  ***       AUTOLOG2 USERS = 6     BY RACFVM
RACFVM  : AUTO LOGON  ***       AUTOLOG2 USERS = 6
RACFVM  : HCPCLS6056I XAUTOLOG information for AUTOLOG2: The IPL command is verified by the IPL command processor.
20:45:16 AUTO LOGON  ***       VMSERVS  USERS = 7     BY AUTOLOG2
20:45:16 AUTO LOGON  ***       VMSERVU  USERS = 8     BY AUTOLOG2
20:45:16 AUTO LOGON  ***       VMSERVR  USERS = 9     BY AUTOLOG2
20:45:17 AUTO LOGON  ***       DTCVSW1  USERS = 10    BY AUTOLOG2
20:45:17 AUTO LOGON  ***       DTCVSW2  USERS = 11    BY AUTOLOG2
20:45:17 AUTO LOGON  ***       VMSERVP  USERS = 12    BY AUTOLOG2
20:45:17 AUTO LOGON  ***       VMNBCSX  USERS = 13    BY AUTOLOG2
HHC00107I Starting thread cckd_ra(), active=0, started=0, max=2
HHC00107I Starting thread cckd_writer(), active=0, started=0, max=2
HHC00100I Thread id 00007f24279f8700, prio 0, name 'cckd_ra thread 1' started
HHC00107I Starting thread cckd_ra() from cckd_ra(), active=1, started=1, max=2
HHC00100I Thread id 00007f24277f6700, prio 0, name 'cckd_ra thread 2' started
HHC90020W 'hthread_setschedparam()' failed at loc=cckddasd.c:1793: rc=22: Invalid argument
HHC00007I Previous message from function 'hthread_set_thread_prio' at hthreads.c(1172)
HHC00100I Thread id 00007f24278f7700, prio 0, name 'cckd_writer thread 1' started
herc =====>
CP00 PSW=0706400080000000 0000000000000000 31..W....Z                                               instcnt 835,894,908; mips 43.60; I/O    195
<b>
    +++ OOPS! +++

Hercules has crashed! (Segmentation fault)

Creating crash dump... This will take a while...</b>
</pre>

I am not sure why. 

The previous version I generated October 2022 (Version 4..4.1.10647-SDL-gd0ccfbc9) works well. 

BR Florian

**Comment by Fish-Git** [comment] 2023-03-08 23:40
Hi Florian!

Please see:

* [**SUBMITTING PROBLEM REPORTS** \#373](https://github.com/SDL-Hercules-390/hyperion/issues/373)

Some things I'd like to see:

1. I would appreciate seeing the _complete Hercules log file_ rather than screen copies.
2. May we see your Hercules config file?
3. It says it created a crash dump _(i.e. "core" file)_. &nbsp;Did it? &nbsp;Do you have one to anayze? &nbsp;May we see it? <br>(Ref: [**"How to analyze a Linux "core" file (i.e. crash dump)", \#199**](https://github.com/SDL-Hercules-390/hyperion/issues/199)).
4. Does warning **`HHC00017W`** appear anywhere in your log file?
5. Have you tried the current **develop branch?** &nbsp;Does it also crash the same way? &nbsp;Maybe the problem has already been fixed?

Thanks.

**Comment by Fish-Git** [comment] 2023-03-08 23:54
FYI: I just tried it with my zVM 6.4 "FrankenVM" _(6.3 with 6.4 kernel)_ and it worked fine. No crash.

I forgot to ask: is this problem repeatable? Does it happen all the time (every time)? &nbsp;Or was this just a one-time event?

**Comment by fbi-ranger** [comment] 2023-03-09 04:13
Fish, 

YES, the problem is repeatable. 

Unfortunately I can not find a core file. I use openSUSE Leap 15.4 as OS. In the current directory there is no dump file. 

Checking the log it appears that the problem happens when Hercules processes the QETH device 0C00.3 
When I comment out this line in the config file the segfault does NOT happen. This device is used in z/VM for communication via vswitch. So I need this device. 

In version 4.4.1 the QETH statement is processed correctly and the system runs fine. 

[herc.current.log](https://github.com/SDL-Hercules-390/hyperion/files/10927549/herc.current.log)
[hercules.conf.txt](https://github.com/SDL-Hercules-390/hyperion/files/10927558/hercules.conf.txt)

**Comment by Fish-Git** [comment] 2023-03-09 12:57
Thank you.

First, let's fix your _INCOMPLETE Hercules log file_ problem:

Please _remove_ the following line from the beginning of your Hercules configuration file:

    log herc.current.log 

and use the `-o` (or `--output=` or `--logfile=`) command line option instead, e.g.:

    hercules -f "hercules.conf.txt" -o "herc.current.log"

_(**Ref:** "Hercules Version 4: Installation and Operation", "Operating Procedure", [**Command line arguments**](https://sdl-hercules-390.github.io/html/hercinst.html#arguments))_

It's _**very important**_ for your Hercules log file to be a _complete_ log file. The way you have it setup right now, we are missing the beginning of the log file. We are missing some very important startup messages. Doing the above will fix this.

Once you have done the above, please try your test again, and post your resulting Hercules log file.

NOTE: doing the above will _not_ fix your problem, but I suspect it will confirm my suspicion that warning message `HHC00017W` is being issued, indicating your system is not configured correctly to produce `core` files (i.e. crash dumps). That is why you could not find any core file: your system is not configured correctly to produce them!

As you know, I am not that skilled at Linux, but other people are, and I'm sure someone will be able to help you configure your **openSUSE** system to create core files. Generic instructions for doing so are documented in GitHub Issue \#<span>199</span>: ["How to analyze a Linux "core" file (i.e. crash dump)"](https://github.com/SDL-Hercules-390/hyperion/issues/199).

Core files are important as they provide the _only_ way to discover why a program has crashed. Without a core file (crash dump) to analyze, it becomes impossible to know with any degree of certainty why a program has crashed.

I'm guessing _(because I don't have a core file)_ that your crash is being caused by an inadvertent bug that version 4.5.0 introduced into the `hercifc` utility. Being able to analyze the core file (crash dump) will allow us to be certain instead of simply guessing (presuming).

The bug that I'm guessing (presuming) is causing your crash has already been found and fixed, and will appear in the next 4.6.0 release of Hercules _(currently still in development)_.

If you want the fix now, you will have to "switch" your repository to the `develop` branch (`git checkout develop`), and then rebuild Hercules. This will give you the latest and greatest bleeding edge development version of Hercules with the `hercifc` fix in it. _(Hint: when you clone a repository, the default branch is always `master`, so if you want a different branch, you have to specifically request is via `git checkout...` after doing your clone.)_

I hope that helps!

**Comment by Fish-Git** [comment] 2023-03-09 13:27
p.s. If you use preconfigured interfaces then hercifc would not be needed.

**Comment by fbi-ranger** [comment] 2023-03-09 21:57
Here you have the requested complete log file
[hercules.current.log](https://github.com/SDL-Hercules-390/hyperion/files/10936400/hercules.current.log)

and the log from gdb: 

[gdb.txt](https://github.com/SDL-Hercules-390/hyperion/files/10936403/gdb.txt)

**Comment by Fish-Git** [comment] 2023-03-09 23:59
> Here you have the requested complete log file

Thank you. It looks like crash dumps _are_ enabled for your system. _(I do not see any `HHC00017W` warning)_

So you _should_ have a core file _somewhere_ on your system. openSUSE might be placing them in some unexpected location. _(Why Linux has to make obtaining crash dumps (core files) so difficult/complicated is beyond me! Sheesh!)_

I did a quick Google and found this:

  * **SUSE Support:  [_How to obtain application core dumps_](https://www.suse.com/support/kb/doc/?id=000015982)**

I hope it will be helpful?

> and the log from gdb:

Unfortunately, that does not tell me very much. :(

It looks like you may have built your Hercules without any debugging optimization options? _(e.g. `-g -g3 -ggdb3`)_  What value did you specify for your `--enable-optimization='xxx...'` ./configure option? &nbsp;May we see your `./configure` log?

The "gdb" flags (``-g -g3 -ggdb3`) are important because they cause important debugging information to be included in the core files (crash dumps) that get created. Crash dumps without any debugging information in them are mostly useless.

You might consider building your Hercules using Bill Lewis's (@wrljet, one of our fellow Hercules developers) most excellent "Hercules Helper" script:

  * [_**Hercules-Helper**_](https://github.com/wrljet/hercules-helper)

It make building Hercules _very_ easy and ensures that Hercules is always built correctly for your platform.

### STATUS:

1. Rebuild Hercules using the correct build flags so we can obtain a meaningful _(useful)_ crash dump. _(I highly recommend using Bill's "Hercules-Helper" script.)_
2. Determine _where_ openSUSE saves its core files.
3. Once you find it, .zip and upload it so that it can be analyzed.
4. _(Optional):_ Checkout the develop branch and build Hercules from that. It might just fix your problem! `(*)`

Thanks.

`(*)` &nbsp;_(But only a good core file will be able to tell us that for sure.)_

**Comment by fbi-ranger** [comment] 2023-03-10 07:46
Well, indeed I managed to get the core dump yesterday. From that dump I created the gdb.txt.
I always compile the binary with -gdb3 option. Here is the ./config string:

`./configure --enable-custom="YBI-15313-10829" --prefix=/local/sys1/z390/herc15313 --enable-capabilities --enable-cckd-bzip2 --enable-het-bzip2 --disable-fthreads --enable-setuid-hercifc=hercules --enable-multi-cpu=12  --enable-optimization="-**ggdb3** -O3 -march=native -mfpmath=sse -msse4.1 -fexpensive-optimizations" --enable-extpkgs=/local/sys1/src/git/SDL-Hercules-390/extpkg`

The core dump is 8GB, compressed 62 MB and it seems that I cannot upload that size to github. I have put it to OneDrive: 
https://1drv.ms/u/s!AkdyZ53JALT0g33aafRcoi-z3Uzt?e=9iLO4M
Sorry I am not a developer.

**Comment by Fish-Git** [comment] 2023-03-10 11:36
> Sorry I am not a developer.

And I am sorry I am not a Linux person! &nbsp;`:(`

I _APOLOGIZE_, Florian!  Apparently a core file cannot be analyzed on a system where the crash did not occur! &nbsp;`:(`

  * [How to analyse a core dump from a different machine?](https://serverfault.com/questions/1088296/how-to-analyse-a-core-dump-from-a-different-machine)

On Windows, a crash dump that occurs on _any_ Windows system can be easily analyzed on _any **other**_ Windows system`(*)`, which makes analyzing crash dumps trivially easy to do on Windows.

`(*)` &nbsp;_(As long as you also have the associated `.pdb` files that were created when the executable was built of course, which is something we always provide with each release.)_

This is unfortunately not true on Linux, apparently. &nbsp;`:(`

According to the above web page, the two systems apparently have to have the same Linux kernel _(which IMO is stupid)_. So I am unfortunately unable to analyze your .core file. What I asked you for was a complete waste of time and effort. I apologize for that. I didn't know.

**So... where does that leave us?**

The only help I can provide you is to please try the current git develop branch. I suspect it will likely resolve your crash problem. Please let me know whether it does or not.

* If it resolves your problem, I will close this issue.

* If it does _not_ resolve your problem, I will close this issue! &nbsp;`(**)`

`(**)` &nbsp;_(Since I do not believe we can debug it any further!)_

If you need help with checking out the develop branch on git, let me know. It is incredibly easy. Once you rebuild the current develop branch of Hercules, I am confident your crash will go away.

That's the best I can do for now.

Sorry! &nbsp;`:(

**Comment by fbi-ranger** [comment] 2023-03-10 13:07
OK! No problem. My system is not a development system. Sorry for that. 
Thanks for your help. I will try to check out the development version. 
From my point of view, please close the case.

**Comment by Fish-Git** [comment] 2023-03-10 13:10
Closing per request.

**Closed as completed** 2023-03-10 13:10 UTC
Labels: BUG, L, Unknown
