### ISSUE TITLE
LCS Layer 3 is broken for zLinux guest

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#156] opened 2018-12-02 19:32 UTC
I have tried the zLinux guest on a Linux x86_64 host and a Windows 10 host (or at least a Windows 10 virtual machine running on the Linux x86_64 host), and had the same results on both.

When zLinux is using an LCS it issues a sequence of LCS commands to determine the LCS's capabilities. The sequence starts with Startup, then Start LAN and ends with Stop LAN, then Shutdown. After the Shutdown, halts are issued for the two devices.

With SDL Hercules, the zLinux LCS driver hangs at this point. With Hyperion the zLinux LCS driver continues normally and issues Startup, then Start LAN, and everything proceeds as it should.

The hang is caused by the section of code in `ctc_lcs.c` that begins `if (haltorclear)` at approximately line 2570. The section includes a `return;`. If the return is removed, the zLinux lcs driver does not hang, it continues and issues Startup, then Start LAN. However, at this point the zLinux LCS driver issues an "Error in opening device!" message, and shortly afterwards SDL Hercules abends. I have yet to determine where the abend occurs. Unfortunately, I'm about to be away for six weeks, so that determination is going to be delayed.

My zLinux guest is **Fedora 29 s390x**, though the hang also happened with Fedora 28 s390x. I had hoped to confirm the problem with Debian s390x, but Debian doesn't support LCS any more! zLinux seems to be deprecating everything except OSD.

**Comment by ivan-w** [comment] 2018-12-02 22:09
Working on this already ;)

There apparently is an issue when an HSCH is issued to a suspended CCW and a PCI is also pending... 

--Ivan

**Comment by ivan-w** [comment] 2018-12-02 22:10
LCS works fine on debian (just not for install)

**Comment by mcisho** [comment] 2018-12-03 11:16
Perhaps Debian doesn't automatically bring the LCS up, thus making the znetconf -A necessary, because /etc/sysconfig/scripts/hardware/hwup-ccw contains the following:-
  3088/60)
  error "lcs not supported"
  ;;

**Comment by ivan-w** [comment] 2018-12-03 11:30
I did manage to bring up the LCS on debian..but I need to activate CCW tracing to overcome the time dependent race condition ;)

**Comment by mcisho** [comment] 2018-12-03 11:58
Thank you for reminding me of znetconf, I always forget it! Using non-SDL Hyperion, Debian and LCS work just fine once the command has been entered, as you said. All I have to do now is get CTCI working with Fedora! Not this year though.

**Comment by moshix** [comment] 2018-12-16 15:15
well, SDL latest (as of today) also doesn't work for LCS on VM/ESA 2.40.... No response whatsoever. It works fine on Hercules 3.13. 

CTCI in VM/ESA 2.40 with SDL latest works fine .

thanks
M

**Comment by ivan-w** [comment] 2018-12-16 15:57
LCS with VM/ESA 2.4.0 works fine for me !

Ready; T=0.05/0.06 12:51:28                                                  
netstat home                                                                 
VM TCP/IP Netstat Level 320                                                  
Home address list:                                                           
                                                                             
Address            Link                                                      
-------            ------                                                    
192.168.100.208    ETH1                                                      
Ready; T=0.07/0.09 12:51:31                                                  
netstat devlink                                                              
VM TCP/IP Netstat Level 320                                                  
                                                                             
Device LCS1              Type: LCS         Status: Ready                     
Queue size: 0            Address: 0A00                                       
   Link ETH1             Type: ETHERNET    Net number: 0                     
Ready; T=0.06/0.07 12:51:33                                                  
netstat gate                                                                 
VM TCP/IP Netstat Level 320                                                  
Known gateways:                                                              
                                                                             
NetAddress      FirstHop        Link     Pkt Sz  Subnet Mask     Subnet Value
----------      --------        ------   ------  -----------     ------------
Default         <direct>        ETH1     1500    <none>                      
192.168.100.0   <direct>        ETH1     1500    <none>                      
Ready; T=0.12/0.14 12:51:37                                                  
ping 192.168.100.1                                                           
Ping Level 320: Pinging host 192.168.100.1.  Enter #CP EXT to interrupt.     
PING: Ping #1 response took 0.001 seconds. Successes so far 1.               
Ready; T=0.06/0.07 12:51:42                                                  

(On a side note.. I did run into an IFI004 ABEND on VM/ESA 2.4.0 (not CCKD64)...

--Ivan

**Comment by moshix** [comment] 2018-12-16 15:59
Hmmmm. I will try it again. But this morning I couldn’t get it to work whereas Hercules 3.13 worked immediately

**Comment by ivan-w** [comment] 2018-12-16 16:00
It's a Layer 2 LCS though.. Haven't tried Layer 3.

**Comment by moshix** [comment] 2018-12-16 16:55
Pretty sure I am on layer 3. Let me check later again. Thanks

**Comment by Fish-Git** [comment] 2018-12-25 01:00
> Well, SDL latest (as of today) also doesn't work for LCS on VM/ESA 2.40.... No response whatsoever. It works fine on Hercules 3.13.

Yet more evidence that SDL Hyperion's LCS handler is broken! &nbsp;_(Frick!)_ &nbsp;`:(`

Maybe I should just rip out that new tuntap device query logic altogether and just always do all offloading manually? That's the only thing I can think of that's causing it: my new ioctl calls that are attempting to query the tuntap device's capcabilities. It obviously has some unintended side effect that's causing problems later on down the road. I should probably just rip it out and be done with it.

I sure which Linux's tuntap was better documented!&nbsp;`:(`

**Comment by ivan-w** [comment] 2018-12-25 01:03
offload by the tun/tap is already disabled and always done by hercules.

**Comment by moshix** [comment] 2018-12-25 01:34
Yes, not working for me across the board: zLinux, z/VM and z/OS. 

On the other hand CTCI works much better in SDL than in 3.12/3.13. 

thanks

M

**Comment by ivan-w** [comment] 2018-12-25 01:58
* LCS z/Linux breakage, I can reproduce (I see how it breaks - don't know how to fix it yet - but it's some subtle instance of halting a device in a suspended state with PCI pending or other status pending).

Because there is a Heisenbug in there as well (if CCW tracing on, the problem goes away), it's complicated to debug.

* LCS (using a pre-defined tap connected to a virtual switch - so NOT using hercifc here) works as expected for me under z/VM 6.3 and VM/ESA 2.4

**Comment by mcisho** [comment] 2018-12-25 10:15
> Because there is a Heisenbug in there as well (if CCW tracing on, the problem goes away), it's complicated to debug.
I must have a slower machine, the problem doesn't go away for me with CCW tracing on. I'll send you a log soon.

**Comment by Fish-Git** [comment] 2018-12-25 11:13
> Because there is a Heisenbug in there as well (if CCW tracing on, the problem goes away), it's complicated to debug.

Which is why Greg Smith created our handy PTTRACE facility!

https://github.com/SDL-Hercules-390/hyperion/blob/64b1b3f14f381b2af45c1188e12a8f94b2605e8a/ctc_lcs.c#L42-L52

&nbsp;
If the existing `PTT_DEBUG` statements in `ctc_lcs.c` don't provide enough information for you (or don't provide the right information you need), then simply insert some of your own, rebuild, and then use the `ptt` command to activate "lcs2" ptt tracing:

```
HHC01603I help ptt
HHC01603I
HHC01602I Command               Description
HHC01602I ----------------      -------------------------------------------------------
HHC01602I ptt                  *Activate or display internal trace table
HHC01603I
HHC01603I Format: "ptt [?] [events] [options] [nnnnnn]"
HHC01603I
HHC01603I When specified with no operands, the ptt command displays the defined trace
HHC01603I parameters and the contents of the internal trace table.
HHC01603I
HHC01603I When specified with operands, the ptt command defines the trace parameters
HHC01603I identifying which events are to be traced. When the last option is numeric,
HHC01603I it defines the size of the trace table itself and activates tracing.
HHC01603I
HHC01603I Events:    (should be specified first, before any options are specified)
HHC01603I
HHC01603I      (no)log          trace internal logger events
HHC01603I      (no)tmr          trace internal timer events
HHC01603I      (no)thr          trace internal threading events
HHC01603I      (no)inf          trace instruction information events
HHC01603I      (no)err          trace instruction error events
HHC01603I      (no)pgm          trace program interrupt events
HHC01603I      (no)csf          trace interlocked instruction type events
HHC01603I      (no)sie          trace SIE instruction events
HHC01603I      (no)sig          trace SIGP instruction events
HHC01603I      (no)io           trace I/O instruction events
HHC01603I      (no)lcs1         trace LCS timing events
HHC01603I      (no)lcs2         trace LCS general debugging events
HHC01603I
HHC01603I options:   (should be specified last, after any events are specified)
HHC01603I
HHC01603I      ?                show currently defined trace parameters
HHC01603I      (no)lock         lock table before updating
HHC01603I      (no)tod          timestamp table entries
HHC01603I      (no)wrap         wraparound trace table
HHC01603I      to=nnn           automatic display timeout  (number of seconds)
HHC01603I      nnnnnn           table size                 (number of entries)
```

&nbsp;
Then when the problem occurs, use the `ptt` command to dump the table.

**Comment by Fish-Git** [comment] 2018-12-25 12:17
> I know that. `:)`

Cool. I thought maybe you had forgotten about it. It's good to know you haven't.&nbsp;`:)`

> But the information I yield from the fact that, doing `t+<cuu>` may alter the behavior, is that it _**is**_ apparently a time dependent issue!

Ah. Good point!

Well, I guess I'll leave you alone then. It sounds like you're on top of it!

Thanks, Ivan.

**Comment by ivan-w** [comment] 2018-12-25 20:08
082b69c5b764782afae24fa3483b930b7f2aa7d0 fixes First part of znetconf hanging (it's a 2 part thing... I still have to figure out the second part !)

**Comment by Fish-Git** [comment] 2019-04-20 22:43
@moshix 

Has this issue, from _your_ point of view, been resolved to your satisfaction?

You originally reported LCS was hanging at shutdown, but based on a review of all of the comments made in this GitHub Issue, it appears Ivan's commit supposedly resolves this problem. Can you confirm that is true? Can you confirm that the hang no longer occurs?

Thanks!

**Comment by Fish-Git** [comment] 2019-04-20 22:54
@ivan-w 

Ivan, can you provide us with a status update regarding the `IFI004` issue you were attempting to track down? Does the problem still exist? Maybe recent commits made to SDL Hyperion since this issue was first opened might have also resolved your `IFI004` issue too?

Commits b76163a6646abef539e6800df3fbdb6adaed9a9d (the actual code) and 607e01d9a5fd604ffc444ed8eec815bd60b07174 (Release Notes) seemed to resolve an [`IFI004` issue that moshix was having](https://github.com/SDL-Hercules-390/hyperion/issues/190).

Maybe your `IFI004` issue has now been resolved too?

Can you confirm for me whether the `IFI004` problem you were attempting to track down is still occurring or whether it has now been resolved? I would like to close this issue if possible, but I obviously don't want to do so if the problem is still occurring!

Thanks.

**Comment by ivan-w** [comment] 2019-04-21 00:39
Fish,
This was an intermediate fix (it is part of the solution, but not THE solution). The issue is not resolved yet.
But I must admit I got sidetracked.
There are still conditions under which a HSCH on the read or write LCS subchannel will yield the wrong results, leading the LCS to fail on a linux host - or even worse hang the linux kernel altogether.
I request this issue to remain open at this time.
--Ivan

**Comment by ivan-w** [comment] 2019-04-21 00:41
I am however somehow convinced the IFI004 abend and the failing Linux support of LCS to be symptoms of  the same issue.

**Comment by moshix** [comment] 2019-04-21 04:53
Fish

I have nuked my z/Ubuntu 18.04 installation by mistake... (it takes about 3-5 hours to install z/Ubuntu on top of SDL, but only about 25 minutes on zPDT...), so I will reinstall z/Ubuntu and test LCS...

Will let you know more soon

thansk

M

**Comment by Fish-Git** [comment] 2019-04-21 06:20
> **The issue is not resolved yet.**
> I request this issue to remain open at this time.

10-4. Labels adjusted. I'll leave you alone then. If there's anything I can do to help, please let me know. Thanks.

**Comment by Fish-Git** [comment] 2019-07-10 06:43
Just checking for a status update: Is this issue still a problem?

**Comment by Fish-Git** [comment] 2019-08-07 07:37
> The hang is caused by the section of code in `ctc_lcs.c` that begins `if (haltorclear)` ...

> There apparently is an issue when an HSCH is issued to a suspended CCW and a PCI is also pending...

> It's essentially a race condition somewhere...

> ... it's some subtle instance of halting a device in a suspended state with PCI pending or other status pending).

> There are still conditions under which a HSCH on the read or write LCS subchannel will yield the wrong results ...

The above comments seem to describe a bug very similar to the one I just recently fixed in commit 6813cfa76325b7e0653ab9443d7962b870e74aba for issue #229 (missing interrupt for CSCH). What I determined was that due to a race condition, one of channel.c's DEQUEUE_IO_INTERRUPT_QLOCKED calls was failing and the code in channel.c wasn't expecting that. It was never checking the return code from DEQUEUE_IO_INTERRUPT_QLOCKED to verify the interrupt that it _thought_ it was dequeuing actually got dequeued, resulting in the interrupt that _should_ have been dequeued remaining in the queue!

Perhaps something similar is happening here, but for LCS? _(just guessing!)_

You might consider adding some debug code in all of the places where channel.c is currently coded to expect its DEQUEUE_IO_INTERRUPT_QLOCKED call to always succeed to see if maybe one of them is unexpectedly failing?

**Comment by Fish-Git** [comment] 2020-10-01 22:01
Ian? (@mcisho)

Another very old unresolved issue with no recent activity, compelling me to once again ask whether the originally reported is still a problem or not? Does this problem still exist?

If not, can I close this issue as "unknown"?

If it's still occurring however, is there an easy way for me to reliably reproduce it so that maybe I can start looking into it? Do I just have to try installing z/Ubuntu using an LCS device? Is that it? Or is there more to it?

Thanks.

**Comment by mcisho** [comment] 2020-10-01 22:20
Yes, go ahead and close. I haven't reproduced the problem for some time, but then again I haven't used Hercules much for some time.

**Comment by Fish-Git** [comment] 2020-10-02 09:40
Closing.

**Closed by Fish-Git** 2020-10-02 09:40 UTC
Labels: BUG, L, QUESTION..., Researching...
