### ISSUE TITLE
SCSI tape error

### ISSUE THREAD

**Issue by vinatron** [SDL-Hercules-390/hyperion#512] opened 2022-10-12 19:57 UTC
Hello,
I just built a fresh install of Hyperion and I'm running into an issue. I am trying to attach a SCSI IBM DAT DDS4 drive to Hercules and I used the following commands:
```
HHC01603I attach 560 3480
HHC00224I 0:0560 Tape file *, type AWS: display "        "
HHC01603I devinit 560 /dev/nst0
HHC00221I 0:0560 Tape file /dev/nst0, type SCSI: format type SCSI attached tape drive
HHC00100I Thread id 00007f9c9472f640, prio 4, name 'scsi_status' started
HHC02245I 0:0560 device initialized
```
And when trying to IPL from the tape that I made with tape copy which successfully completed I get the following:
```
HHC01603I ipl 560
HHC00811I Processor CP00: architecture mode ESA/390
HHC01315I 0:0560 CHAN: ccw 02000000 60000018
HHC01312I 0:0560 CHAN: stat 0200, count 0018=>00000000 00000000 00000000 00000000 ................
HHC01313I 0:0560 CHAN: sense 40422043 00000020 00000000 00000000 00000000 00000000 000600FC 00560000
HHC01314I 0:0560 CHAN: sense INTREQ ITF WRI
HHC00828E Processor CP00: ipl failed: architecture mode ESA/390, csw status 0200, sense 40422043 00000020 00000000 00000000 00000000 00000000
HHC00007I Previous message from function 's390_load_ipl' at ipl.c(525)
```
&nbsp;
Any ideas? I'd greatly appreciate the assistance in troubleshooting this because I have no idea how tapecopy can work and Hercules itself not work. Also for reference I ran Hercules and tapecopy as root so it's definitely not a privilege issue. 

Thanks,

Vincent

**Comment by Fish-Git** [comment] 2022-10-13 02:54
1. https://github.com/SDL-Hercules-390/hyperion/issues/373
2. Please attach your _complete_ Hercules configuration file.
3. Please attach your _complete_ Hercules log file.

According to manual GA32-0042-4 "IBM 3480 Magnetic Tape Subsystem - Channel Commands, Status and Sense Bytes, and Error Recovery Procedures", a sense byte 0 of X'40' means "Intervention Required" (as indicated by Hercules's `HHC01314I 0:0560 CHAN: sense INTREQ ITF WRI` message).

This tells me there's either no tape mounted on your tape drive, or the tape drive is not online and ready.

Also, depending on the model of your tape drive, you may or may not need to specify [additional options](https://sdl-hercules-390.github.io/html/hercconf.html#Quantum) on the Hercules tape drive device statement. (I have no idea what a SCSI IBM DAT DDS4 drive is or how it behaves; check your tape drive documentation/user manual.)

You might or might not also be interested in our [`SCSIMOUNT`](https://sdl-hercules-390.github.io/html/hercconf.html#SCSIMOUNT) configuration file option as well. That way you won't have to be manually issuing `attach` and `devinit` commands each time (which might well be the cause of your problem, but we won't know until you provide us with more information as requested in items 1-3 above).

**Comment by vinatron** [comment] 2022-10-14 13:27
I'll have to collect the data.I did a quick test today and found that adding`SCSIMOUNT YES` to the configuration helped. However when advancing files I have to IPL twice any reason for this? I'll try and collect the data and submit for further analysis but it is interesting that I got somewhere. Thanks for the assistance!

**Comment by Fish-Git** [comment] 2022-10-14 18:59
> However, when advancing files I have to IPL twice. Any reason for this?

I'm not sure what you mean. What do you mean by "when advancing files ..."? And why are you IPLing twice? What are you trying to do? Is the file you want/need to IPL not the very first file on the tape? Are you perhaps wanting to IPL from the _second_ file on the tape? What is the first file on the tape? What is the second file on the tape?

What are the symptoms you are experiencing/seeing? Seeing your _complete_ Hercules log -- from beginning to end (as well as your _complete_ Hercules configuration file too) -- would certainly help us to better help you!

**Comment by Fish-Git** [comment] 2022-10-26 22:53
Vincent (@vinatron),

FYI: still waiting for requested info (complete Hercules configuration and log files).

Or, if problem has since been resolved(?) (has it??), may I close this issue?

Thanks.

**Comment by Fish-Git** [comment] 2022-11-02 00:25
Closing due to no response.

The user can always re-open it again if they wish.

**Closed as completed by Fish-Git** 2022-11-02 00:25 UTC
Labels: User Error, L, Unknown
