### ISSUE TITLE
OOPS! Hercules has crashed!

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#311] opened 2020-06-22 11:50 UTC
Hercules 4.3.9999.10144-SDL-g5315756f running on Windows 10 virtual machine on Fedora 32 host. Hercules had been running Fedora 32 s390x guest, guest had shutdown, Hercules was being closed.

The attached screenshot shows where the oops occurred. Is this sufficient, or do you want me to FTP the dump et al?

![image](https://user-images.githubusercontent.com/1387091/85284600-c5cb9d00-b48f-11ea-8b2b-e65dca39a496.png)

**Comment by Fish-Git** [comment] 2020-06-23 07:08
> The attached screenshot shows where the oops occurred. Is this sufficient, or do you want me to FTP the dump et al?

Nah. The dump isn't going to show me anything more than what your screenshot already does.

**Comment by Fish-Git** [comment] 2020-06-24 21:24
Ian (@mcisho),

**Standard question:** is this crash reproducible? (or is there anything that one can do to increase the likelihood of being able to reproduce it?)

I think I still have a s390x Hercules system stashed away somewhere that I haven't used in a long time, but if it's in any easily reproducible (or even somewhat easily reproducible) on a non-390x Herc system, that would of course be ideal. (As I recall, running s390x Herc is dog slow and a PITA!)

I'm not ready to start looking into this issue quite yet (still deep into TXF at the moment!), but I'd like to have all the information ready for when I do eventually get around to looking into it.

Thanks.

**Comment by mcisho** [comment] 2020-06-25 13:51
![image](https://user-images.githubusercontent.com/1387091/85732237-80aba300-b6fb-11ea-8355-fdf181e3fdc5.png)

**Comment by mcisho** [comment] 2020-06-25 15:37
Han't suceeded in reproducing either of the Oops.

**Comment by Fish-Git** [comment] 2020-06-25 16:43
> I was trying to reproduce the Oops, but got a different Oops instead!

It's probably the same bug just manifesting itself slightly differently.

I suspect it's the same (or very similar) bug as the one I _thought_ I had already fixed for you just recently: commit 5315756f79cfd86219362e9627215af87a140fe6 to resolve(?) Issue #303.

I probably missed something somewhere. &nbsp; `:(`

As I said, I'm still quite busy working on TXF at the moment, but as soon as I get a chance, I'll jump right on this one. Your patience is of course appreciated.

(Keep trying to recreate it though, and let me know if you discover any clues doing so! Thanks!)

**Comment by Fish-Git** [comment] 2020-10-01 21:33
Ian? (@mcisho)

Has this problem reoccurred at all since when you first reported it? (i.e. has it happened at all since June 22?)

If not, I'm willing to write it off as an "unknown", "unable to reproduce" problem if that's okay with you.

I realize that kind of sucks, but if neither of use can reliably reproduce the problem (or at least have a strong suspicion as to what is likely causing it), then there's really nothing that can be done to "fix" it.

Can I close this issue? (as "unresolved") Or do you want me to keep it open?

Thanks.

**Comment by mcisho** [comment] 2020-10-01 22:24
Yes, go ahead and close. I haven't used Hercules much recently, but when I have there haven't been any Oops.

**Comment by Fish-Git** [comment] 2020-10-02 09:39
As you wish!

**Closed as completed by Fish-Git** 2020-10-02 09:39 UTC
Labels: BUG, Unknown
