### ISSUE TITLE
MVT/ASP and TK3UPD/JES3 problems with SDL Hyperion 4.2

### ISSUE THREAD

**Issue by cjar1950** [SDL-Hercules-390/hyperion#235] opened 2019-08-09 14:12 UTC
I am having issues with both **MVT/ASP** and **TK3UPD/JES3** under build R4.2.0.9708-SDL-x64, which weren't there with the previous builds (SDL_TEMP_4.2_PVT_X64_VS2008 & R4.1.0.9426-SDL-x64 and earlier).

When ASP and JES3 start, a second console is initiated, which controls ASP and JES3 respectively.

With the latest build, when a ASP/JES3 command is entered into this console:
```
*s jss
*i s
*return
*i q,n=all
*x  cr,in=00c,k
```

The first few characters of the command are dropped, resulting in invalid command.

Chris

**Comment by cjar1950** [comment] 2019-08-09 14:13
Chris

**Comment by cjar1950** [comment] 2019-08-10 17:54
MVT/ASP conf 
[asp.txt](https://github.com/SDL-Hercules-390/hyperion/files/3489171/asp.txt)
MVT/ASP hercules.rc
[hercules.txt](https://github.com/SDL-Hercules-390/hyperion/files/3489172/hercules.txt)

Terminal I have problems with:- address 014

d u,,,014,1 response:-
155910   ASP1 R= IEE450I 15.59.10 UNIT STATUS 027 
155910   ASP1 R= UNIT TYPE STATUS  VOLSER VOLSTATE
155910   ASP1 R= 014  3158 O

**Comment by cjar1950** [comment] 2019-08-10 17:59
MVS TK3UPD JES3 conf
[tk3upd.txt](https://github.com/SDL-Hercules-390/hyperion/files/3489177/tk3upd.txt)
MVS TK3UPD JES3 hercules.rc
[hercules.txt](https://github.com/SDL-Hercules-390/hyperion/files/3489178/hercules.txt)

Terminal I have problems with:- address 0c6
d u,,,0c6,1 response:-
              1602052  R=          D U,,,0C6,1
              1602052  R=          IEE450I 16.02.05 UNIT STATUS 186
              1602052  R=          UNIT TYPE STATUS  VOLSER VOLSTATE
              1602052  R=          0C6  3277 O

**Comment by cjar1950** [comment] 2019-08-11 10:02
I am getting the same problem with some flavours of vm/370. 

I also have tried using personal communications for os/2 v4.1, as the 3270 emulator, with no difference

**Comment by Juergen-Git** [comment] 2019-08-25 17:59
I currently have no ASP, JES3, or VM/370 system running. Would you please provide an example, as simple as possible, on how to reproduce the issue without having to setup of a complex system environment first? Thanks!

**Comment by cjar1950** [comment] 2019-08-25 23:03
Jurgen,

The simplest way to see this, is by installing Kevin Leonards MVT/ASP.
This can be obtained from  http://www.ibiblio.org/jmaynard/asp.zip

Assuming that you have Windows 7:-

If you unzip the file asp.zip to your desktop.
Replace the file asp.conf in the conf directory with the attached
asp.conf, and  insert the attached hercules.rc into the same directory.

I have hercules R4.2.0.9708-SDL-x64 in the directory C:\program
Files\Hercules\R4.2.0.9708-SDL-x64.

Start a "command prompt" session. 

set the path to point to Hercules\R4.2.0.9708-SDL-x64.

path c:\program files\hercules\R4.2.0.9708-SDL-x64;%path%

cd to the directory asp in the unziped area on your desktop.

CD C:\Users\c jarman\Desktop\asp\asp

Run the command :-
hercules -f conf\asp.conf -r conf\hercules.rc

on the operators console 
hit enter to :- IEA101A  SPECIFY SYSTEM PARAMETERS FOR RELEASE 21.8F MVT 
r 00,u to:- *00 IEE114A DATE=91.237,CLOCK=23.15.12 - REPLY WITH SET PARAMETERS OR U 

on the asp console, which shows:-
231645   INT02 ASP SYSTEM RESTART, ASP 3.2.0                                   
231645   ASP1 R= IEE143I OLD=010          NEW=02F         VALDCMD= ALL         
231645                                                                         
231645   ASP1 R= IEE143I ROUTCDE=ALL                                           
231645     T=M H=N                                                             
231645   ASP1 R= IEE252I MEMBER COMMND00 FOUND IN SYS1.PARMLIB                 
231645   AMSV33 DLOG FACILITY HAS BEEN TURNED OFF ON SUPPORT                   
231645   ASP1 R= IEE037I LOG NOT SUPPORTED.                                    
231645   ASP1 R= IEE351I SMF SYS1.MAN RECORDING NOT BEING USED                 
231645   ASP1 R= IEF403I ASP      STARTED    TIME=23.16.44                     
                                                                               
-------------------------------------------------------------------------------

Enter *s,jss

The response 

232123   ASP1 R= IEE305I JSS      COMMAND INVALID shows that the first 3
characters are not passed to asp.

Chris



-- 
 <cjar1950@yahoo.com>



----------------------------------------------------------------------------------------------------------------------------------

**Comment by Juergen-Git** [comment] 2019-08-26 01:29
Thanks! I'm able to reproduce it now...

**Comment by cjar1950** [comment] 2019-08-26 16:42
Juergen

As confirmed by Moshix, I have only seen a 3 byte offset.

With respect to VM/370, I cannot see what is happening. I get the problem with:-


VM370 (3 pack Bob Adeles VM370 system)
VM370 (4 pack Andy Norrie's VM370 system)
VM370 (4 pack Dave Wade VM370 system)
VM370 (6 Pack)

But not with:-

VM370 (5 pack VM370 system)
VM370 (6 Pack) 6.3 Beta2
VM370 (6 Pack) 6.3 Beta3

Chris

**Comment by ivan-w** [comment] 2019-08-29 12:41
Just to put my $.02 in the fray.. This has been a long standing issue. For some reason, under certain circumstances( which are yet to be determined), the Read Modified CCW to a 3270 terminal (3x74 controller emulation) after an AID attn isn't returning the SBA of the cursor - the missing 3 bytes.. Some programs get very confused by this. This has apparently nothing to do with the tn3270 client being used - I have seen this behavior under various tn3270 clients (leading for example to the fact that I have to append 3 spaces in some standalone utilities... they don't really care about the SBA - but they expect the data to be AFTER the SBA field)

**Comment by Juergen-Git** [comment] 2019-08-29 15:03
Thanks, Ivan!

Yes, yesterday evening I ended up exactly at this point: I was very sure that the problem lies in the code area I modified for the recent performance improvements. But in fact, from this changed code still the same old logic gets called that determines the offset into the incoming buffer at which the datastream begins. And this logic delivers in the given case 6 instead of 3. So, my next step is to find out, why it skips the SBA order, which, as you say, probably is trivial.

Your input is very valuable because I was so convinced that the problem must be in my changes that I in fact looked into the old positioning code only after I ran completely out of ideas around my changes.

I will continue working on this tomorrow, given today I'm still at the conference and in the evening I'm out for dinner with an old friend.

**Comment by Juergen-Git** [comment] 2019-09-02 01:30
77a201f should finally fix that thing once and for all (unless I broke something else now). So, I'd appreciate if anyone interested in the matter would rebuild and verify that the consoles are now working as expected.

**Comment by Fish-Git** [comment] 2019-09-02 06:43
> I'd appreciate if anyone interested in the matter would rebuild and verify that the consoles are now working as expected.

Confirmed! _ALL_ of my Hercules test systems are now behaving correctly as far as console handling goes. _Thank you_, Jürgen!

**Comment by Juergen-Git** [comment] 2019-09-03 00:55
Sorry for the mess! Yesterday I erroneously committed an intermediate version, which had some code disabled for debugging reasons. Probably this came from permanently hanging head downwards here in San Francisco (when comparing to Europe) ;-). So, while yesterday's version probably will not yield any problem at all, I still recommend to rebuild at the 18343fb level. Thanks for everyone's patience...

**Comment by Fish-Git** [comment] 2019-09-04 04:02
Re-tested with 18343fb953af79f63db1c0d9a244629cc54b628c: everything _still_ works just fine.

**Comment by Juergen-Git** [comment] 2019-09-04 18:24
Thanks for re-testing, Fish!

Chris, would you, as original poster of the issue, please confirm whether it's now working OK for you? Thanks!

**Comment by cjar1950** [comment] 2019-09-04 19:49
Jurgen,

As an old fashioned mainframe Coboller, I am trying to get Visual Studio 2017 installed and working. 

When I figure it out, I will test your fix.

Chris

**Comment by cjar1950** [comment] 2019-09-05 15:49
Jurgen,

Many thanks.

I can confirm that the issue with mvt/asp, MVS/JES3 and VM/370 seems to be resolved.

many thanks for your efforts.

Chris

**Closed** 2019-09-05 18:33 UTC
Labels: BUG, Waiting to close...
