### ISSUE TITLE
Random Hercules crash using OORexx with HAO

### ISSUE THREAD

**Issue by Vf58** [SDL-Hercules-390/hyperion#140] opened 2018-08-30 08:29 UTC
Hi Fish,

My apologies for my unclear explanations in the previous issues.

Hercules level : 4.0.0.9226
Windows 10 Pro 64 bits version 1803 / 17134.228 
OORexx : 4.2.0.9940

The dump and all the files specified in the attached $$readme.txt have been FTP uploaded to your [SoftDevLabs](http://www.softdevlabs.com) 'incoming' folder (ftp://www.softdevlabs.com) as "phidw-Dump-2018-08-27-Rexx.zip". You also will find print screen of Windows, Hercules level, license.

* $readme.txt&nbsp;&nbsp;&nbsp;&nbsp;_(EDIT: file removed as it contained sensitive information)_

The suspected rexx (mount#scr.rex) is started by "hao" when a 'mount privats' is displayed.

It was written 'quick and dirty' but I'm thinking it is not a reason to crash Hercules. I suspect the 'Execio' instruction to be the source of the problem. I put recently a trace and it currently occurs on the same instruction:
```
2018/08/30 10:20:02.580 000000F8     26 *-*   end
2018/08/30 10:20:02.580 000000F8     28 *-* Address HOSTEMU 'EXECIO * DISKR "'ScrFile'" (stem line. finis'
2018/08/30 10:20:02.580 000000F8        >L>   "EXECIO * DISKR ""
2018/08/30 10:20:02.580 000000F8        >V>   SCRFILE => "..\Tape Files\Lst-Scratch.txt"
2018/08/30 10:20:02.580 000000F8        >O>   "" => "EXECIO * DISKR "..\Tape Files\Lst-Scratch.txt"
2018/08/30 10:20:02.580 000000F8        >L>   "" (stem line. finis"
2018/08/30 10:20:02.580 000000F8        >O>   "" => "EXECIO * DISKR "..\Tape Files\Lst-Scratch.txt" (stem line. finis"
2018/08/30 10:20:02.580 000000F8        >>>   "EXECIO * DISKR "..\Tape Files\Lst-Scratch.txt" (stem line. finis"
2018/08/30 10:20:02.625 000000F8 
2018/08/30 10:20:02.625 000000F8                       ***************
2018/08/30 10:20:02.625 000000F8                       *    OOPS!    *
2018/08/30 10:20:02.625 000000F8                       ***************
2018/08/30 10:20:02.625 000000F8 
2018/08/30 10:20:02.625 000000F8                     Hercules has crashed!
2018/08/30 10:20:02.625 000000F8 
2018/08/30 10:20:02.625 000000F8 (you may or may not need to press ENTER if no 'oops!' dialog-box appears)
2018/08/30 10:20:02.625 000000F8 
```

Today the rexx executed 11 times and crash occurs at 12th.

I've attached the Rexx script below (rename with .txt, .rex is not permitted):

* [Mount#scr.rex.txt](https://github.com/SDL-Hercules-390/hyperion/files/2335281/Mount.scr.rex.txt)

Sorry again for the disagreement,

Philippe

**Comment by Fish-Git** [comment] 2018-09-04 17:39
Microsoft "Debugging Tools for Windows" WinDbg `!analyze -v` output for the dump your provided is as follows:
```

Microsoft (R) Windows Debugger Version 6.12.0002.633 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_DUMPS\Hercules.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

WARNING: Minidump contains unknown stream type 0x15
WARNING: Minidump contains unknown stream type 0x16
Comment: '4.0.0.9226-SDL-gbb5fa8a5'
Comment: '(C) Copyright 1999-2018 by Roger Bowler, Jan Jaeger, and others'
Comment: 'Running on: MAXIMUSVII-1410 (Windows-6.2.9200 Intel(R) x64) LP=4, Cores=4, CPUs=1'
Comment: 'Built with: Microsoft Visual Studio 2008 (MSVC 150030729 1)'
Comment: 'Build type: Windows MSVC AMD64 host architecture build'
Comment: 'Modes: S/370 ESA/390 z/Arch'
Comment: 'Max CPU Engines: 64'
Comment: 'Using   shared libraries'
Comment: 'Using   Fish threads Threading Model'
Comment: 'Using   Error-Checking Mutex Locking Model'
Comment: 'With    Shared Devices support'
Comment: 'With    Dynamic loading support'
Comment: 'With    External GUI support'
Comment: 'With    Partial TCP keepalive support'
Comment: 'With    IPV6 support'
Comment: 'With    HTTP Server support'
Comment: 'With    sqrtl support'
Comment: 'Without SIGABEND handler'
Comment: 'With    CCKD BZIP2 support'
Comment: 'With    HET BZIP2 support'
Comment: 'With    ZLIB support'
Comment: 'With    Regular Expressions support'
Comment: 'With    Object REXX support'
Comment: 'With    Regina REXX support'
Comment: 'With    Automatic Operator support'
Comment: 'Without National Language Support'
Comment: 'Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 hatomics=msvcIntrinsics'
Symbol search path is: C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_DUMPS;srv*C:\Windows\Symbols*http://msdl.microsoft.com/download/symbols
Executable search path is: C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_DUMPS
Windows 7 Version 17134 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS
Machine Name:
Debug session time: Mon Aug 27 01:28:22.000 2018 (UTC - 7:00)
System Uptime: not available
Process Uptime: 0 days 0:05:23.000
................................................................
...................................
Loading unloaded module list
.................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1af0.3724): Access violation - code c0000005 (first/second chance not available)
Unable to load image C:\Windows\System32\ntdll.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
ntdll+0x9bc04:
00007ffa`81abbc04 c3              ret
0:013> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify checksum for rexx.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for rexx.dll - 
Unable to load image C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_08e0c10ba840a28a\msvcr90.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for msvcr90.dll
*** ERROR: Module load completed but symbols could not be loaded for msvcr90.dll
***** OS symbols are WRONG. Please fix symbols to do analysis.

*************************************************************************
***                                                                   ***
***                                                                   ***
***    Your debugger is not using the correct symbols                 ***
***                                                                   ***
***    In order for this command to work properly, your symbol path   ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: ntdll!_PEB                                    ***
***                                                                   ***
*************************************************************************
Unable to load image C:\Windows\System32\kernel32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for kernel32.dll
*** ERROR: Module load completed but symbols could not be loaded for kernel32.dll
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Your debugger is not using the correct symbols                 ***
***                                                                   ***
***    In order for this command to work properly, your symbol path   ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: nt!IMAGE_NT_HEADERS32                         ***
***                                                                   ***
*************************************************************************
Unable to load image C:\Windows\System32\KERNELBASE.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for KERNELBASE.dll
*** ERROR: Module load completed but symbols could not be loaded for KERNELBASE.dll
Unable to load image C:\Windows\System32\ole32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ole32.dll
*** ERROR: Module load completed but symbols could not be loaded for ole32.dll
Unable to load image C:\Windows\System32\mswsock.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for mswsock.dll
*** ERROR: Module load completed but symbols could not be loaded for mswsock.dll
Unable to load image C:\Windows\System32\win32u.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for win32u.dll
*** ERROR: Module load completed but symbols could not be loaded for win32u.dll
Unable to load image C:\Windows\System32\user32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for user32.dll
*** ERROR: Module load completed but symbols could not be loaded for user32.dll

FAULTING_IP: 
HOSTEMU+19e0
00007ffa`664619e0 ??              ???

EXCEPTION_RECORD:  ffffffffffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 00007ffa664619e0 (<Unloaded_HOSTEMU.DLL>+0x00000000000019e0)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000008
   Parameter[1]: 00007ffa664619e0
Attempt to execute non-executable address 00007ffa664619e0

PROCESS_NAME:  hercules.exe

ADDITIONAL_DEBUG_TEXT:  
Use '!findthebuild' command to search for the target build information.
If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

MODULE_NAME: HOSTEMU

FAULTING_MODULE: 00007ffa81a20000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  5308e13e

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

EXCEPTION_PARAMETER1:  0000000000000008

EXCEPTION_PARAMETER2:  00007ffa664619e0

WRITE_ADDRESS:  00007ffa664619e0 

FOLLOWUP_IP: 
HOSTEMU+19e0
00007ffa`664619e0 ??              ???

MOD_LIST: <ANALYSIS/>

FAULTING_THREAD:  0000000000003724

BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ_BAD_INSTRUCTION_PTR_SOFTWARE_NX_FAULT_INVALID_WRONG_SYMBOLS

PRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ_INVALID

DEFAULT_BUCKET_ID:  INVALID_POINTER_READ_INVALID

LAST_CONTROL_TRANSFER:  from 00007ffa4eb7dc07 to 00007ffa664619e0

STACK_TEXT:  
00000000`0aa24538 00007ffa`4eb7dc07 : 00000000`0aa24870 00000000`00000000 00000000`00000246 00007ffa`4eb7dbec : <Unloaded_HOSTEMU.DLL>+0x19e0
00000000`0aa24540 00007ffa`4eb3f0f4 : 00007ffa`4eb3f5fa 00007ffa`4eb2ee64 00000000`00000000 00007ff4`6a254fe0 : rexx!RexxDidRexxTerminate+0x33ce7
00000000`0aa24570 00007ffa`4eb2f4c2 : 00007ff4`6a254f10 00000000`0aa24660 00000000`00000001 00007ff4`6a254f10 : rexx!RexxWaitForTermination+0x48124
00000000`0aa245b0 00007ffa`4eb7df10 : 00007ff4`6a254e50 00000000`0aa24840 00000000`00000000 00000000`00000000 : rexx!RexxWaitForTermination+0x384f2
00000000`0aa245e0 00007ffa`4eb2e447 : 00007ff4`6a254650 00007ff4`6a254650 00007ff4`6a2446d0 00007ff4`6a2446d0 : rexx!RexxDidRexxTerminate+0x33ff0
00000000`0aa247f0 00007ffa`4eb2da73 : 00007ff4`6a24ef90 00007ff4`6a24ef90 00007ff4`6a254e50 00007ff4`6a249270 : rexx!RexxWaitForTermination+0x37477
00000000`0aa248b0 00007ffa`4eb3d421 : 00007ff4`6a254650 00007ff4`6a254650 00007ff4`6a2446d0 00007ff4`6a249770 : rexx!RexxWaitForTermination+0x36aa3
00000000`0aa24920 00007ffa`4eb0b5fc : 00000000`0aa24bf0 00000000`0aa24a70 00007ff4`6a249770 00000000`0aa24a50 : rexx!RexxWaitForTermination+0x46451
00000000`0aa24970 00007ffa`4eb3705b : 00007ff4`6a249770 00000000`0aa24bf0 00007ff4`6a249270 00002313`1abef04e : rexx!RexxWaitForTermination+0x1462c
00000000`0aa249f0 00007ffa`4eb3f00b : 00007ffa`4eb3f5fa 00007ff4`6a248f70 00000000`0aa24bf0 00000000`0aa24bf0 : rexx!RexxWaitForTermination+0x4008b
00000000`0aa24aa0 00007ffa`4eb33246 : 00007ff4`6a248f70 00000000`0aa24bf0 00000000`00000001 00007ff4`6a2446d0 : rexx!RexxWaitForTermination+0x4803b
00000000`0aa24ae0 00007ffa`4eb38ad3 : 00007ff4`6a2446d0 00000000`0aa24bf0 00000000`00000002 00000000`00000001 : rexx!RexxWaitForTermination+0x3c276
00000000`0aa24b40 00007ffa`4eb498f1 : ad70c287`01d43ddf 00000000`01d43885 00000000`00000445 006f004d`6562336b : rexx!RexxWaitForTermination+0x41b03
00000000`0aa24b90 00000001`005fc51e : 00000000`0aa251a0 00000000`0000f000 00000000`0aa27568 00007ffa`81a670a0 : rexx!RexxStart+0xf1
00000000`0aa24c70 00000001`005fb1a5 : 00000001`00663c11 00000001`0067ac38 00000001`006f2030 00000000`0aa25180 : hengine!OORexxExecSub+0xce [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\hrexxapi.c @ 1037]
00000000`0aa25100 00000001`00422fe9 : 00000000`0aa27550 00000000`00000000 00000000`00000018 00000001`006f2030 : hengine!exec_cmd+0x595 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\hrexx.c @ 1752]
00000000`0aa25300 00000001`00423211 : 00000000`0aa27550 00000000`00000000 00000000`00000000 00000000`0aa27550 : hengine!CallHercCmd+0x2d9 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\cmdtab.c @ 359]
00000000`0aa254a0 00000001`00423f23 : 00000000`05e14d40 00000000`05e14d40 00000000`0aa27567 00000000`00000000 : hengine!DoCallHercCmdLine+0x61 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\cmdtab.c @ 414]
00000000`0aa27530 00000000`01991470 : 00000000`00000006 00000001`0064d300 00000001`0067fe40 00000001`007f34b0 : hengine!the_real_panel_command+0x223 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\cmdtab.c @ 828]
00000000`0aa2f580 00000001`0059c931 : 00000000`00000000 00000000`0aa2f6c0 00000001`0064d300 00000001`00400000 : dyngui!gui_panel_command+0x40 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\dyngui.c @ 550]
00000000`0aa2f610 00000001`0059c208 : 00000000`00000000 00000000`00000000 00000000`00000048 00000000`00000048 : hengine!hao_message+0x4b1 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\hao.c @ 822]
00000000`0aa2f900 00000000`017fff04 : 00000000`00000000 00000001`0001dd02 00000001`006f3010 00000000`00000000 : hengine!hao_thread+0x248 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\hao.c @ 637]
00000000`0aa2f980 00000000`017f3baa : 00000000`03195b40 00000000`00000000 00000000`00000000 00000000`6562336b : hutil!hthread_func+0x34 [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\hthreads.c @ 779]
00000000`0aa2f9b0 00000000`65622fdf : 00000000`040e94f0 00000000`00000000 00000000`00000000 00000000`00000000 : hutil!FTWin32ThreadFunc+0x5a [c:\users\fish\documents\visual studio 2008\projects\hercules\_git\_fish\hyperion-0\fthreads.c @ 787]
00000000`0aa2fa00 00000000`040e94f0 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : msvcr90+0x2fdf
00000000`0aa2fa08 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`65623080 : 0x40e94f0


SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  hostemu!unloaded+19e0

FOLLOWUP_NAME:  MachineOwner

IMAGE_NAME:  hostemu.dll

STACK_COMMAND:  ~13s; .ecxr ; kb

BUCKET_ID:  WRONG_SYMBOLS

FAILURE_BUCKET_ID:  INVALID_POINTER_READ_INVALID_c0000005_hostemu.dll!unloaded

Followup: MachineOwner
---------
```

**Comment by Fish-Git** [comment] 2018-09-04 18:06
. . .
```
FAULTING_IP: 
HOSTEMU+19e0
00007ffa`664619e0
```
. . .
```
STACK_TEXT:  
00000000`0aa24538 00007ffa`4eb7dc07 : 00000000`0aa24870 00000000`00000000 00000000`00000246 00007ffa`4eb7dbec : <Unloaded_HOSTEMU.DLL>+0x19e0
00000000`0aa24540 00007ffa`4eb3f0f4 : 00007ffa`4eb3f5fa 00007ffa`4eb2ee64 00000000`00000000 00007ff4`6a254fe0 : rexx!RexxDidRexxTerminate+0x33ce7
00000000`0aa24570 00007ffa`4eb2f4c2 : 00007ff4`6a254f10 00000000`0aa24660 00000000`00000001 00007ff4`6a254f10 : rexx!RexxWaitForTermination+0x48124
00000000`0aa245b0 00007ffa`4eb7df10 : 00007ff4`6a254e50 00000000`0aa24840 00000000`00000000 00000000`00000000 : rexx!RexxWaitForTermination+0x384f2
00000000`0aa245e0 00007ffa`4eb2e447 : 00007ff4`6a254650 00007ff4`6a254650 00007ff4`6a2446d0 00007ff4`6a2446d0 : rexx!RexxDidRexxTerminate+0x33ff0
00000000`0aa247f0 00007ffa`4eb2da73 : 00007ff4`6a24ef90 00007ff4`6a24ef90 00007ff4`6a254e50 00007ff4`6a249270 : rexx!RexxWaitForTermination+0x37477
00000000`0aa248b0 00007ffa`4eb3d421 : 00007ff4`6a254650 00007ff4`6a254650 00007ff4`6a2446d0 00007ff4`6a249770 : rexx!RexxWaitForTermination+0x36aa3
00000000`0aa24920 00007ffa`4eb0b5fc : 00000000`0aa24bf0 00000000`0aa24a70 00007ff4`6a249770 00000000`0aa24a50 : rexx!RexxWaitForTermination+0x46451
00000000`0aa24970 00007ffa`4eb3705b : 00007ff4`6a249770 00000000`0aa24bf0 00007ff4`6a249270 00002313`1abef04e : rexx!RexxWaitForTermination+0x1462c
00000000`0aa249f0 00007ffa`4eb3f00b : 00007ffa`4eb3f5fa 00007ff4`6a248f70 00000000`0aa24bf0 00000000`0aa24bf0 : rexx!RexxWaitForTermination+0x4008b
00000000`0aa24aa0 00007ffa`4eb33246 : 00007ff4`6a248f70 00000000`0aa24bf0 00000000`00000001 00007ff4`6a2446d0 : rexx!RexxWaitForTermination+0x4803b
00000000`0aa24ae0 00007ffa`4eb38ad3 : 00007ff4`6a2446d0 00000000`0aa24bf0 00000000`00000002 00000000`00000001 : rexx!RexxWaitForTermination+0x3c276
00000000`0aa24b40 00007ffa`4eb498f1 : ad70c287`01d43ddf 00000000`01d43885 00000000`00000445 006f004d`6562336b : rexx!RexxWaitForTermination+0x41b03
00000000`0aa24b90 00000001`005fc51e : 00000000`0aa251a0 00000000`0000f000 00000000`0aa27568 00007ffa`81a670a0 : rexx!RexxStart+0xf1
```
. . .
```
SYMBOL_NAME:  hostemu!unloaded+19e0
```
. . .
```
IMAGE_NAME:  hostemu.dll
```
. . .
```
FAILURE_BUCKET_ID:  INVALID_POINTER_READ_INVALID_c0000005_hostemu.dll!unloaded
```

&nbsp;

All of the above point to a bug in OORex's "hostemu.dll", not Hercules (famous last words!). It appears OORexx unloaded its "hostemu.dll", but then tried to call one of its functions afterwards.

Once a DLL has been unloaded/unmapped from a given process ("FreeLibrary" API), it cannot be used as the address space (virtual address range) it was originally loaded into is now no longer valid. As I said, this very much looks like an OORexx bug that Hercules just happened to trigger due to the way you are using rexx.

I'm _guessing_ it might have something to do with multi-threading. It might be that, due to your use of HAO (Hercules Automatic Operator) rules, your rexx script was invoked multiple times in rapid succession, and OORexx wasn't (isn't) prepared for that (i.e. EITHER OORexx can't handle being called by multiple threads at the same time (i.e. asynchronously), or else it has an unresolved race condition bug that we just happened to trigger).

I will _try_ to reproduce the error on my own system, but I cannot guarantee that I will be successful.

If I am unable to reproduce you crash on my own system, I'll see if maybe I can add some code to force all "RexxStart" calls to be synchronous to see if maybe that helps you or not.

Hang loose... I'm looking into it!

**Comment by Vf58** [comment] 2018-09-05 11:29
Hi Fish,

Sorry for this late answer, GMT+2 does not facilitate dialogs.
I'm embarrassed that you're wasting your time on an OOREXX bug.

I write a small Rexx named Test.rex and called when I enter "D T" command on the Z/OS console.

Hao tgt IEE136I
Hao cmd exec Test.rex

Test.rex:
/* REXX */

 parse arg parms

 parms = space(parms)
 argc  = words(parms)
if argc = 0 then Tot = 10
	    else Tot = word(parms,1)

deb = "------>"

Say deb 'Tot loop : ' Tot

do i = 1 to Tot
	say deb 'Loop ' i  "/" Tot
	call Syssleep 1
end
say deb 'end of Test'
exit 0

I enter several "!D T" and I see that the next rexx do not start before the previous one finished.
I run it many times without getting a crash.

Still searching an easy way ...

Best regards,

Philippe

**Comment by Fish-Git** [comment] 2018-09-07 00:08
Fixed by commit bd2a5ab03680afd16d9c3aa3ef8ba4536e49dc8f: "Work around rexx library loading/unloading race condition bug".

I'm afraid you will have to wait for the next Windows snapshot in order to get the fix, or else clone and rebuild Hercules for yourself.

Closing.

**Closed by Fish-Git** 2018-09-07 00:08 UTC
Labels: BUG, Researching...

**Comment by Fish-Git** [comment] 2018-09-07 00:40
> I run it many times without getting a crash.

That's because your test script is not using EXECIO, which requires the use of an extension DLL (i.e. contains a "::requires hostemu LIBRARY" statement). That is where the bug is: it's a race condition in OORexx:

1. Thread A begins. OORexx notices it requires "hostemu.dll", so it loads it.
2. Thread A begins executing its rexx script.
3. Thread B begins. OORexx notices it requires "hostemu.dll", but does NOT load it since it has already been loaded.
4. Thread A _finishes_ executing it rexx script, and OORexx _unloads_ "hostemu.dll".
5. Thread B begin executing its rexx script, and as soon as it reaches its "EXECIO" statement, it crashes because "hostemu.dll" has already been unloaded.

The fix (which has already been committed) is to _also_ load all of the available extension libraries at startup too, thereby preventing any of them from being "accidentally" unloaded due to rexx's library load/unload race condition bug.

_Technically_ the bug is _not_ within Hercules -- it is within OORexx.

But until it can be fixed (it has not even been reported yet) -- as well as to allow users to use older "broken" versions of rexx with Hercules -- the problem needs to be addressed. What I've committed is a workaround which effectively neutralizes the bug, making it harmless.

**Comment by Vf58** [comment] 2018-09-07 06:37
Thnank you FIsh for your work and the applied solution.
I'll try to copy last version of Hercules and rebuild it myself. A good exercice.

Best regards,

Philippe

**Comment by Fish-Git** [comment] 2018-09-07 19:01
Philippe has reported to me in an offline email:

> Hello Fish,
> 
> 
> I download last version of Hercules from repository  and generate Hercules under windows.
> 
> I run multiple OORexx using Execio and it run fine. No more crash.
> 
> Thank you for your help
> 
> Best regards,
> 
> Philippe
