### ISSUE TITLE
VM/370 virtual machine user using floating point gets math errors with ECPS:VM assist DISP2 active

### ISSUE THREAD

**Issue by wably** [SDL-Hercules-390/hyperion#382] opened 2021-03-25 14:49 UTC
When using floating point arithmetic in a VM/370 virtual machine, arithmetic errors are encountered with ECPS:VM active.  This has been narrowed down to the DISP2 assist specifically.  There is a flaw in the DISP2 code where it loads the floating point registers from the VMBLOK upon dispatch of the user.

Correcting the floating point register loads in `ecpsvm.c` (lines 1456-1467) resolves the issues.

This issue was recently reported on the groups.io VM message forum.

A fix and a commit will be coming soon.

**Comment by Fish-Git** [comment] 2021-03-25 21:29
Thank you for looking into this, Bob.

**Comment by wably** [comment] 2021-03-26 11:57
Fixed by commit 94129da

**Comment by RossPatterson** [comment] 2024-04-28 21:49
For those (like me) who need more context, the "_groups.io VM message forum_" thread is at https://groups.io/g/h390-vm/topic/81552953.

**Comment by RossPatterson** [comment] 2024-04-29 01:11
I know this issue is closed, but I'm researching a bug that, way down at its bottom, looks like, running VM/CE 1.2 in Hercules Hyperion 4.6 with ARCHLVL 370, FPR 4 is getting overwritten with the contents of FPR2, but not predictably.  And I'm seeing a mismatch in how `float.c` and `ecpsvm.c` use the `regs->fpr` structure.  For example, the implementation of the [Load Double Register (`LDR`) instruction](https://github.com/SDL-Hercules-390/hyperion/blob/master/float.c#L3488) does this to copy the source FPR to the destination FPR:

```c
    i1 = FPR2I(r1);
    i2 = FPR2I(r2);

    /* Copy register contents */
    regs->fpr[i1] = regs->fpr[i2];
    regs->fpr[i1+1] = regs->fpr[i2+1];
```

That `FPR2I` macro [will either copy the register number intact, or will double it, depending on whether something called `FEATURE_370_EXTENSION` is enabled at compile time or not](https://github.com/SDL-Hercules-390/hyperion/blob/master/opcode.h#L2081).

It's not clear exactly what that feature is, or how to tell if it was enabled in the [Hyperion 4.6 release binary I downloaded](https://github.com/SDL-Hercules-390/hyperion/releases/download/Release_4.6/Hercules-4.6.0.10941-SDL-g65c97fd6-x64.zip), but since it's described as ["_caus[ing] nonconformant/incorrect S/370 floating point behavior_"](https://github.com/SDL-Hercules-390/hyperion/blob/master/opcode.h#L2088), I assume it is not, and thus `FPR2I` does not double the register number. 

But the fix above to `ecpsvm.c` appears to presume that the register numbers should be doubled:

```c
        /* LOAD FPRS */
        regs->fpr[0] = EVM_L(vmb+VMFPRS+0);
        regs->fpr[1] = EVM_L(vmb+VMFPRS+4);
        regs->fpr[4] = EVM_L(vmb+VMFPRS+8);
        regs->fpr[5] = EVM_L(vmb+VMFPRS+12);
        regs->fpr[8] = EVM_L(vmb+VMFPRS+16);
        regs->fpr[9] = EVM_L(vmb+VMFPRS+20);
        regs->fpr[12] = EVM_L(vmb+VMFPRS+24);
        regs->fpr[13] = EVM_L(vmb+VMFPRS+28);
```

This would have exactly the effect I'm seeing - sometimes, FPR4 (`regs->fpr[4]` and `regs->fpr[5]` in `float.c`) gets set to the value in FPR2 (`VMFPRS+8` and `VMFPRS+12`, which is undisputed).  The "sometimes" part would be, whenever the `DISP2` ECPS instruction got invoked to dispatch the virtual machine.  On those occasions when the VM's code gets run without an untimely re-dispatch, the copy wouldn't happen and FPR4 wouldn't get damaged.

Am I missing something, or is there a bug in this fix?

**Comment by RossPatterson** [comment] 2024-04-29 02:13
Things are getting clearer.  Almost two years after commit 94129dac5914e8e78cfd7d1773850a1e01b4f9f4 above, the way the `regs->fprs` structure gets used was changed in Issue #546, and the definition of the `FPR2I` macro I mentioned was changed accordingly.  It appears the ECPS:VM DISP2 code was not changed, probably because it didn't use the macro in the first place.

**Comment by Rhialto** [comment] 2024-04-29 10:07
Does that mean that if this is fixed (presumably by introducing the use of `FPR2I` in the mentioned code in `ecpsvm.c `, that this is a "real fix" of what commit  https://github.com/SDL-Hercules-390/hyperion/commit/94129dac5914e8e78cfd7d1773850a1e01b4f9f4 is trying to fix, and the code/functionality that has been deleted there can be reinstated? Or do I misunderstand that?

**Comment by wably** [comment] 2024-04-29 13:01
Hi Ross,

It seems that you have found another issue with the DISP2 assist related to floating point.  I'm not presently sure exactly what #546 has to do with it since that is a display issue, but it does seem like I should have been using the FPR2I macro from the beginning.   I'll re-open this issue.

Unfortunately, for the next two weeks I really do not have the ability to look into this issue in any detail nor actually create a fix and commit it.  After that, I can fully dive into it.

In the meantime, if you find a solution you could post it here if you wish, and hopefully you are able to compile Hercules on your own machine so that you can use the code with the issue fixed. Because if not, it will be a long time before this fix reaches general use even if I fixed it today.  It likely will be months before Fish rebuilds the next release of SDL-Hyperion that would contain the fix, as he just recently did a rebuild.

Regards,
Bob

**Comment by mcisho** [comment] 2024-04-30 01:21
Floating point instructions are currently undergoing an overhaul. The fp registers will be stored as 64-bit values rather than the current two 32-bit values, and FPR2I no longer exists. The changes can all be found in the **sharedvfp** branch.

Regards,
Ian

**Comment by RossPatterson** [comment] 2024-04-30 03:07
> Floating point instructions are currently undergoing an overhaul. The fp registers will be stored as 64-bit values rather than the current two 32-bit values, and FPR2I no longer exists. The changes can all be found in the **sharedvfp** branch.

Nice!  And from a quick glance at https://github.com/SDL-Hercules-390/hyperion/blob/sharedvfp/ecpsvm.c#L1463, it looks like the questionable code in `ecpsvm.c` has already been changed to work with the new FPR model.

Thank you!

**Comment by wably** [comment] 2024-04-30 11:44
Ian,

The changes to ecpsvm.c to use the new floating point register notation looks good to me.  I like that it is now consistent with the same method used for the other registers.

May I close this issue then, knowing that the changes from the sharedvfp branch will eventually make their way into the develop branch?

Regards,
Bob

**Comment by mcisho** [comment] 2024-04-30 12:48
Hi Bob,

Yes, probably! Serious testing with the sharedvfp branch is only just starting, but so far it seems stable. It would be really helpful if you could run your VM system with the new branch, as you have the environment and you  know how to reproduce this problem.

Ian

**Comment by RossPatterson** [comment] 2024-05-01 13:59
@mcisho I have a mostly-reproducible test case, which I [described above](https://github.com/SDL-Hercules-390/hyperion/issues/382#issuecomment-2081742012).  I can provoke a detectable failure by using the VM/370 Community Edition's Virtual PER facility (the CP `PER` command) to trace the natural logarithm (`log()`) function of the GCCCMS runtime library when executing a Rexx program via the VM/370 CE `BRexx` interpreter.  The `log()` function uses 370-mode FPR4 as an accumulator in a loop, and the bad code overwrites FPR4 with the value of FPR2 occasionally.  Using PER to trace it forces the virtual machine to be undispatched and redispatched at every instruction in the loop, dramatically increasing the likelyhood that the code that damages FPR4 will be executed in that loop.

Running the Hyperion 4.6 Windows release binary, it fails over and over.  Disabling the DISP1 and DISP2 Extended Control Program Support: VM instructions (via `ecpsvm disable disp1 disp2`) makes the problem disappear, even in the intensive-PER case that usually provokes it reliably.  Running a `sharedvfp` binary that I built myself from the current source of that branch, even without disabling DISP1 and DISP2, does not demonstrate the problem.

Please understand that this problem has been hard to demostrate reliably, although I've gotten better and better at provoking failures in the weeks I've been investigating it.  My current technique with PER seems to provoke it at least 75% of the time on 4.6.

**Comment by Rhialto** [comment] 2024-05-01 14:26
It would be nice to have a patch of just the fixed FP registers, that can be applied to the latest release version. Then I can add it to pkgsrc so people will have a fixed version before the next release.

**Comment by RossPatterson** [comment] 2024-05-01 15:05
> It would be nice to have a patch of just the fixed FP registers

Once I'm certain of the fix, I intend to do so, for my own needs.  I'll post the patch here.

**Comment by mcisho** [comment] 2024-05-07 00:42
The floating point changes have been merged into the **develop** branch.

**Comment by RossPatterson** [comment] 2024-05-10 13:43
The updated `develop` branch has run my test case repeatedly without failure.  :-)

**Comment by RossPatterson** [comment] 2024-05-10 13:51
> It would be nice to have a patch of just the fixed FP registers, that can be applied to the latest release version. Then I can add it to pkgsrc so people will have a fixed version before the next release.

You can pull it from [my commit](https://github.com/RossPatterson/hyperion/commit/e66c96faa166ff1dca6ae34c264a35956431a5b4) to my `issue_382` branch on my fork.  I'll leave that fork around until the end of the month, but then I'm deleting it, 'cause I don't usually hack on Hercules.

**NOTE:** I would think very carefully about posting this change to a package manager's distrubution (like `pkgsrc`).  It has received minimal testing.  It works for me, and I spent a lot of time refining a test case that could isolate the failure and detect it reliably.  But it's still only been tested by me, and it affects every use of floating point math.

**Comment by RossPatterson** [comment] 2024-05-10 13:52
As @mcisho 's floating point changes are now on the `develop` branch, we should close this issue once again.

**Comment by mcisho** [comment] 2024-05-10 13:59
> The updated `develop` branch has run my test case repeatedly without failure. :-)

Thanks Ross, that's good to know.

**Closed as completed** 2024-05-10 15:50 UTC
Labels: BUG, Ongoing

**Comment by Rhialto** [comment] 2024-05-10 21:22
@RossPatterson Thanks, I saved the commit.

I kind of agree with your arguments about minimal testing. On the other hand, the existing situation is also doing an incorrect thing with floating point. So even if your patch is wrong, it is probably not more wrong than before :)
