### ISSUE TITLE
z/OS 2.5 missing facilities

### ISSUE THREAD

**Issue by gdelarey** [SDL-Hercules-390/hyperion#459] opened 2021-12-28 16:07 UTC
___
_**Note:** this issue is closely related to issue [\#77: "MISSING Facilities support"](https://github.com/SDL-Hercules-390/hyperion/issues/77)._
___
I tried an IPL of z/OS 2.5 on hercules (Hercules version **4.4.0.0-SDL-gbf377f63** (4.4.0.0)) and got an operation exception almost immediately.  Instruction trace shows it appears to occur following `STFLE` (see log1.txt):

* [log1.txt](https://github.com/SDL-Hercules-390/hyperion/files/7785411/log1.txt)

From https://www.ibm.com/docs/en/zos/2.5.0?topic=system-identifying-server-requirements, I found that required facilities:

* 80 Decimal-floating-point packed-conversion facility.
* 129 Vector facility for z/Architecture.

were missing, so I added them to my config:

* [sazos25a.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/7785439/sazos25a.cnf.txt)

On restarting, hercules reports:
```
 HHC00896E Facility( 080_DFP_PACK_CONV ) not supported for z/Arch
 HHC00896E Facility( 129_ZVECTOR ) not supported for z/Arch
```
as in the attached log2.txt:

* [log2.txt](https://github.com/SDL-Hercules-390/hyperion/files/7785463/log2.txt)

Could the facilities be enabled for z/Arch?  I am not familiar enough with the code to try, but I can apply patches and test.

**Comment by Fish-Git** [comment] 2021-12-28 17:58
> Could the facilities be enabled for z/Arch?

There currently is no support for either facility within Hercules. Such support hasn't been coded yet (i.e. support for either facility does not exist yet in the Hercules code base).

You _can_ forcibly enable any STFLE facility bit desired via the `facility enable nnn` syntax however (see "help facility"), so you might want to try that.

**Comment by Fish-Git** [comment] 2021-12-28 18:36
ADDITIONAL INFORMATION:

Entering the command "facility query all" lists the 080_DFP_PACK_CONV and 129_ZVECTOR facilities as:

<pre>
HHC00891I
HHC00891I                             z/Arch Facility Table
HHC00891I
HHC00891I           SRDC* = Supported, Required, Default, Current, Modified.
HHC00891I
HHC00891I Bit By Bi SRDC* Facility                    Description
HHC00891I --- -- -- ----- --------------------------- ---------------------------------------------------------
HHC00891I
...
HHC00891I  80 0A 80 --00  080_DFP_PACK_CONV           Decimal-Floating-Point-Packed-Conversion Facility
...
HHC00891I 129 10 40 --00  129_ZVECTOR                 Vector Facility for z/Architecture
...
HHC00891I
HHC00891I           SRDC* = Supported, Required, Default, Current, Modified.
HHC00891I
</pre>

Notice the "--00" in the "SDRC*" column for each. This means support for the facility does not currently exist in Hercules (i.e. the facility is currently not supported), which is why when you try to specifically enable it (by short name) it you get a "not supported" error message.

_However,_ Hercules does contain support for forcibly turning on any given facility bit via the aforementioned "enable bitnum" syntax:

<pre>
HHC01603I fac ena 80
HHC00898W Facility( 080_DFP_PACK_CONV ) *Enabled for z/Arch
HHC00007I Previous message from function 'facility_enable_disable' at facility.c(3948)
HHC01603I fac ena 129
HHC00898W Facility( 129_ZVECTOR ) *Enabled for z/Arch
HHC00007I Previous message from function 'facility_enable_disable' at facility.c(3948)
</pre>

which causes a warning message to be issued letting you know that you're enabling a facility that technically isn't supported. We provide such an ability so users can test whether a given OS's requirement for such facilities is an artificial or hard requirement. If it's an artificial requirement, the OS _might_ be able to run without it. But if it's a hard requirement, then it probably won't (since some facilities introduce new instructions which, if the OS attempts to execute, will immediately fail with an Operation Exception program interrupt due to the instruction(s) not existing yet in Hercules).

IBM is a multi-billion dollar corporation with the money and staff to introduce new z/Architecture facilities much faster than Hercules is able to react. The Hercules development team is actually quite small, and none of us are getting paid to work on it. Each of us only works on Hercules as we're able.

So if z/OS 2.5 does indeed have a hard requirement for those facilities in order to run, I'm afraid you're going to be in for a rather long wait, as it's obviously going to take _MUCH_ time and effort (and therefore a _long_ time) to get such facilities coded.

**Comment by gdelarey** [comment] 2021-12-28 18:51
Enabling the facility bits by number as you suggest moves things along a lot further.  Thank you!   What you guys do is awe-inspiring.

**Comment by Fish-Git** [comment] 2022-01-13 20:23
@gdelarey

> Enabling the facility bits by number as you suggest moves things along a lot further.

Yes, but does it move it along _enough_ is the real question. Does z/OS 2.5 now successfully IPL and start? Or are there additional "issues" (missing facilities and/or bugs, etc) that still need to be resolved?

I myself do not have z/OS 2.5, so I am unable to test.

**Comment by gdelarey** [comment] 2022-01-13 20:38
Sorry, I guess that was a bit of an understatement: indeed it does IPL successfully and everything I've tried runs fine -- TSO/ISPF, batch assemblies, C compiles, USS shell, basic developer stuff mostly, to do with the subset of the OS I normally use.  From what I've seen, hercules runs 2.5 perfectly.
  If you have anything you would like me to try, I would be very happy to help.

**Comment by ARandham** [comment] 2022-01-13 20:43
Fish,
By enabling those facilities, I was able to start z/OS 2.5 . 
I had to set DIAG8CMD to DISABLE to get past a wait state 19, and later on,  IZUSVR1 failed due to missing opcode(s) from 129_ZVECTOR namely E707 - Vector Load To Block Boundary.  
Besides that, it behaves normally.

**Comment by Fish-Git** [comment] 2022-01-13 21:02
> I had to set DIAG8CMD to DISABLE to get past a wait state 19 ...

_**Eh?!**_ &nbsp; How can `DIAG8CMD` cause a disabled wait 019?! Do you have a customized nucleus installed that issues `DIAG` instruction(s)?? If so, what diagnose instructions is it issuing??

> ... and later on, IZUSVR1 failed due to missing opcode(s) from 129_ZVECTOR ...

_THAT_ is something that likely will not be resolved for quite some time yet I'm afraid. &nbsp; `:(`

There are a _ba-zillion_ vector instructions and getting them all coded _(and tested!)_ is going to take quite a bit of time and effort. Unless of course we decide to maybe code support for only those specific instructions that guests such as z/OS actually _need?_ But then if we did that, we wouldn't be able to validly claim that the facility was officially supported either. &nbsp; `:(`

How important is IZUSVR1 to z/OS 2.5's usability?

**Comment by ARandham** [comment] 2022-01-13 21:17
> Eh?!   How can DIAG8CMD cause a disabled wait 019?!  Do you have a customized nucleus installed that issues DIAG instruction(s)??  If so, what diagnose instructions is it issuing??

Nucleus is stock. The ipl sequence went like this:-

21:29:35 HHC01603I ipl dca8
21:29:35 HHC00811I Processor CP00: architecture mode ESA/390
21:29:35 HHC00811I Processor CP01: architecture mode ESA/390
21:29:35 HHC00811I Processor IP02: architecture mode ESA/390
21:29:35 HHC00811I Processor IP03: architecture mode ESA/390
21:29:35 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 00000001: CC 0
21:29:35 HHC00811I Processor CP00: architecture mode z/Arch
21:29:35 HHC01950I Starting guest issued panel command: Q VCML RC
21:29:35 HHC01603I Q VCML RC
21:29:35 HHC01600E Unknown command Q, enter 'help' for a list of valid commands
21:29:35 HHC00007I Previous message from function 'DoCallHercCmdLine' at cmdtab.c(441)
21:29:35 HHC01950I Completed guest issued panel command: Q VCML RC
21:29:35 HHC00801I Processor CP00: Specification exception code 0006 ilc 4
21:29:35 HHC02324I CP00: PSW=0000100080000000 0000000000000920 INST=83080228     DIAG  0,8,552(0)             diagnose
21:29:35 HHC02326I CP00: R:0000000000000228:K:06=000A0000 00000019 00080000 80000B90  ................
21:29:35 HHC02269I CP00: R0=0000000000000000 R1=0000000000000020
21:29:35 HHC02269I CP00: R2=0000000020005000 R3=0000000000009000
21:29:35 HHC02269I CP00: R4=0000000020004000 R5=000000000000D000
21:29:35 HHC02269I CP00: R6=0000000000000000 R7=0000000000003000
21:29:35 HHC02269I CP00: R8=000000000000D168 R9=0000000000000024
21:29:35 HHC02269I CP00: RA=0000000000000590 RB=0000000000000599
21:29:35 HHC02269I CP00: RC=0000000000000000 RD=0000000000000000
21:29:35 HHC02269I CP00: RE=0000000000000000 RF=00000000000033F8
21:29:35 HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000000019

> How important is IZUSVR1 to z/OS 2.5's usability?

IZUSVR1 is the z/OSMF task, so it depends on who you ask I guess. For me, it's not that important.

**Comment by Fish-Git** [comment] 2022-01-14 03:52
Interesting! It looks like z/OS tried issuing a DIAG X'008' (Virtual Console Function):

```
21:29:35 HHC01950I Starting guest issued panel command: Q VCML RC
21:29:35 HHC01603I Q VCML RC
21:29:35 HHC01600E Unknown command Q, enter 'help' for a list of valid commands
21:29:35 HHC00007I Previous message from function 'DoCallHercCmdLine' at cmdtab.c(441)
21:29:35 HHC01950I Completed guest issued panel command: Q VCML RC
```

followed by DIAG X'228', which of course because it doesn't exist, caused a Specification exception, which is what I'm guessing is what lead to the disabled wait 19? Either that or possibly the fact that the DIAG X'008' (or possibly some other diagnose instruction?) actually _unexpectedly succeeded_ is what lead to the disabled wait 19??

I don't recall ever, _EVER_ having `DIAG8CMD` enabled for _any_ version of z/OS, and performing a spot review of a random selection of my Hercules log files for z/OS IPLs (any version), it looks like issuing one or more DIAG instructions (resulting in a specification exception) is a common part of a normal z/OS IPL.

Was there a reason you enabled DIAG8CMD, or was that just a simple typo/oversight?

**Comment by ARandham** [comment] 2022-01-14 09:39
> Was there a reason you enabled DIAG8CMD, or was that just a simple typo/oversight?

Just an oversight Fish. It crept into my config files a while ago and got propagated through cut/paste.

> There are a ba-zillion vector instructions.....

Heck, I've just taken a closer look at the PoPs manual and there must be over 100 new instructions covered in 5 chapters :(
This will be a massive undertaking if you decide to take it on!

**Comment by ssamayoa** [comment] 2022-05-29 22:57
I just got ADCD 2.5 and tried to IPL but got some messages I didn't understand, googled them until I found:

https://www.ibm.com/docs/en/zos/2.5.0?topic=wsc-07b

Then read a bit on facilities and finally saw this issue. I'm writing this comment while my system is IPLing and saw this message:

- 11.45.17 STC00033  JVMDUMP032I JVM requested System dump using
-  'IZUSVR.JVM.IZUSVR1.D22052
- 9.T164516.X&DS' in response to an event                            

IZUSVR1 as reported by @ARandham 
But the important thing here is that what seems affected is Java.

Nowadays I'm little busy but would like to help implementing such facilities.

**Comment by ssamayoa** [comment] 2022-08-17 03:28
I copied Java 1.8.0_221 from z/OS 2.4 to z/OS 2.5 expecting that older java binary (which runs on well in 2.4) not used the offending instruction (E707) but seems that what changes is not the java itself but some OS's service used by java.

Time to learn how Hercules is implemented and tested and implement that instruction.

**Comment by Fish-Git** [comment] 2022-08-18 02:41
> I just got ADCD 2.5 and tried to IPL but got some messages I didn't understand, googled them until I found:
> 
> * https://www.ibm.com/docs/en/zos/2.5.0?topic=wsc-07b

No need to Google for it if you have the latest IBM reference manual for your particular version of z/OS downloaded in .pdf format to your local system (which in this particular case is manual [SA38-0665-50 "z/OS V2R5 MVS System Codes"](https://www-40.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R5sa380665/$file/ieah700_v2r5.pdf)):

  * **[z/OS 2.5 Publications](https://www-40.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R5MvsPublications?OpenDocument)**

You probably don't need all of the listed manuals, but certainly having the latest and greatest of _some_ of them can prove to be quite handy.

Just trying to help!

**Comment by Fish-Git** [comment] 2022-08-18 02:43
> Time to learn how Hercules is implemented and tested then implement that instruction.

_**PLEASE!**_ &nbsp; We could use all the help we can get! &nbsp; `;-)`

**Comment by Fish-Git** [comment] 2022-08-21 23:12
Closing this topic for now. The solution, for now (until proper support for 129 = z/Arch Vector Facility is coded by someone), is to use the `FACILITY ENABLE bitnnn` format of the facility statement (e.g. `fac ena 129`).

**Closed as completed by Fish-Git** 2022-08-21 23:12 UTC
Labels: HELP!, Missing, Related, Ongoing

**Comment by Y-Innovate** [comment] 2022-09-24 18:27
Hi, for what it's worth: although z/OS 2.5 indeed IPLs with facilities 80 and 129 enabled, I ran into 0C1's when trying to debug some code with IBM Debug for z/OS. Was able to fix it though by adding dummy operations for vector_store_multiple VSTM (E73E) and vector_load_multiple VLM (E736). The Debugger is apparently fine once it thinks vector registers are being saved and restored. I doubt that would be the case for z/OSMF, but who knows someone else might run into something similar and come across this thread (like I did and learned about 80 and 129).
Cheers! Keep up the good work.

**Comment by Fish-Git** [comment] 2022-09-24 22:47
> I was able to work around the problem however by adding dummy operations for the `vector_store_multiple` (VSTM = E73E) and `vector_load_multiple` (VLM = E736) instructions.

Thanks, Bobby! &nbsp;That's good information to know!

**Comment by werner02815** [comment] 2022-12-20 13:41
Hi,
I want to bring up this topic again with some remarks and additional information:
- i can confirm that setting fac ena 129 allows z/OS2.5 to come up (hercules 4.5.0.10830 has already implemented facility 80, so no need to enable this)
- after enabling facility 129 i get wait state code 19 as already described in post from ARandham. i have DIAG8CMD enabled and need this because i am doing some operating system based automation and issuing hercules commands via this interface (issue AUTOMOUNT command). disabling (or better not enabling) DIAG8CMD allows z/OS 2.5 to successfully come up - but with limited functionaility because i need this DIAG8CMD interface
- i can confirm that java -version gives abend for java version 8, but e.g. java v7 succeeds. But of course that`s no solution, because this is a quite outdated version.

i am able to do any testing if required.
Thanks,
Werner

**Comment by Fish-Git** [comment] 2022-12-22 11:12
> Update on DIAG8CMD: enabling it at a later time (e.g. after NIP phase) works fine (means z/OS2.5 comes up and issuing commands is allowed).
> So it really seems to only be an issue in very first IPL phase

Thanks. Good to know. Maybe you can use an HAO rule to automate the enabling of it?

**Comment by desertwiz** [comment] 2023-01-01 22:21
Not sure why disabling DIAG8CMD matters, but it did allow 2.5 to come up mostly normal (with lots of address translation errors).  It works in native mode.  But the 7B returns when IPL-ing virtually under zVM 7.3.  Any ideas for workaround under zVM?

**Comment by PeterVels** [comment] 2023-01-01 23:06
The COBOL runtime also contains vector instructions, so even existing COBOL programs (compiled on previous releases of z/OS) might not run.   Submit the attachment to reproduce.
[COBS0C1.JCL.txt](https://github.com/SDL-Hercules-390/hyperion/files/10329616/COBS0C1.JCL.txt)

**Comment by werner02815** [comment] 2023-01-02 13:18
> The COBOL runtime also contains vector instructions, so even existing COBOL programs (compiled on previous releases of z/OS) might not run. Submit the attachment to reproduce.
> 
> * [COBS0C1.JCL.txt](https://github.com/SDL-Hercules-390/hyperion/files/10329616/COBS0C1.JCL.txt)

i can recreate on my image (and confirm it`s running on "real z/OS". I see similar problem also with e.g. IBM product "DB2 administration tool V12" - also getting abend with z/OS 2.5 running on hercules (and suceedinig with e.g. z/OS 2.4).

**Comment by syspmk** [comment] 2024-02-13 11:43
I am trying to install zos 3.1 from zosmf (IZUSVR1) procedure wich  failed to start because of  java 8 based on 
https://github.com/SDL-Hercules-390/hyperion/issues/459#issuecomment-1217417310

r there any work around to start izusvr1

**Comment by Fish-Git** [comment] 2024-02-13 15:51
Not at this time, no.

**Comment by ssamayoa** [comment] 2024-02-13 16:21
> I am trying to install zos 3.1 from zosmf (IZUSVR1) procedure wich failed to start because of java 8 based on [#459 (comment)](https://github.com/SDL-Hercules-390/hyperion/issues/459#issuecomment-1217417310)
> 
> r there any work around to start izusvr1

Even tho you manage to install z/OS above version 2.4 is very likely will be unusable because vector facility seems to be used to implement system facilities. Why I guess that? Because I took Java 8 binaries from 2.4 to 2.5 and it failed to just run "java -version"

I recall read that Jay Maynard is implementing, in a fork, some of vector instructions to be able to run zLinux.

**Comment by Fish-Git** [comment] 2024-02-13 22:02
> Even tho you manage to install z/OS above version 2.4 is very likely will be unusable because vector facility seems to be used to implement system facilities.

That's not _completely_ true, Sergio.

While it _may_ be true that z/OS uses vector facility instructions in _some_ of its system facilities (most probably related to java), it most certainly is _NOT_ true that z/OS 2.5+ would therefore be unusable.

How usable z/OS 2.5+ is to a user depends on what type of things (tasks) they typically need to do on their z/OS system. If you need java _(which yes, I am told that z/OSMF does use)_, then yes, you will probably not be able to do what you want to do with z/OS 2.5+ on Hercules.

_IF HOWEVER_, you do not need to use java (i.e. if you only plan to use the rest of z/OS, e.g. edit files, submit jobs, use FTP, etc), then z/OS 2.5+ is quite usable on Hercules. I myself have been using z/OS 2.5 for the past 1.5 years without any problems whatsoever.

So as I said, if you _must_ have java (e.g. z/OSMF), then yes, trying to use z/OS 2.5+ on Hercules is not going to work for you.

But if you _don't_ need java, then z/OS 2.5+ on Hercules runs great!

I just wanted to make that clear.

**Comment by syspmk** [comment] 2024-02-13 22:07
Thanks a lot for your, I do use ZOS 2.5 From last June after installing 3.1 , I will dump it to Hercules and let you know

Thanks
Mohamed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ssamayoa** [comment] 2024-02-14 00:07
> 
> That's not _completely_ true, Sergio.
> 
mmm... not only java is affected, has been reported that COBOL runtime uses vector instructions, also DB2 utilities (not sure if native or Java based but very likely former) wont work.

So,
> is very likely will be unusable
Will depend on how much core OS services were refactored to use vector instructions, at this moment we have no idea how many old programs are affected because those OS services.

**Comment by Fish-Git** [comment] 2024-02-14 05:17
> So my statement that:
> 
> > is very likely will be unusable
> 
> depends on how many of the core OS services were refactored to use vector instructions, so at the moment we have no idea how many old programs are affected because of those refactored OS services.

Quite true. Quite true. It's not _just_ java that is affected. Thank you for pointing that out.

But all I was _trying_ to say was, if you don't care about those things, then z/OS 2.5+ runs perfectly fine under Hercules. But if you do care about z/OSMF, COBOL, DB2 utilities, etc, then yes, z/OS 2.5+ under Hercules will very likely be unusable to you.

I hope that's clear now?

**Comment by Vf58** [comment] 2024-04-10 09:57
@ssamayoa  

DId you solve the disable state 07C ?
I get a 07C with reason code 0A a IPL
[07C.txt](https://github.com/SDL-Hercules-390/hyperion/files/14930605/07C.txt)

Diag8cmd is desable and I ipl Natively

Vincent

**Comment by gdelarey** [comment] 2024-04-10 11:52
I can confirm this sequence of abends ending with the specification exception on the SVS set_vector_summary instruction and disabled wait state ...0A007C occurs with z/OS 2.5 from ADCD Z25C and later, although Z25B and earlier work fine (ignoring java issues).

**Comment by Fish-Git** [comment] 2024-04-10 12:25
As long as you forcibly enable facility 129, then z/OS 2.5C should IPL just fine.

**Comment by desertwiz** [comment] 2024-04-10 16:51
Morning All.

2.5 definitely comes up fine natively and under z/VM.  

I had a plan to bring Java and Language Environment

from 2.4 over to see if I can get those functions working.

If anyone has tried this, please comment.

zN

**Comment by Vf58** [comment] 2024-04-11 12:29
I Check the Z/OS 2.5 (Not ADCD) with a maintenance level Mid 2022, it's working fine
The same configuration with maintenance level mid 2023 and I get disabled wait state ...0A007C

**Comment by Fish-Git** [comment] 2024-04-11 14:12
> I can confirm this sequence of abends ending with the specification exception on the SVS set_vector_summary instruction and disabled wait state ...0A007C occurs with z/OS 2.5 from ADCD Z25C and later, although Z25B and earlier work fine (ignoring java issues).

The specification exception on the `SVS` `set_vector_summary` instruction during IPL has nothing to do with the disabled wait failure you are getting. z/OS always gets that during an IPL, as well as for several other instructions too.

**Comment by gdelarey** [comment] 2024-04-11 14:54
And here are the config and log for z/OS 2.5B, which works.
[sazos25b.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/14947787/sazos25b.cnf.txt)
[zos25b.log](https://github.com/SDL-Hercules-390/hyperion/files/14947788/zos25b.log)
Let me know you if I can help with any more details.

**Comment by Vf58** [comment] 2024-04-11 14:58
Indeed, the set_vector_xxx gives a disabled wait 022007B or 023007B.
0A007C is "The system was IPLed from an unsupported virtual machine environment.".

I found those ptf's which are not on my early 2.5 but well on the later one and affecting the bootstrap.

https://www.ibm.com/support/pages/apar/OA62783
https://www.ibm.com/support/pages/apar/OA65014

I suspect the first one is responsible for the disabled wait .0A007C

**Comment by syspmk** [comment] 2024-04-11 15:01
Hi

Fyi, Concerning Java it had an issue running on zos 2.5 in Hercules.

If you have a solution kindly share it

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fish-Git** [comment] 2024-04-11 15:03
#### _General FYI regarding email replies:_

I would very much appreciate it if you would _**not**_ respond/reply to GitHub Issues via email.

I would much prefer that you instead respond/reply _directly_ via the GitHub Issues web page itself:

* **[ht<span>tps</span>://github.com/SDL-Hercules-390/hyperion/issues/XXX](https://github.com/SDL-Hercules-390/hyperion/issues/XXX)**

When you reply **directly** via their web page, I can make minor edits to your reply so it is more readable (prettier) by editing the fonts being used, formatting of log messages, etc.

When you reply via email however, I cannot edit your reply (GitHub does not allow it), so oftentimes it is much harder (more difficult) to read.

GitHub also does not allow attachments in their email replies either, making it impossible to receive a file that may have been requested from you.

It is up to you whether or not you want to take the time to reply via their web page or continue to reply via email, but it is generally preferable that you reply directly via their web page instead. Especially if you need to attach a file that was requested from you.

Thanks for understanding.
