### ISSUE TITLE
Local 3270 read modified command returns invalid data

### ISSUE THREAD

**Issue by mtalexander** [SDL-Hercules-390/hyperion#380] opened 2021-03-24 05:39 UTC
The "read modified" channel command for a locally attached 3270 should never return fewer that 3 bytes of data (an AID character and two bytes of cursor location) as per GA23-0060-0.  However in some cases Hercules is returning zero bytes for a read modified.  Since no real 3270 ever does this some host software may not deal with it well.  In particular, the OPERATOR task in MTS crashes if it gets such a buffer.  This could be fixed, of course, but not easily since those with the D6.0 version of MTS have no way to rebuild the OPERATOR job.  It would be better to fix Hercules to not do this.

Here's what I know about the problem so far, I'll keep looking and add more here if I learn anything.

This was first reported by Matteo Panella who was running D6.0 MTS in Hercules 4.2 (precise version unspecified) on a Windows machine (unspecified version) using Vista TN3270.

It also happened to me running version **4.4.9999.0-SDL-gde7e7931** (4.4.9999.0) on MacOSX Mojave on an iMac using Zoc.

Since it happens in two such radically different environments, it doesn't seem too likely that it is a problem in the external environment.  In both environments it is a rare event so there must be some timing related aspects to it.

Matteo Panella did the work to bisect down to the commit that causes the problem which is [**a84107e7**](https://github.com/SDL-Hercules-390/hyperion/commit/a84107e78c6482cc86b3bc6347c76a416c6c45b7) dated _Jun 28, 2019_.  I see that this commit makes significant changes related to deciding when to return an AID.  There must be some case in which it decides not to do so when it should.

The log and config file for my crash are attached.  I also have the MTS job dump, but it is unlikely to be useful.

* [Archive.zip](https://github.com/SDL-Hercules-390/hyperion/files/6194655/Archive.zip)

**Comment by Fish-Git** [comment] 2021-03-24 13:44
> The "read modified" channel command for a locally attached 3270 should never return fewer that 3 bytes of data (an AID character and two bytes of cursor location) as per GA23-0060-0.

_Almost_ true. The actual minimum appears to be one byte:

> (Page 3-6):
>
> _**Short Read**. The Read Modified command causes a short read operation if the CLEAR,_
> _CNCL, or a PA key has been pressed at the selected device.  During the Short Read_
> _operation, only an AID byte is transferred to main storage.  This AID byte identifies the_
> _key that was pressed._

_But ..... **Your point still stands:**_ Hercules should _not_ be returning 0 bytes in response to a Read Modified CCW command.

Either I or Jürgen himself _(or someone else on the team!)_ will try to look into this issue as soon as we get a chance. Thank you for reporting it Mike.

**Comment by Fish-Git** [comment] 2021-03-24 13:49
p.s. I'm not seeing any type of "crash" in your [attached Hercules logfile](https://github.com/SDL-Hercules-390/hyperion/files/6194655/Archive.zip).

Also, have you tried doing a CCW trace on the terminal in question? (i.e. `t+nnn` where 'nnn' is the device address of the terminal exhibiting the problem) Providing such a trace would be very helpful with trying to debug this problem. Thanks.

**Comment by Juergen-Git** [comment] 2021-03-24 14:23
Well, I know, there is (too?) much AI (aka heuristics) in console.c. IIRC, the particular commit mentioned, and a few others I made around that time frame, made in particular JES3 consoles happy -- they had various problems before that series of commits. But it's quite a while since then, so I cannot reproduce all the dirty details from memory. It will take a while until I can revisit the topic, given that I'm completely absorbed with other things currently. For the time being, I recommend implementing a local circumvention.

One problem with general solutions in that area is, that one must re-test all operating systems our users are using: From the oldest systems from the '70s to the current z based systems. And that on all host platforms we are supporting: Sheer horror -- I'm speaking from experience ;-)

**Comment by mtalexander** [comment] 2021-03-25 05:16
I should have said that read modified returns at least 3 bytes in most cases and one byte in a few cases.  Regardless of that zero bytes is invalid and doesn't occur on real 3270s.  That's the main point.

There was no Hercules crash.  The OPERATOR task in MTS crashed and I have the dump for it (but I doubt that you want it).  Hercules (and MTS) kept running.  When I restarted the OPERATOR job things went back to normal.

I don't have a CCW trace.  This has happened only once for me in several days of MTS usage.  I could turn on CCW tracing routinely when running MTS but I haven't so far.  

I'm quite sure that the immediate cause of the OPERATOR jobdump is a zero length read modified.  The dump occured because the code that handles the response from Read Modified crashed on exit.  It crashed because register 9 was invalid.  This register is set when the AID byte is processed in the read result.  Furthermore register 5 contains the total number of bytes processed in the read modified result and it is zero.  The combination of bad R9, zero R5, and crash at that location points pretty strongly to a zero length result from read modified.  I can't think of any other explanation.

**Comment by Fish-Git** [comment] 2021-03-25 21:27
> I don't have a CCW trace. This has happened only once for me in several days of MTS usage. I could turn on CCW tracing routinely when running MTS but I haven't so far.

Don't bother. It sounds like there is no real need. What you say next (reproduced below) is evidence enough of what is going on:

> I'm quite sure that the immediate cause of the OPERATOR jobdump is a zero length read modified. The dump occured because the code that handles the response from Read Modified crashed on exit. It crashed because register 9 was invalid. This register is set when the AID byte is processed in the read result. Furthermore register 5 contains the total number of bytes processed in the read modified result and it is zero. The combination of bad R9, zero R5, and crash at that location points pretty strongly to a zero length result from read modified. I can't think of any other explanation.

Thank you, Mike. As I said, either I or Jürgen will look into this issue as soon as one of us gets a chance (which, unfortunately, may still be a while yet, as we are both completely absorbed with something else right now).

I also agree with Jürgen that implementing a local circumvention is the best approach to take for the time being.

**Comment by mtalexander** [comment] 2021-03-25 23:53
On 25 Mar 2021, at 17:27, Fish-Git wrote:

> Thank you, Mike. As I said, either I or Jürgen will look into this 
> issue as soon as one of us gets a chance (which, unfortunately, may 
> still be a while yet, as we are both completely absorbed with 
> something else right now).
>
> I also agree with Jürgen that implementing a local circumvention is 
> the best approach to take for the time being.

That sounds fine.  I was mainly trying to document this so it doesn't 
get lost.  I'll fix the OPERATOR job to avoid the crash and carry on 
with my MTS work.

**Comment by joemonk64** [comment] 2021-04-29 11:41
This  may not  be an invalid condition, as it seems to be possible with a 3274-1D.

http://www.bitsavers.org/pdf/ibm/3274/GA23-0061-2_3274_Control_Unit_Description_and_Programmers_Guide_Mar85.pdf says (page 1-48):

"During 3274 B and D unit operations, if the channel byte count reaches zero before all modified data is transferred, read operations are terminated and the remaining modified data is not transferred. The buffer address after termination is undefined."

console.c defines the  control unit used in hercules as a 3274-1D.  So, it's very possible that this condition could have happened, and would have caused the condition  seen by  MTS.

I would note  that it seems this is peculiar to the  3274-1D, which is why the manual Mike pointed to doesnt have it.

**Comment by Fish-Git** [comment] 2021-04-29 16:28
> I would note that it seems this is peculiar to the 3274-1D, which is why the manual Mike pointed to doesn't have it.

Actually it's not and it does (but it's on page 3-6), and the wording is _identical_ too.

But I don't think that's the problem/bug that Mike was describing. Unless I'm mistaken, his code was issuing a read-modified command for greater than 0 bytes, but Hercules was returning 0 bytes instead, which is wrong.

For _any_ read-modified command, there should _always_ be _at least **three** bytes_ available for transfer, even if no fields on the screen have been modified: the AID key and the 2-byte cursor address. I believe _THAT_ was Mike's point.

**Comment by joemonk64** [comment] 2021-04-29 17:48
> For any read-modified command, there should always be at least three bytes available for transfer, even if no fields on the screen have been modified: the AID key and the 2-byte cursor address. I believe THAT was Mike's point.

I understand. But from the description in the manual, the transfer was aborted by the channel, and so nothing was transferred, resulting in  0 bytes.  Thats MY point.

"This read operation can also be terminated by the channel byte count reaching zero **before all data is read**; in this case, the buffer address after termination is undefined."

**Comment by Fish-Git** [comment] 2021-04-29 21:24
> But from the description in the manual, the transfer was aborted by the channel, ...

Huh? How did you determine that? Mike never said anything about his I/O failing. All he said was that it returned 0 bytes. If there was an I/O error I am sure he would have said so, so I can only presume that it was a successful I/O (i.e. the unit-status and channel-status in the CSW was a normal CE+DE = X'0C00'), but was one in which the residual indicated zero bytes were actually transferred. Mike? (@mtalexander) Is this correct?

But in any case, _my_point is: "the description in the manual" does _not_ determine whether a transfer _**was**_ aborted by the channel. The "manual" (depending on which one you are referring to) may _describe_ certain conditions which, if/when they actually occur, might cause a data transfer to abort, but just because such a condition is _described_ in the manual does not determine whether said condition _**actually occurred or not**_ during an actual run of your program!

Mike? (@mtalexander) Did you ever do a CCW trace like we asked? We need to _confirm_ your claim. As just explained to Joe, we are _"presuming"_ that your I/O was successful. But if it wasn't, if there was indeed an I/O error, then Joe's point would certainly explain why you might end up receiving zero bytes on your I/O. Otherwise it doesn't, and Hercules does indeed contain a bug (which is what I'm presuming), so completing a CCW trace is very important  here! Can you do that for us please? So we can actually _**see**_ the problem (bug) actually occurring? Thanks!

**Comment by Fish-Git** [comment] 2021-08-02 19:34
Closing due to lack of response. Feel free to re-open should more solid/conclusive evidence be obtained.

**Closed as completed by Fish-Git** 2021-08-02 19:34 UTC
Labels: Researching..., Unknown
