### ISSUE TITLE
LCS devices hang when using TLS

### ISSUE THREAD

**Issue by PeterVels** [SDL-Hercules-390/hyperion#539] opened 2023-01-23 07:58 UTC
LCS devices (e.g. devices E20 and E21) suddenly become inoperable. Attempting to detach them (including at Hercules shutdown ("exit" command)) hangs Hercules.  Attempting to do anything TCPIP-related fails. It seems the devices are dead and cannot be recovered. After Hercules is restarted, everything is fine again.

**The problem is consistent and repeatable.**

**Hercules:** version 4.5.0.10830-SDL-g58578601 &nbsp;_(official 4.5)_
**Host OS:** Windows 64-bit
**Guest OS:** z/OS 2.4 winter ADCD

Hercules configuration and log files attached:

* [z24_config.txt](https://github.com/SDL-Hercules-390/hyperion/files/10477607/z24_config.txt)
* [z24_config DASD.txt](https://github.com/SDL-Hercules-390/hyperion/files/10477608/z24_config.DASD.txt)
* [Hercules-log-20230123-144450.txt](https://github.com/SDL-Hercules-390/hyperion/files/10477621/Hercules-log-20230123-144450.txt)

TCPIP.PROFILE data set attached:

* [TCPIP.PROFILE.txt](https://github.com/SDL-Hercules-390/hyperion/files/10477602/TCPIP.PROFILE.txt)

_**Prerequisite:**_ Configure the TN3270 started task to use TLS authentication.    I realise this is not a trivial exercise, so if you have not (yet) done this then setting it up will take some configuring.    I am happy to do experiments on your behalf.

_**To re-create:**_  Paste half a page of text into a 3270 emulator edit session (e.g. in ISPF option 2). The paste appears to work, that is, the text appears in the emulator window as expected, but then all emulator sessions that are connected to guest port 2023 (the TLS one) are frozen.  Other non-TLS emulator sessions are unaffected (because they are connected to port 3270 on 127.0.0.1).  Both IBM PCOMM and TN3270 Vista sessions are disconnected, so I doubt this is related to the emulator itself.  All other TCPIP-related activity (ping, tracert, etc) fails because the devices are now dead. Unsurprisingly, restarting TCPIP does not help. Attempting to detach the devices hangs Hercules.

Pasting half a page of text into a non-TLS 3270 emulator edit session (i.e. connected to port 3270 on localhost 127.0.0.1) works fine, and continues to work fine even if the TCPIP devices (LCS) are dead.

I expect someone will tell me to enter commands like **ptt** and **t+e20** .  I'm happy to do that, but won't pretend to understand the output.

Note that there are other scenarios (e.g. using FTP) that also hang LCS, but I have not found a way to consistently reproduce them.

**Comment by Fish-Git** [comment] 2023-01-23 21:47
Hi Peter!

Do you have Large Send Offloading (sometimes called Segmentation Offloading) or Jumbo Frames enabled on your Windows host adapter? (that CTCI_WIN/Hercules is using) What about Checksum Offloading?

I would like to see a Wireshark trace of everything passing through your Windows host adapter (i.e. the one that CTCI-WIN/Hercules is using for your LCS device) from shortly before you connect your TLS-enabled TN3270 session to port 2023 until shortly after the problem occurs.

Have you tried this on real iron? I am not familiar with your TCPIPPROFILE "TTLS" statement. Are you sure you have it configured right? I noticed port 2023 is nowhere in your list of ports. Whether that's a problem or not I do not know. I've only ever used local 3270 devices, where my TN3270 clients always connect to Hercules, not directly to the guest. I've never connected a TN3270 client directly to z/OS before, so I don't know how that works. I presume you simply connect to your TN3270 client to your z/OS guest's IP address at port 23 instead? (i.e. your guest's "TCP TN3270" Telnet Server port?)

Does it only happen when you paste a "half page" (largish amount?) into your 3270 terminal? Or does it happen when _any_ amount pasted? (I'm trying to determine whether "half page" is significant or not.)

Preliminary suggestions:

1. Disable Large Send/Segmentation Offloading and Jumbo Frames support on your Windows adapter if they're currently enabled, and try again. It's entirely optional whether or not you want to also disable Checksum Offloading or not too. To eliminate it as a possibility I personally would. It can always be re-enabled later once we find out what's going on.

2. Determine whether not having port 2023 in your TCPIPPROFILE is important or not. Maybe you just need to add it to the list the same way port 23 is currently defined in the list? (i.e. as TCP TN3270?)

3. Do a Wireshark packet capture trace on your Windows host adapter so I can see if maybe there might be any CTCI-WIN considerations I might need to take into account.

In the mean time I will try to learn what the "TTLS" statement in your TCPIPPROFILE means. If there's any IBM documentation you can point me to to help me understand what's involved in providing TLS support in z/OS, I'd appreciate that. Thanks.

> I expect someone will tell me to enter commands like **ptt** and **t+e20** . I'm happy to do that, but won't pretend to understand the output.

You need not concern yourself about that. If we do eventually need you to so a `ptt` trace _(and we might!)_, it's only important that _WE_ understand the output, not you. &nbsp; `;-)`

But I don't think we need to do that yet.

**Comment by PeterVels** [comment] 2023-01-23 23:00
Jumbo Packet is disabled.
![Jumbo Packet setting](https://user-images.githubusercontent.com/55377655/214165781-e846b11f-1147-415d-9d36-d6c7f1c6d651.jpg)

The only "offload" settings I can see are Protocol ARP Offload and Protocol NS Offload and both are disabled.

>Have you tried this on real iron?
Yes. No issues.

I doubt port 2023 is a problem, because I can run for hours using it, and it will be fine as long as I remember to avoid pasting anything (not easy!)  I **can** paste a small amount f data (e.g. one word) into the session and survive.  However, I **will** add it to the TCPIPPROFILE data set.

>I presume you simply connect to your TN3270 client to your z/OS guest's IP address at port 23 instead? (i.e. your guest's "TCP TN3270" Telnet Server port?)

Yes, correct. I've set up TN3270 to use port 23 for non-TLS and port 2023 for TLS.  This is pretty standard.

Regarding TTLS: https://www.ibm.com/docs/en/zos/2.4.0?topic=protection-tls-configuration-in-profiletcpip

Wireshark capture: 
[packet capture 2023-01-24_08.56.zip](https://github.com/SDL-Hercules-390/hyperion/files/10484293/packet.capture.2023-01-24_08.56.zip)

**Comment by PeterVels** [comment] 2023-01-23 23:16
I added port 2023 to the TCPIPPROFILE data set (and re-IPL'd).  It made no difference - still fails if I paste half a page of text into the editor.

**Comment by Fish-Git** [comment] 2023-01-24 01:08
> Jumbo Packet is disabled.

> The only "offload" settings I can see are Protocol ARP Offload and Protocol NS Offload and both are disabled.

Intel is infamous for forcing certain adapter settings on you, since in their mind, "Why would you _not_ want to have offload _&lt;such-and-such&gt;_ enabled?!".

Try enabling their "Legacy Switch Compatibility Mode", which I'm hoping will disable most modern offloads.

> I _can_ paste a small amount of data (e.g. one word) into the session and survive.

Then it sounds to me like it's a Large-Send / Segmentation Offload issue. If you paste lots of data, the packets that get transmitted between your Windows host and CTCI-WIN are more than likely _(just a guess at this point)_ too large for it to handle. When you past only a small amount of data on the other hand, it all fits into one standard sized Ethernet frame and there's no problem. CTCI-WIN can handle it fine. That's why Large-Send / Segmentation Offloading needs to be disabled. This is a well known issue.

> Regarding TTLS: https://www.ibm.com/docs/en/zos/2.4.0?topic=protection-tls-configuration-in-profiletcpip

Thanks. I'll take a look at it.

> Wireshark capture:
> 
> * [packet capture 2023-01-24_08.56.zip](https://github.com/SDL-Hercules-390/hyperion/files/10484293/packet.capture.2023-01-24_08.56.zip)

Thanks. I'll take a look at this too.

**Comment by Fish-Git** [comment] 2023-01-24 02:15
If you have a different network adapter (preferably non-Intel and preferably and older much simpler one) that you can experiment with, I suggest that. I downloaded the only manual I could find from Intel's own web site for the "Intel 82579LM Gigabit" adapter, and it _**sucks!**_  _(It doesn't have Table of Contents **nor** even an Index either!! Sheesh!)_

It looks like the only way to configure it is via their "ProSet" software.

Hardware manufacturers are the worst. They may know hardware, but when it comes to writing software -- especially Windows software -- they absolutely SUCK at it. &nbsp; `:(`

I've given your Wireshark packet capture a look-see and I'm seeing many TLS packets with invalid checksums. Haven't figured out yet how to ask Wireshark to show me just the large segmentation offloaded packets (if any), if that's even possible. _(I hate Wireshark almost as much as I hate gcc. Yeah, I'm a grouchy old man. I admit it.)_

**Comment by PeterVels** [comment] 2023-01-24 02:19
I enabled "Legacy Switch Compatibility Mode", and rebooted my Windows machine.  Sadly, it made no difference.

**Comment by Fish-Git** [comment] 2023-01-24 02:26
> I enabled "Legacy Switch Compatibility Mode", and rebooted my Windows machine. Sadly, it made no difference.

Oh well. It was worth a shot. &nbsp; `:(`

I greatly fear you _may_ be S.O.L. &nbsp; `:(`

Neither Hercules _nor_ my CTCI-WIN supports encrypted connections. What's got me confused though is your claim that pasting only small amounts of data _works!_ I just don't understand that! Why would it work fine for small amounts of data but not for larger amounts? That's why I'm suspecting Segmentation Offloading. I'm obviously missing something somewhere, but I can't for the life of me figure out what that something is. &nbsp; `:(`

**Comment by PeterVels** [comment] 2023-01-24 03:07
> What's got me confused though is your claim that pasting only small amounts of data works!
Strange, but true.  I'm thinking there is some threshold beyond which it fails. Discovering the exact threshold would be trial and error - somewhat painful, as each failure requires a re-IPL.

As I type this, I have an edit session open in a 62x160 emulator session. It happens to be Tom Brennan's Vista T3270. There are 152 visible columns in the editor.   I successfully pasted 2 full lines of numbers 304 bytes .  I will try adding one line at a time to the clipboard, and pasting that until it dies.....

(A few minutes later).   I was able to paste up to 8 lines of text into the editor OK.  A subsequent attempt to paste 9 lines caused the failure.   So pasting 1216 bytes is OK, but 1368 is not.

**Comment by Fish-Git** [comment] 2023-01-24 03:48
> So pasting 1216 bytes is OK, but 1368 is not.

That sure sounds to me like a [Large Segment Offloading](https://en.wikipedia.org/wiki/TCP_offload_engine#Large_send_offload) issue to me!

> _For example, a unit of 64 KiB (65,536 bytes) of data is usually segmented to 45 segments of 1460 bytes each before it is sent through the NIC and over the network. With some intelligence in the NIC, the host CPU can hand over the 64 KB of data to the NIC in a single transmit-request, the NIC can break that data down into smaller segments of 1460 bytes, add the TCP, [IP](https://en.wikipedia.org/wiki/Internet_Protocol), and data link layer protocol headers — according to a template provided by the host's TCP/IP stack — to each segment, and send the resulting frames over the network. This significantly reduces the work done by the CPU._

You _REALLY_ need to find out how to disable that on your adapter!!

**Comment by PeterVels** [comment] 2023-01-24 04:30
> That sure sounds to me like a [Large Segment Offloading](https://en.wikipedia.org/wiki/TCP_offload_engine#Large_send_offload) issue to me!

OK, but why would it fail when using TLS, and not fail when not using TLS?

>Neither Hercules nor my CTCI-WIN supports encrypted connections.

Maybe that's the problem.  However, I can happily transfer large files using TLS in Total Commander. Surely if Large Segment Offloading were broken then I wouldn't be able to?

**Comment by mcisho** [comment] 2023-01-24 12:41
Have you tried another TN3270 client? I can't remember the exact details at the moment, and I don't have the computer to hand to check, but I had to download a newer, not publicly available, version of Vista when I needed to use TLS. The newer version works fine with TLS, but lost some features with non-TLS, which is why it wasn't publicly available. As I said, I don't remember the details.

**Comment by PeterVels** [comment] 2023-01-24 13:13
> Have you tried another TN3270 client?

Yes.  IBM PCOMM also disconnects.  I don't think it's an emulator problem.

**Comment by Peter-J-Jansen** [comment] 2023-01-24 13:36
I know the problem is against LCS devices, so just for information : TLS works fine with QETH layer 3 devices, both in Linux (Ubuntu 20.04) and Windows (11; VS2022 clang 15.0.1 built). I'll try an LCS device when I've set one up.

This was tested with x3270, wc3270 an PCOMM emulators.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-01-24 23:22
Peter Vels (@PeterVels) said:
> _**Prerequisite:**_ Configure the TN3270 started task to use TLS authentication. I realise this is not a trivial exercise, so if you have not (yet) done this then setting it up will take some configuring. I am happy to do experiments on your behalf.

Ah-HA! So configuring z/OS to use TLS is _**not**_ as simple as just adding a "TTLS" statement to your TCPIP profile! I guess that makes sense.

Peter? (either one!) (or _anyone_ really!) Could you explain to me what is involved in configuring z/OS to use TLS? Preferably put it in a short(?) notepad document (or PDF document, etc; I don't care) and either post (upload) it here or else send it to me privately. Either way is fine.

_**NOTE!** &nbsp;Be sure to use small/simple words! Remember, I know almost nothing about z/OS! Thanks!_

**Comment by PeterVels** [comment] 2023-01-25 00:10
This is the best write-up on TN3270 and TLS I can find: https://www.linkedin.com/pulse/securing-3270-sessions-at-tls-andrew-mattingly/

**Comment by Fish-Git** [comment] 2023-01-25 06:10
> This is the best write-up on TN3270 and TLS I can find: https://www.linkedin.com/pulse/securing-3270-sessions-at-tls-andrew-mattingly/

WAY beyond my skill level I'm afraid. &nbsp;`:(`

 (Besides that, the web page is too hard to read too! The author's choice of fonts absolutely SUCKS!)

**Comment by Fish-Git** [comment] 2023-01-25 22:49
_**Okay, I have some news...**_

I was able to get TLS working just fine with _**z/OS 2.5c**_ right out of the box. &nbsp;_(Don't ask! I have friends!)_ &nbsp;I did not have to configure anything at all _(other than change my TCPIP profile to specify use of an LCS device instead of a QETH/OSA of course, but that was it. I did not have to make any other changes at all)_.

I was able to connect my TN3270 client to port 2023 using TLS 1.2, and it worked fine. And, most importantly, I was able to paste 36 lines of 80 characters each = 2880 bytes just fine too. Hercules did _not_ crash or hang. I tried the same thing using a QETH/OSA device too, and it also worked fine.

I tested both OSA and LCS using both the current git "develop" branch of Hercules as well as the same official 4.5 version that you are using. Both worked flawlessly in all situations.

_SO...._ &nbsp;The only preliminary logical conclusion I can come to is that the likely cause of your problem is what I originally suspected: your Windows host's network adapter is not configured properly for CTCI-WIN/Hercules! You _**must**_ disable "_**TCP Large Segment Offloading**_"**`(*)`** on your adapter! Hercules networking simply _will not work correctly_ with it enabled! As I said before, this is a well known issue.

One item of note however _(and maybe this is where the problem lies?)_: I did not have to create any type of certificate for z/OS or install any certificate on my Windows system either. As I said, TLS on my z/OS system worked fine right out of the box. I did not have to configure anything at all. Does that mean anything? Is that significant? I don't know! I'm simply too unfamiliar and inexperienced with z/OS! Maybe you can figure that out for us.

But for now, I'm going to classify this as [PEBKAC](https://www.google.com/search?q=define+PEBKAC) (i.e. user error).

Sorry!

_(I'll leave this issue open for another day or three to give you a chance to fix your adapter issue and try again. If I don't here from you in a day or three however, I'm going to go ahead and close this issue as User Error. Thanks)_
____
**`(*)`** _Or whatever it's called on your adapter. Some adapters call it Large Send Offload, others call it Segmentation Offloading._

**Comment by PeterVels** [comment] 2023-01-25 23:50
> I did not have to create any type of certificate for z/OS

That leaves me wondering what you and your friends **did** do.  Anyway, the simple way know that your 3270 session is using TLS is to  look for the padlock symbol.  In Tom Brennan's Vista TN3270 it's in the status bar at the bottom of the screen.  My non-TLS window (connected to 127.0.0.1 port 3270) shows this:

![image](https://user-images.githubusercontent.com/55377655/214718136-0f014ee6-657b-4b22-bbe3-bb52566ae6f9.png)

whereas a TLS 3270 session has this (note the padlock on the left):
![image](https://user-images.githubusercontent.com/55377655/214718205-b8cf69f3-09c9-4dd3-b1f5-e405705cc506.png)

Clicking on the padlock brings up the TN3270 server certificate information.

In PCOMM it looks like this:

![image](https://user-images.githubusercontent.com/55377655/214719308-207125c0-4c7d-4666-9cde-b4688a438161.png)

**Comment by PeterVels** [comment] 2023-01-26 01:28
I'm willing to accept this is a **hardware** issue.  I tried a different Windows machine (laptop) with a near-identical Hercules and guest OS setup and it does _not_ fail when I paste 57 150-byte lines into a  TLS 3270 session.  FWIW, I can't see any "offloading" settings in the laptop's network adapter's configuration.  OK to close.

**Comment by Fish-Git** [comment] 2023-01-26 01:31
> > I did not have to create any type of certificate for z/OS
> 
> That leaves me wondering what you and your friends **did** do.

It is a _PLAIN, VANILLA, UNMODIFIED, AS DELIVERED, OUT-OF-THE-BOX_ z/OS 2.5c ADCD. Neither my anonymous benefactor nor myself modified it any way whatsoever.

> Anyway, the simple way know that your 3270 session is using TLS is to look for the padlock symbol. In Tom Brennan's Vista TN3270 it's in the status bar at the bottom of the screen.

I know that.

> Clicking on the padlock brings up the TN3270 server certificate information.

Knew that too:

```
OpenSSL Version:     OpenSSL 1.0.1g 7 Apr 2014
Encryption:          AES256-SHA - 256 bits
Protocol:            TLSv1.2
Issued By:           IBM
Organization:        IBM
Distinguished Name:  unknown
Department:          DTSC
Country:             US
State/Province:      Texas
City:                Dallas-Coppell
Domain:              S0W1.DAL-EBIS.IHOST.COM
Valid:               From 2019-10-03 06:00:00 to 2020-50-01 02:05:59
```

**Comment by Fish-Git** [comment] 2023-01-26 01:34
> I'm willing to accept this is a **hardware** issue. I tried a different Windows machine (laptop) with a near-identical Hercules and guest OS setup and it does _not_ fail when I paste 57 150-byte lines into a TLS 3270 session. FWIW, I can't see any "offloading" settings in the laptop's network adapter's configuration. OK to close.

Thank you. Closing.

**Closed as completed by Fish-Git** 2023-01-26 01:34 UTC
Labels: User Error, Unknown
