### ISSUE TITLE
Hercules version 4.3.9999.0-SDL-g392a251-modified (4.3.9999.0)  Regression

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#252] opened 2019-09-20 09:52 UTC
Used SDL Hercules version **4.3.9999.0-SDL-g392a251-modified (4.3.9999.0)**  

Started z/VM and then several z/OS guests, to force paging by z/VM CP. It seems that lots of paging by z/VM will eventually lead to a core dump. 

Also without paging, z/VM will very often do an `IFI004` when IPLing a z/OS guest machine. 

Thanks

M

```
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Sep 20 2019 at 06:53:50
HHC01417I Built with: GCC 5.4.0 20160609
HHC01417I Build type: GNU/Linux x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 64
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 hatomics=C11
```

**Comment by Fish-Git** [comment] 2019-09-20 12:27
> It seems that lots of paging by z/VM will eventually lead to a core dump.

A z/VM core dump? Or a Hercules core dump? (crash)

If the former, it sounds like a z/VM bug. If the latter, that's a Hercules bug that definitely needs fixed.

> Also without paging, z/VM will very often do an IFI004 when IPLing a z/OS guest machine.

Again, probable z/VM bug. Yes, I understand that your reported unusual z/VM behavior could very well be caused by a bug within Hercules (and thus it's not a z/VM bug but rather a Hercules bug), but until you can provide stronger evidence that it's a Hercules bug and not a z/VM bug and/or a way to easily/reliably reproduce the problem, there's really no way to look into it. I have IPL'ed z/OS under z/VM many, many times and have _never_ experienced _any_ z/VM crash or `IFI004`, etc. _**Never**_.

Of course I fully realize that may not mean much to you, but as I explained, unless I am, or someone else is, able reproduce the problem(s) you describe, there's really no way to look into this supposed "regression".

**Comment by Fish-Git** [comment] 2019-09-22 10:49
FYI: I gave a try to starting multiple (two) instances of z/OS under z/VM and things did not go well.&nbsp;`:(`

The first instance ran fine, but the second instance experienced lots of problems that don't normally occur when run natively.

But I think the reason is likely because I didn't have enough PAGING space defined to z/VM. I currently only have one PAGE pack, a 3390-9, which can only hold a maximum of 8GB, and each z/OS guest was trying to run with 6GB! _(Oops!)_

So I need to define another PAGE volume to z/VM (a 3390-54 maybe) and try again. Hopefully things will work better then.

I'll let you know how it goes.

In the mean time, have _you,_ @moshix , verified that _your_ z/VM system as enough PAGE space to run multiple z/OS systems? If you haven't, that _might_ be your problem? Otherwise if you have, then it's probably something else.

The point is, I haven't completely given up on this issue yet! I admit that it could well be a Hercules bug somewhere (maybe), but before I'm willing to take the time/effort involved in chasing down a bug, I need to be sure there's a bug to be chased! (I don't like chasing non-existent bugs!)

**Comment by moshix** [comment] 2019-09-25 00:49
Fish

Ivan saw my screenshots, so I cannot agree to close this issue because it's a very real issue. I had IFI004 and PROG004 abends of z/VM and Ivan has the screenshots. 

thanks

M

**Comment by Fish-Git** [comment] 2019-09-29 14:48
> Ivan saw my screenshots, so I cannot agree to close this issue because it's a very real issue. I had IFI004 and PROG004 abends of z/VM and Ivan has the screenshots.

Screenshots mean nothing. They just tell us that z/VM experienced a problem. I'm not doubting that! I  absolutely believe you that your z/VM experienced IFI004 and PROG004 abends! But that _by itself_ is not evidence that Hercules is the cause. We need more convincing evidence than just a screenshot!

For example, does the _EXACT SAME_ z/VM system (_exact same_ dasd, Hercules configuration, _z/VM configuration_, etc) work fine with SDL Hyperion 4.2? Or 4.1? That is to say, did this issue only begin happening with 4.2.1? Do earlier versions work okay? If the same system works fine with 4.2 but fails with 4.2.1, then I would gladly accept that as evidence that the problem is very likely being caused by Hercules and would then be willing to re-open this issue. Without such evidence however, _**I**_ am certainly not going to re-open this issue. (If you want to then fine, do so!)

> ... I cannot agree to close this issue ...

Then re-open it! ........

...... _AND_ .... provide more convincing evidence that it is likely a Hercules problem!

As I mentioned before, I myself have _**never**_ seen either problem with the z/VM 6.3 I use to test with.

Only _you_ seem to be having these problems. Maybe it's your NUMA system? Does the same problem happen when you disable NUMA and go plain SMP?

**Comment by ivan-w** [comment] 2019-09-29 15:11
I'm looking into this. I also see moshix is experiencing z/VM soft Abends FUN001 (which are basically the same thing as aa hard abend IFI004). But how they occur, how *often* they occur seem to be highly time dependent.. Depending on your host system, you could possibly run a system without ever running into it or on some systems run into it every couple of hours. I am working on trying to *FORCE* this error to occur. I am suspecting (completely unsubstantiated claim) it has something to do with HSCH/CSCH in relation with PCI/SUSPENDed CCW chains - and one of the CSW/SCSW returned is wrong/bogus/merged/split during subsequent TSCHs.

**Comment by Fish-Git** [comment] 2019-09-29 16:19
> I'm looking into this.

_**THANK YOU**, Ivan!_ &nbsp; Because the problem is completely beyond my capabilities! (especially given the amount of information to go on! A screen shot? And a claim that the guest "sometimes doesn't work"? Come on! That's not much to go on!)

I'll go ahead and re-open the issue and assign it to you since you're working on it and change the "Invalid" label to "Unknown" and "Researching" instead.

**Comment by moshix** [comment] 2019-09-29 16:45
Fish

you make it sound like I am committing a felony to report an issue which is extremely difficult to trigger at will. 

No NUMA. 

As I outlined in the past, this seems to trigger more often on SDL running on machine with slow I/O. It's almost certainly not networking related. 

I have variously supplied dumps to Ivan and the problem is always the same. 

So to say that you have nothing to go by other than a screenshot is just not true and, honestly, a bit offensive. I have been having this problem for well over a year now, so it's hardly news. All I said in this issue I opened is that the chagnes in SDL from last week seemed to make the problem worse. 

Ivan promptly refactored some of his latest changes and - as of today - SDL seems more stable, but it's impossible to say for sure if I don't test more. 

All this to say, just closing this issue because I don't have all the dumps here and all the other information I have been providing for well over a year seems bizzarre. 

We are all working together to make SDL and Hercules even greater than it already is. 

thanks

m

**Comment by Fish-Git** [comment] 2019-09-29 22:13
> You make it sound like I am committing a felony to report an issue which is extremely difficult to trigger at will.

I apologize profusely for conveying that. I certainly did not mean to.

> No NUMA.

Good! That's one suspect to cross off the list.

> As I outlined in the past, this seems to trigger more often on SDL running on machines with slow I/O (like guest instances in the Amazon or google cloud).

Interesting. I thought your system was super fast. That is seems to happen on _slower_ systems is good information to know! Thanks!

> So to say that you have nothing to go by other than a screenshot is just not true and, honestly, a bit offensive.

Again, I apologize if my words offended you. I certainly did not mean for them to do so. But in all honesty the only information you provided in your original problem report was:

> > * SDL Hercules version **4.3.9999.0-SDL-g392a251-modified (4.3.9999.0)**
> > 
> > * Started z/VM and then several z/OS guests, to force paging by z/VM CP. It seems that lots of paging by z/VM will eventually lead to a core dump.
> > 
> > * Also without paging, z/VM will very often do an `IFI004` when IPLing a z/OS guest machine.

I believe any reasonable person would agree that's not very much information to go on!

And when I myself attempted to recreate the same environment that supposedly triggers the problem (1. several z/OS guests, 2. Lots of paging (core dump), 3. No paging (IFI004)) and was unable to do so no matter how hard I tried, _**and...**_ given that I _did_ experience "unusual problems" on my first attempt due to improper z/VM configuration which went away once I configured z/VM properly, what would any reasonable person conclude? Answer: that the problem was likely a user error caused by improper z/VM configuration (i.e. not enough paging space). I even mentioned that in an earlier reply which you never responded to:


It's not uncommon for problem reports to be closed when the reported problem is unable to be reproduced. Many rather large software and hardware companies around the world do it all the time. Only when the same or similar problem is continually reported by others, each one providing slightly different information, does the likely cause begin coming into focus.

> I have been having this problem for well over a year now, so it's hardly news.

I might have been your use of the word "regression" in the title of your report that triggered my reaction. Use of the word "regression" makes it seem as it the changes made in 4.2.1 actually broke something that was working just fine before (i.e. that instead of our changes having made Hercules a _better_ product, that we had somehow made it _worse_ instead! _THAT_ is somewhat offensive!)

It is now all too clear that is not true. The _fixes_ that were made to 4.2.1 did not "regress_ Hercules at all. Rather, it has simply caused an _existing **undiscovered**_ problem to occur more frequently than before.

> All I said in this issue I opened is that the changes in SDL from last week seemed to make the problem worse.

And that's actually good news!

The closer we can get to identifying an as-yet-unfixed existing problem that was previously not known to exist, the better! That means we're getting closer to finding the bug, whatever the heck it is!

But until such time as I myself am able to reproduce it _even one time_ I am afraid there is nothing I myself can do to help you. The best I can do is to continue _trying_ to reproduce it when I have time (HA!) and to continue monitoring your reports. Hopefully, _eventually_ (over time) a likely suspect will begin to come into focus. But until then, I decided it wasn't worth keeping the issue open, which is why I had closed it.

> Ivan promptly refactored some of his latest changes and - as of today - SDL seems more stable, but it's impossible to say for sure if I don't test more.

Which, now that Ivan is on the case, is why I have re-opened it! Ivan is much more skilled than I am at tracking down hard to find z/VM issues. He's a good man.

> All this to say, just closing this issue because I don't have all the dumps here and all the other information I have been providing for well over a year seems bizarre.

Well you didn't provide any dumps in _this_ problem report!

And information from earlier problem reports (other than perhaps the list of symptoms) don't apply to _current_ problem reports IMO, so I personally wouldn't label by decision to close the issue as being "bizarre". Rather, from _**my**_ point of view it was completely reasonable.

_**BUT...**_ now that Ivan is looking into your problem and the issue has been re-opened, the point is now moot:

_**We're on it, Moshix!**_

And by "we" I mean the Hercules team (but mostly Ivan!). &nbsp;As for myself, I shall continue to _occasionally_ try and reproduce the problem (when I find time).

I'm afraid that's the best we can do right now. I hope that's good enough.

> We are all working together to make SDL and Hercules even greater than it already is, I therefore fail to understand the animosity.

Again, I _sincerely_ apologize for unintentionally offending you in any way. I have only the greatest respect for you, Moshix! Please know that! You're an important _unofficial_ member of the Hercules team IMO, and would never intentionally offend you. _Never._

... At least not without good reason anyway. (heh!) &nbsp;`;-)`

(That was a _joke_ by the way)

**Comment by Fish-Git** [comment] 2020-10-01 19:21
Moshix? (@moshix)

Are you still experiencing IFI004? What version of Hercules are you using?

Many changes have been made over the past year since you first opened this issue over a year ago, one of which was DAT related. I'm wondering whether or not we may have now maybe fixed this issue of yours. When was the last time you experienced a IFI004, and what version of Hercules were you using when it happened? Are you currently using a relatively recent version of Hercules? What version?

I would very much like to close this issue if possible, but do not want to do so if the problem still exists!

Does the problem still exist?

Thanks!

**Comment by moshix** [comment] 2020-10-02 05:54
Hi Fish

I had one IFI004 around April with an SDL version from January 2020 (so that gave it about 3-4 months of uptime, nonetheless). With the version from April 2020, I have so far not had an IFI004 or any other crashes, with an uptime of about 5 months and moderate NJE load (node MOSHIX4)

So, I think we can close this issue. If this issue surfaces again, it's easy to re-open it. 

Many thanks

M

**Comment by Fish-Git** [comment] 2020-10-02 09:34
> So, I think we can close this issue. If this issue surfaces again, it's easy to re-open it.

Sounds good to me.

> Many thanks

You are very welcome.

While it is good that you can apparently run for many months under moderate load before an `IFI004` occurs, it's still not good _THAT_ they occur. They _shouldn't_ be occurring! And I wish my z/VM + Hercules debugging skills were better so that we could get to the bottom of why they do still occasionally occur. But I guess beggars can't be choosers. Ah well.

If it happens again, please _do_ re-open this issue and we'll try again to try and figure it out.

Thank _YOU_ for your patience, Moshix.

Closing as requested.

**Closed by Fish-Git** 2020-10-02 09:34 UTC
Labels: (Unknown), HELP!, IN PROGRESS..., Ongoing, Researching...
