### ISSUE TITLE
Number of DSCB in DASDLOAD(64) too small?

### ISSUE THREAD

**Issue by peter-sylvester** [SDL-Hercules-390/hyperion#566] opened 2023-05-18 13:44 UTC
The dasdload utility allows for a maximum of 1000 dscbs. This doesn't allow to put for example the whole CBT tape on a disk. Is there a reason not to increase this number?

**Comment by Fish-Git** [comment] 2023-05-18 17:26
> Is there a reason not to increase this number?

None whatsoever. It is currently a hard coded constant value, which IMHO it shouldn't be. The only hard coded value should be the _default_ number of DSCBs, but the user should be able to override that value via a command line option.

I'd get right on that for you, Peter. Thanks for reporting it.

**Comment by Fish-Git** [comment] 2023-05-18 21:43
Peter, (@peter-sylvester)

Can you provide a simple repro for me that triggers the problem? I'd like to test my changes before committing them.

Thanks!

**Comment by Fish-Git** [comment] 2023-05-19 16:37
FYI: I have the necessary changes _(I hope!)_ ready to commit, but am reluctant to do so until I can verify it correctly addresses the problem. Since I am quite unfamiliar with `dasdload ` (having never in my life ever used it), I would appreciate being provided with a simple test case that reproduces the problem so I can verify my changes do indeed correct it.

Since it's only been 18 hours since I made my original request for a repro (and thus you may not have even seen it yet!), I'll go ahead and wait for another 2 or maybe 3 days before committing my changes anyway if I don't hear back from you by then. Thanks.

**Comment by peter-sylvester** [comment] 2023-05-20 16:16
I just spend a few days of vacation with very limited access to Internet. I'm just going back home at 300km/h in a TGV with good wifi. 

I seem to understand that you have copied the common code into dasdload2.h. That's good IMHO.

The offending line is the #define  MAXDSCB  1000. This constant is used to allocate a table of pointers.
I simply increased the value to 5000.  Making this another parameter doesn't seem necessary (to me). 

To test you can use a (not so) small ctrl file  

ONEBIG 3390 
test.f1 seq  myfile TRK 1 1 0 PS FB 80 800
test.f2 seq  myfile TRK 1 1 0 PS FB 80 800
...
test.1001 seq myfile TRK 1 1 0 PS FB 80 800

always with the same small myfile from with the content is taken. 
It should complain for the 1001 unless MAXDSCB is make bigger.

**Comment by Fish-Git** [comment] 2023-05-20 19:29
> To test you can use a (not so) small ctrl file:
[...]
> always with the same small `myfile` from which the content is taken. It should complain on the 1001st entry unless `MAXDSCB` is made bigger.

Thanks! Problem fixed by commit 8f6ccf2453b67a2888e795131b43c04123da44e6.

Please refer to updated "hercload.html" file.

Closing.

**Closed as completed by Fish-Git** 2023-05-20 19:29 UTC
Labels: Enhancement
