### ISSUE TITLE
Softfloat on OpenBSD/sparc64 fails build: does not support thread-local

### ISSUE THREAD

**Issue by cptnapalm** [SDL-Hercules-390/hyperion#248] opened 2019-09-13 20:57 UTC
From my afternoon's research, OpenBSD does not support thread-local despite using GCC.  Digging around, I saw that thread local was added in SoftFloat 3b as an option.

If it is still optional, a flag for OpenBSD to not use thread local (softfloat.h in the IBM_IEEE block) and fallback to single threaded would improve the odds of being usable on OpenBSD.

**Comment by Fish-Git** [comment] 2019-09-16 00:25
More information is needed:

* What version of Hercules are you trying to build? (It's best to clone the [repository](https://github.com/SDL-Hercules-390/hyperion) and build directly from that.)

* Did you build the **External Libraries** for your Sparc64 system before attempting to build Hercules? (as instructed in the [documentation](https://sdl-hercules-390.github.io/html/hercinst.html)?)

* In case it matters, what version of OpenBSD are you using?

Finally, your opening comment that:

> OpenBSD does not support thread-local despite using GCC

leads me to believe the problem is with your version of GCC, not Hercules.  Have you tried upgrading GCC to a newer version?  Can we at least see the errors you are getting?  Your problem report is quite vague and unhelpful!

**Comment by cptnapalm** [comment] 2019-09-16 16:57
A) I did clone the repository.
B) It was while building the External Libraries, Softfloat specifically
following the instructions (necessary for building on sparc), that the
error "thread-local storage not supported for this target."  Thus the
references to Softfloat and thread-local not being supported in the title.
C) The GCC version being used is 4.9.4.  However, OpenBSD (the newest,
latest 6.5) simply doesn't support thread local storage; neither does
NetBSD, according the the libdill page (
http://libdill.org/compatibility.html).
D) util/bldlvlck passed.
E) It might be possible to get gcc to emulate TLS support.  I will look
into it.

**Comment by Fish-Git** [comment] 2019-09-16 20:58
> ... doesn't support thread local storage; neither does NetBSD ...

According to Wikipedia and NetBSD themselves, thread-local storage has been supported for at least the past 7 years:

&nbsp;

https://en.wikipedia.org/wiki/NetBSD#Releases

> **Release 6.0** &nbsp; &nbsp; &nbsp; (17 October 2012)
> 
> * Support for thread-local storage, Logical Volume Manager functionality

&nbsp;

https://www.netbsd.org/releases/formal-6/NetBSD-6.0.html

> **Announcing NetBSD 6.0**
> 
> **Introduction**
> 
> Some NetBSD 6.0 highlights are: support for thread-local storage (TLS), ...

&nbsp;

But it looks like you're right as far as OpenBSD is concerned: as best as I can tell it doesn't support TLS.

I have not messed with SoftFloat in a _loooong_ time (the last major change to our SoftFloat code was done by @srorso Steve Orso), but I seem to recall that TLS was a big deal.

I am doubting _(but am admittedly unsure!)_ Hercules Software support can be built without thread-local storage (TLS) support.

Maybe @srorso Steve can jump in here and answer this question more definitively (authoritatively).

Steve?

**Comment by cptnapalm** [comment] 2019-09-18 02:43
Two things happened today which precluded compiling a newer version of gcc:
the CMOS battery in my UltraSparc laptop died (rendering this whole thing
moot until I replace it) and I got a Multiprise 3000 (saved from going to a
scrap yard.)

I would say that this issue should be closed for now.  If I can get it
working with a later version of gcc emulating TLS, then I'll send a message
and it can just be included in documentation as an extra step for OpenBSD
users.

Sound appropriate?

**Comment by Fish-Git** [comment] 2019-09-18 03:06
Seems reasonable to me. Closing for now. Feel free to re-open if/when you feel doing so is warranted.

**Closed by Fish-Git** 2019-09-18 03:06 UTC
Labels: HELP!, L, QUESTION..., Researching...
