### ISSUE TITLE
Can't upgrade Ubuntu 18.04 to 20.04 - Illegal instruction in rm

### ISSUE THREAD

**Issue by mp39590** [SDL-Hercules-390/hyperion#567] opened 2023-05-29 16:22 UTC
I'm using self-built Hyperion 4.5 (`58578601d` from git) on Fedora 38

While doing `apt full-upgrade`  on Ubuntu under the emulator, I get following error in my session:
```
Unpacking libc6:s390x (2.31-0ubuntu9.9) over (2.27-3ubuntu1.6) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Illegal instruction)
dpkg: error processing archive /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_s390x.deb (--unpack):
 rm command for cleanup subprocess was killed by signal (Illegal instruction)
Errors were encountered while processing:
 /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_s390x.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

On hercules console:
```
HHC00801I Processor CP03: Operation exception interruption code 0001 ilc 6
HHC02324I CP03: PSW=0705200180000000 000003FFA0F1BA14 INST=E70030000837 ????? ,                      ?
HHC02326I CP03: V:000002AA35A85816:R:00000000164B1816:K:06=746D 702E6369 00000000 00000000 0000 ._..............
HHC02326I CP03: V:0000000000000837: Translation exception 003B (Region-third-translation exception)
HHC02269I CP03: R0=0000000000000006 R1=000003FFA0F1BA00
HHC02269I CP03: R2=000002AA35A85808 R3=000002AA35A85816
HHC02269I CP03: R4=0000000000000007 R5=FFFFFFFFFFFFFFF2
HHC02269I CP03: R6=0000000000000000 R7=000002AA35A84440
HHC02269I CP03: R8=0000000000000002 R9=000002AA35A84440
HHC02269I CP03: RA=000002AA35A85700 RB=0000000000000006
HHC02269I CP03: RC=000003FFA10A6F88 RD=000002AA34E8CC30
HHC02269I CP03: RE=000002AA34E89A06 RF=000003FFFD07F130
HHC02271I CP03: C0=0080000014846A10 C1=000000002FFAC1C7
HHC02271I CP03: C2=0000000000011140 C3=0000000000000000
HHC02271I CP03: C4=000000000000FFFF C5=0000000000011140
HHC02271I CP03: C6=0000000010000000 C7=000000003248C1C3
HHC02271I CP03: C8=0000000000000000 C9=0000000000000000
HHC02271I CP03: CA=0000000000000000 CB=0000000000000000
HHC02271I CP03: CC=0000000000000000 CD=0000000000ED8007
HHC02271I CP03: CE=00000000DB000000 CF=0000000000011280


HHC00801I Processor CP00: Operation exception interruption code 0001 ilc 6
HHC02324I CP00: PSW=0705200180000000 000003FFA1A9BA14 INST=E70030000837 ????? ,                      ?
HHC02326I CP00: V:000002AA09104816:R:0000000016846816:K:06=746D 702E6369 00000000 00000000 0000 ._..............
HHC02326I CP00: V:0000000000000837: Translation exception 003B (Region-third-translation exception)
HHC02269I CP00: R0=0000000000000006 R1=000003FFA1A9BA00
HHC02269I CP00: R2=000002AA09104808 R3=000002AA09104816
HHC02269I CP00: R4=0000000000000007 R5=FFFFFFFFFFFFFFF2
HHC02269I CP00: R6=0000000000000000 R7=000002AA09103440
HHC02269I CP00: R8=0000000000000002 R9=000002AA09103440
HHC02269I CP00: RA=000002AA09104700 RB=0000000000000006
HHC02269I CP00: RC=000003FFA1C26F88 RD=000002AA08A8CC30
HHC02269I CP00: RE=000002AA08A89A06 RF=000003FFC7D7EEF0
HHC02271I CP00: C0=0080000014846A10 C1=000000002FB7C1C7
HHC02271I CP00: C2=0000000000011140 C3=0000000000000000
HHC02271I CP00: C4=000000000000FFFF C5=0000000000011140
HHC02271I CP00: C6=0000000010000000 C7=00000000325881C3
HHC02271I CP00: C8=0000000000000000 C9=0000000000000000
HHC02271I CP00: CA=0000000000000000 CB=0000000000000000
HHC02271I CP00: CC=0000000000000000 CD=0000000000ED8007
HHC02271I CP00: CE=00000000DB000000 CF=0000000000011280
```

Searching for  `E70030000837` in issues, I found #367, but I'm not completely sure if it's related.

Can someone point how to overcome this?

If it matters, https://ubuntu.com/download/server/s390x has the following note:

> Starting with 20.04 LTS the minimal requirement is z13s/z13, respectively LinuxONE Rockhopper/Emperor.
zBC12/zEC12 are only supported up to Ubuntu 18.04 LTS.

**Comment by mcisho** [comment] 2023-05-30 10:04
Currently, there is no way to overcome this. Hercules does not support any of the zArch Vector instructions, which are being used more and more frequently in recent Linux distributions. I understand there is an effort underway to write the support for Vector instructions, but there are an awful lot of instructions to be supported, so the support may not be available for some time.

**Comment by Fish-Git** [comment] 2023-06-01 15:41
Ian is correct: your problem is being caused by the fact that Hercules does not yet support the z/Architecture Vector Facility _(and likely won't for quite some time yet)_.

As a result, I'm afraid, for now, you're stuck with using only Ubuntu 18.04 or earlier. Sorry! &nbsp; `:-(`

Closing as duplicate if Issue #77.

**Closed as completed by Fish-Git** 2023-06-01 15:41 UTC
