### ISSUE TITLE
VM/370 CP PER command instruction tracing fails with ECPSVM YES

### ISSUE THREAD

**Issue by BobBolch** [SDL-Hercules-390/hyperion#465] opened 2022-01-07 13:13 UTC
When the VM/370 Community Edition CP command "PER" is used to set an instruction trace with the "I" operand,  and the ECPSVM operand in the Hercules configuration file is set to YES, then the instruction trap is ignored. Proper operation of PER is restored if the "ECPSVM DISABLE  DISP1 DISP2" is added to the configuration file. This symptom occurs starting with Hercules 4.4.0.xxxx.

**Comment by Fish-Git** [comment] 2022-01-07 16:43
I'm not that knowledgeable or experienced with the latest VM/370 CE offering, so I'm going to need a little help recreating this problem. Can you help me out?

1. Where can I download VM/370 CE from?
2. What does my Hercules configuration file need to look like?
3. What must I do to "see" the problem? (Which userid to logon to, what commands to enter, etc)
4. You say it started occurring with 4.4.0. Does it work with 4.3.0? I want to see a good run so I can see what it _should_ look like and compare it to the failing run.

Thanks.

_(Bob? @wably Or Ivan? @ivan-w: &nbsp; I might be needing your help with this one. Thanks.)_

**Comment by wably** [comment] 2022-01-07 17:18
@Fish-Git 

I'll be happy to take this one.  This really isnt a new issue; I've known about this for years.  It happens in all S/370 versions of VM/370 that have the Waterloo PER mods installed.  You don't need to be on VM/CE.  It also occurs on VM/SP with its native PER support.

I am not at all certain that PER use is _fully_ supported with ECPS active even on a real S/370 or 43xx CPU of the day.  I seem to recall a bunch of restrictions around it.

However, there are a bunch of tests in DMKDSP (the dispatcher code of VM/370) that check for PER being active when ECPS is also active.  Since the affected ECPS assist functions follow the DMKDSP code in order to perform those same functions in 'microcode', something is probably botched up or missing in ecpsvm.c.    That's likely why when Bob disables DISP1 and DISP2 that PER starts working; when those two assists are disabled then the actual DMKDSP code is executed and not ECPS for those functions.

I don't use PER often but when I do I just disable the assists.   But maybe I can find out what's up for this case.

@BobBolch can you provide details on how to recreate your issue?  I am sure I can find something that fails too, but I want to be sure to address your exact issue as well.

Regards,
Bob

**Comment by BobBolch** [comment] 2022-01-07 20:46
Some more background. This issue is the first one I have seen when using the PER command from Kerry Anderson at U of Maine for VM/370. It is the basic tool for debugging applications or system modifications on VM/370. I used it constantly in all public releases of SDL Hercules on Windows.

When the VM Community Edition release came out, Bob P. fixed an ECPSVM issue with floating point registers that was exposed, because BREXX has an enhanced roll in that system, and it used floating point operations extensively. I was not able to run Bob's fix, because I don't have the Windows skills to build a custom Hercules version. I ran VM370CE with 'ECPSVM DISABLE DISP1 DISP2' , and distributed it with that configuration statement in place.

VM370CE is downloadable from www.vm370.org
The download is a directory containing the Hercules configuration file and all the files needed to define the Hercules instance.
The end use just issues the vm370ce CONF (or SH) file to start it up.

When the Hercules 4.4.0.xxxxxx publically available pre-built version was released a few weeks ago, I removed the ECPSVM DISABLE configuration file statement and started VM370CE with ECPSVM YES to test the fix for the floating point register ECPSVM problem that Bob fixed early last year.  I immediately ran into the symptom I am seeing now.

/* A test case is trivial.  Here is the test run with ECPSVM DISABLE DISP1 DISP2 in place. */
/*  Logon to any ID, for example MAINT with password CPCMS. */
/* Set a PER Instruction trap at address X'E000', where the ACCESS command module is loaded and executed */
CP PER  I  RANGE E000
Ready;
/* Issue the ACCESS command */
ACCESS 191 A
>00E000   LR      182F      CC=0
BEGIN
'191' REPLACES 'A (191)'
Ready;
/* The initial response when the ACCESS command is entered, shows that the PER trap interrupted the instruction  */
/* at address E000, and suspended execution. The BEGIN command then resumes executiuon of the ACCESS command. */

When I changed the configuration file to specify ECPSVM YES, I see the following:


cp per i r e000               
Ready; T=0.01/0.01 15:35:07   
acc 191 a                     
'191' REPLACES ' A (191) '    
Ready; T=0.01/0.01 15:35:13   
per q                         
 IFETCH RANGE E000 TERMINAL   
Ready; T=0.01/0.01 15:35:20  

The last PER Query command shows that the PER intercept is in place, but that it just doen't activate when the access command is executed.  

As I said, I have used the PER facility on VM/370 with Hyperion versions 4.1, 4.2, 4.2.1, and 4.3 with ECPSVM YES, constantly for the last 3 years while writing VM/370 CMS extensions and utilities. I setup for testing VM370CE with Hyperion 4.4 in late December.
I am happy to run any additional tests that would be useful.

If I am remembering correctly, the PER facility on real VM/370 was a local modification from Kerry Anderson at the University of Maine. IBM did add it to VM later, but I can't remember exactly when.

**Comment by wably** [comment] 2022-01-07 21:57
Hi Bob,

I was able to recreate the issue just as you described.  I was using VM/CE 1.1 on a SDL Hyperion I built last October, so its still technically 4.3.  So...I am on it.

And I stand corrected about the PER origin; I thought it was Waterloo but you are correct instead that it is University of Maine.

Regards,
Bob

**Comment by BobBolch** [comment] 2022-01-08 12:36
Hi Bob,

I did a few more experiments just now with VM370CE and the Sixpack 1.3 beta
and final release levels.
I was surprised to see that the PER command in the test case behaves the
same way with all
the VM variant levels and with Hercules levels back to 4.2.1, so now I
believe I was wrong about
this being a newer problem.  I must have been running with ECPSVM OFF
during the BREXX
development and debugging that started in early 2020. When we started
packaging the initial
Community Edition version, I set ECPSVM on, and started seeing the floating
point errors
that we experienced while running more BREXX tools.

I am hoping to get the next VM370CE release out in the near future, and I
will set the default
config file to use ECPSVM DISABLE DISP1 DISP2.

I will run a few more tests to better understand what is happening. I
recommend we make this a low
priority issue for now.

I am sorry I was so confused about the timing.
Bob

**Comment by wably** [comment] 2022-01-08 14:48
As it turns out, this is not a Hercules ECPS issue.  Instead, the distributions of VM/CE and possibly VM Sixpack Beta 1.3 are missing a patch to DMKDSP in CP.  The patch is DMKDSP HRC074DK and it was written in February 2018.  This patch allows PER to work while ECPS is active by bypassing the ECPS DISP2 assist call in the dispatcher for the userid that is using PER and only bypassing while PER is actually active.  Bypassing the DISP2 assist call means that the actual CP code in DMKDSP will perform the DISP2 function in regular machine instructions.

I found that VM/CE had the patch file DMKDSP HRC074DK loaded onto its 094 disk just as it should; so the patch was distributed.  Nonetheless, the patch was not in effect because the related AUX file (DMKDSP AUXHRC) did not contain HRC074DK.  As a result when DMKDSP was last assembled in preparation for building a CP nucleus the patch was not incorporated into the system.

Adding the following line as the FIRST line in DMKDSP AUXHRC then reassembling DMKDSP and then building a new CP nucleus and re-ipling resolves this issue.

      HRC074DK V01 Do not execute ECPS:VM assist DISP2 with PER active 

Bob Bolch confirmed to me in a private email that adding the line above to the AUX file did indeed resolve this issue.

I'm closing this and marking it as a user error because it is not a Hercules issue, even though it is a valid problem for VM/370 itself.

Regards,
Bob

**Closed as completed by wably** 2022-01-08 14:48 UTC
Labels: User Error

**Comment by RossPatterson** [comment] 2024-05-15 18:52
I'm seeing exactly the problem @BobBolch reported, but under Hyperion 4.7+ (current develop branch minus 7 commits, but nothing relevant) and running VM/370 CE 1.2 with `HRC074DK` applied.

@wably You noted back on 2021-03-26 [on the h390-vm list](https://groups.io/g/h390-vm/message/2776) that the `DISP1` instruction invokes `DISP2` under the covers.  I haven't been able to determine just what the interaction between `DISP2` and VIrtural PER is, but based on that comment, I think CP should skip `DISP1` when the active user has PER active as well, not just `DISP2`.  Can you comment on that?

**Comment by wably** [comment] 2024-05-15 19:42
Hi Ross,

Assist DISP1 or DISP2 could be invoked separately by DMKDSP.  If DISP1 is invoked, then within Hercules it might invoke DISP2 internally. Since any invocation of DISP1 _could_ result in DISP2 being called, it would be best if DISP1 and DISP2 are disabled if using PER.

The relevant code that calls DISP2 from DISP1 is in ecpsvm.c, here:

    DEF_INST(ecpsvm_disp1)
    {

    ECPSVM_PROLOG(DISP1);
    switch(ecpsvm_do_disp1(regs,effective_addr1,effective_addr2))
    {
        case 0: /* Done */
            CPASSIST_HIT(DISP1);
            return;
        case 1: /* No-op */
            break;
        case 2: /* Call DISP2 - INTCHECK NOT needed */
            switch(ecpsvm_do_disp2(regs,effective_addr1,effective_addr2))
            {
                case 0:
                    CPASSIST_HIT(DISP1);
                    return;
                case 1:
                    return;
                case 2:
                    CPASSIST_HIT(DISP1);
                    RETURN_INTCHECK(regs);
                default:
                    break;
            }
            return;
        default:
            return;
      }
    }

Since DISP1 is executed and its exit value determines whether DISP2 is called or not, I can't predict when it will be invoked.

If you can provide details describing exactly how to recreate the issue you are having, then if I can recreate it I can look for another solution.  It could be that another fix like HRC074DK is required in CP.  For example, when DMKDSP invokes DISP1, there is no test to see if PER is active.  Perhaps there should be.  HRC074DK is only testing for PER prior to invoking DISP2.  Or maybe an ecpsvm fix is required.

I'm assuming your issue is slightly different that the original that Bob Bolch had, because that issue was resolved as far as I know up until this point.

Regards,
Bob

**Comment by RossPatterson** [comment] 2024-05-16 20:45
> I haven't been able to determine just what the interaction between `DISP2` and VIrtural PER is

Found it.  [`ecpsvm.c`, in `do_disp2()`](https://github.com/SDL-Hercules-390/hyperion/blob/master/ecpsvm.c#L1541) doesn't do the things that the Virtual PER mods added to `DMKDSP` at `RELPER`:

```assembler
RELPER   DS    0H
         L     R2,VMPERCTL    TRACE EXTENSION 
         LCTL  C9,C11,PERCR9-PERBLOK(R2)     LOAD TRACE C-REGS
         OI    RUNPSW,PERMODE ENABLE PER IN RUNPSW
```

> I think CP should skip `DISP1` when the active user has PER active as well, not just `DISP2`

Which means the answer is yes, `HRC074DK` is an insufficient fix, and `ecpsvm disable disp1 disp2` should be used until a corresponding fix is added to `DMKDSP ` at label `DISPATCH`.  I'll work up the fix and test it.

**Comment by RossPatterson** [comment] 2024-05-16 20:49
> If you can provide details describing exactly how to recreate the issue you are having, then if I can recreate it I can look for another solution. 

It's not easy to reproduce - like my FPR4-damage issue recently, it's extremely timing-related.  I've seen it, but not when I had the console spooled :-( 

> It could be that another fix like HRC074DK is required in CP. For example, when DMKDSP invokes DISP1, there is no test to see if PER is active. Perhaps there should be. HRC074DK is only testing for PER prior to invoking DISP2. 

At this point, I'm certain that's the issue.

> Or maybe an ecpsvm fix is required.

I don't think so, unless you think that `ecpsvm` should be aware of the Virtual PER mods.  Personally, I think that's a step too far, since there's no way for Hercules to know if the CP mods are installed.

> I'm assuming your issue is slightly different that the original that Bob Bolch had, because that issue was resolved as far as I know up until this point.

At least in appearance, my issue is identical to Bob Bolch's.

**Comment by wably** [comment] 2024-05-16 22:04
Hi Ross,

I agree; ecpsvm should not have code specific to the Virtual PER mods.

It sounds like you are going to work up a CP modification.  I'll stand aside then unless you need me to do something.

Regards,
Bob

**Comment by RossPatterson** [comment] 2024-06-07 00:04
The fix was trivial.

[DMKDSP.AUXLCL.TXT](https://github.com/user-attachments/files/15687750/DMKDSP.AUXLCL.TXT)
[DMKDSP.RAP007DK.TXT](https://github.com/user-attachments/files/15687751/DMKDSP.RAP007DK.TXT)

**Comment by RossPatterson** [comment] 2024-06-07 00:07
The fix is at https://github.com/s390guy/vm370/issues/66.

**Comment by RossPatterson** [comment] 2024-12-22 00:17
Fix has been uploaded to https://groups.io/g/h390-vm/files/hrc080dk.vmarc as HRC080DK.
