### ISSUE TITLE
Mainsize test can crash on systems with low memory

### ISSUE THREAD

**Issue by wrljet** [SDL-Hercules-390/hyperion#330] opened 2020-10-27 15:15 UTC
Running `make check` can crash in the _Mainsize_ test on systems with small memory size.

Discovered on cloud host virtual machine running Ubuntu 18.04 with a single CPU and 512MB RAM.
This has been tested and reproduced on several other Linux systems, with low RAM size.

It can be reproduced by starting Hercules, and entering `MAINSIZE 2G` twice in a row.

Linux uses an idea called memory over-commit, and as a result, you can call `malloc()` with a large
size request, larger than total RAM and swap space combined, and the system call will succeed.
When the memory is actually used, is when Linux will commit it and try to allocate the space from
RAM and swap partition.  This results in some unexpected surprise behavior.

(By contrast, Windows will not do this.  `malloc()` for unreasonable sizes will fail if there is not enough
physical RAM and swap disk space available at the time of the call.)

When issued the first `MAINSIZE 2G` command, Hercules, [in config.c around line 320, `configure_storage()`
issues an allocation call](https://github.com/SDL-Hercules-390/hyperion/blob/7ac8c16e0691d747dda8cfd9bb586d55b7612f58/config.c#L320-L321) for 2GB, which succeeds.  It then calls ipl.c `storage_clear()` which doesn't do much.

When the second `MAINSIZE 2G` command is issued, [`storage_clear()` does an `memset()` call](https://github.com/SDL-Hercules-390/hyperion/blob/7ac8c16e0691d747dda8cfd9bb586d55b7612f58/ipl.c#L951-L962)
to zero out 2GB of memory.  This is when Linux tries to commit actual memory (or swap space) for
the original allocations, which fails.  Linux behavior in this case is to kill the process.  (this is documented behavior)

If top or htop are running in another window, when the second `MAINSIZE 2G` command is
issued, you can see the memory and swap space usage shoot up to the maximum over a few
seconds, and then Linux kills the Hercules process.

(One thing I do not understand is why Hercules doesn't clear the storage on the first `MAINSIZE`,
but does on the second.)

Bill

**Comment by dasdman** [comment] 2020-10-28 02:10
Bill:

 

You’re detailing multiple issues, one of which Hercules CAN’T FIX as it is an issue with the underlying OS and provided libraries.

 

Past that, it would be helpful to understand that Hercules takes advantage of memory allocation calls that the library or system indicates that cleared storage is returned. In fact, storage_clear() as you indicated is taking advantage of this. In addition, there is no architectural requirement that storage be cleared on the definition or redefinition of memory. Hercules does this as a convenience to users to help avoid worse problems. Also, architecturally, the only way to “guarantee” clear storage is to perform a “system clear” function or an IPL with the clear option.

 

Mark
dasdman

**Comment by Fish-Git** [comment] 2020-11-12 03:35
> (One thing I do not understand is why Hercules doesn't clear the storage on the first `MAINSIZE`,
> but does on the second.)

Because the allocation is always done via the `calloc` API, which by definition allocates memory that is already cleared to zeroes. Only `malloc` needs to be manually `memset` to zeroes if that's what you want, but `calloc`ed memory is already zeroed.

**Comment by Fish-Git** [comment] 2020-11-12 03:37
Closing issue as "Won't Fix" (described behavior working as designed)

**Closed as completed by Fish-Git** 2020-11-12 03:37 UTC
Labels: WON'T FIX
