### ISSUE TITLE
Auxiliary threads eating up CPU time

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#589] opened 2023-08-02 13:39 UTC
On my ARM system (4 cores) I have 1 instance of hercules running (z/arch)

I see 2 threads running 100% of a core : 
- panel_display
- rubato_thread

I did issue a timerint 100000 - but still the same

I understand the rubato_thread is transaction facility related.. but is it normal they (timer and.. rubato ?) both are is taking a full core ?

--Ivan

**Comment by Fish-Git** [comment] 2023-08-02 17:41
> I did issue a timerint 100000 - but still the same

We shouldn't be allowing a `timerint` value of 1,000,000 (one million). According to everything I'm reading, the number of microseconds that is specified for `usleep` must be _less than_ 1,000,000 (one million).

We should probably define `MAX_TOD_UPDATE_USECS` (in `featall.h`) to 999,999 instead _(and update our documentation accordingly).

**Comment by Fish-Git** [comment] 2023-08-02 17:43
@ivan-w: Please note the updated research patch: I added a test in the `rubato_thread` as well.

**Comment by Fish-Git** [comment] 2023-08-05 05:10
Fixed by commit 87d04ed9ef521623fe75b810519ce1a84af2ccfd.

Closing.

**Comment by Peter-J-Jansen** [comment] 2023-08-06 12:47
I presume this is an important enough bug to start using this latest commit for it. But unfortunately the Hercules log now shows numerous `HHC00075E Error in function usleep(): Interrupted system call` error messages, or can I just ignore this for the time being ?

Cheers,

Peter
[Hercules_log_312_BD.txt](https://github.com/SDL-Hercules-390/hyperion/files/12269628/Hercules_log_312_BD.txt)

**Comment by Fish-Git** [comment] 2023-08-06 17:32
Should hopefully be fixed now by commit c962c5d6a908901a4ea8d6a2ed9556a4a5cc28eb

Re-closing.

**Closed as completed by Fish-Git** 2023-08-06 17:32 UTC
Labels: BUG, Unknown, TXF

**Comment by ivan-w** [comment] 2023-08-06 19:54
And now the threads are using *DOUBLE* of what they used to (on an intel xeon system)

**Comment by Fish-Git** [comment] 2023-08-06 23:43
> And now the threads are using _DOUBLE_ of what they used to (on an intel xeon system).. and even more on my aarch64 system!

Are you sure you're using commit c962c5d6a908901a4ea8d6a2ed9556a4a5cc28eb?

Are there any `HHC00075E` messages being issued? If so, what are they saying? They should be reporting where the problematic USLEEP() is occurring.

If you _ARE_ using commit c962c5d6a908901a4ea8d6a2ed9556a4a5cc28eb, _AND_ you are _not_ seeing any `HHC00075E` messages however, then I don't know what the fuck is going on, and I give up.

In fact, I'm strongly considering resigning completely from Hercules development altogether. I'm serious. This Linux shit is getting old REAL fucking fast.

You're a fucking Hercules developer. YOU figure it out and fucking fix it.

**Comment by Peter-J-Jansen** [comment] 2023-08-07 13:56
After reading up on "usleep" for Ubuntu and some other Linux variants, I think that automatically retrying following a non-zero RC should not be done.  Even the error reporting could perhaps be useful only in the case of errno!=EINTR.  If I had known this prior to my "HHC00075E" message, some frustrations could have been avoided. I'm sorry about that, with apologies to both Fish and Ivan.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-08-07 15:44
> I think that automatically retrying following a non-zero RC should not be done.

Then what should be done?! How should EINTR be handled?

There is no difference between us automatically retrying it, and the caller not sleeping and calling us again. Either way, the usleep will be immediately retried. Over and over and over again. Continuously. Causing host CPU to be unnecessarily consumed.

Same with EINVAL too.

For EINVAL, we could report it, and then attempt a valid usleep, but even if we do a valid usleep (i.e. even if we fix the caller's error so that EINVAL does not occur), we are still left with the possibility that EINTR could occur!

What do we do if/when EINTR occurs?!

If retrying it keeps continuing to fail, then we're screwed! We're fucked! We can't call nanosleep instead, because the exact same thing will occur! Should we change it to a `sleep` call instead (which sleeps for a number of WHOLE SECONDS)? Based on what I'm reading, it's guaranteed to always succeed and never fail. Why does `usleep` and `nanosleep` fail? How can we RELIABLY sleep for less than one second?!

**Comment by wrljet** [comment] 2023-08-07 20:26
What do I need to do to test this?

With the latest commit, on a Debian x86_64 VM, I don't see any error msgs in the Hercules log, and just sitting there not IPLed, it's using very little CPU.

Bill

**Comment by Fish-Git** [comment] 2023-08-08 00:40
> What do I need to do to test/try this?

I have no freaking idea.

@ivan-w never attached a Hercules log.

Peter attached a log **[to his comment](https://github.com/SDL-Hercules-390/hyperion/issues/589#issuecomment-1666848467)** that reports his version as:
```
14:34:41 HHC01417I Built with: Clang 10.0.0
14:34:41 HHC01417I Build type: GNU/Linux x86_64 host architecture build
[...]
14:34:41 HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
14:34:41 HHC01417I Running on: pjamdz3a (Linux-5.15.0-78-generic x86_64) MP=16
```

Why it works fine on some systems but not on others I have no freaking idea. All I know is shit like this makes me scream and want to pull out what little gray hair I have left, and after dealing with it for the past 20 years I'm getting damn sick and tired of it.

**Comment by Fish-Git** [comment] 2023-08-08 08:00
Maybe the problem is how CPU utilization is being measured or similar type bug?

**Comment by Peter-J-Jansen** [comment] 2023-08-08 09:05
> How should EINTR be handled?

I propose that the current implementation behavior not be changed, i.e. do nothing. The `usleep` man pages (like [here](https://www.man7.org/linux/man-pages/man3/usleep.3.html)), state that EINTR is a signal interruption and that usleep's behavior is then _unspecified._ As the problem as reported is clearly not EINTR related, I propose to not attempting to correct a non-existing problem. I suspect that an EINTR interrupted usleep may effectively result in a shorter than requested sleep time. Just retrying the usleep, until one is not EINTR interrupted, will cause effective sleep times significantly longer than the originally requested sleep time. This would explain the reported _doubled_ thread times.

The man page also mentions that `usleep` is _obsolete_ and should be replaced with `nanosleep`, which does have the ability to restart after an EINTR interruption for the remainder of the time that the thread was not yet sleeping. When replacing usleep with re-started nanosleep for the remaining sleep times, the result can guarantee that the requested sleep time is being observed, but in general the sleep time will be larger that the actually requested sleep time. Also usleep when not EINTR interrupted (i.e. ending with rc==0) behaves that way, but a multiple times interrupted nanosleep may end up with an effective sleep time which is a lot more than the originally requested sleep time.

To me it is clear that `usleep`, and even not (repetitive) `nanosleep`, can guarantee exact sleep times: I suspect _real time required accuracy sleep implementations_ would need to resort to more elaborate or different implementations.

In short : I propose to not alter the current `usleep` behavior when an EINTR occurs, as we currently have no known or reported problem with it.

I have therefore tested the following fix, which should get rid of the _doubled_ thread times :  

```diff
--- SDL-hyperion/hscutl.c	2023-08-08 10:39:00.713698533 +0200
+++ hscutl_pjj_fix.c	2023-08-08 10:36:26.469081326 +0200
@@ -609,13 +609,9 @@
 {
     int  rc, save_errno;
 
-    while (1
+    if (1
         && (rc = usleep( usecs )) != 0
-        && (save_errno = errno) == EINTR
-    )
-        continue;
-
-    if (rc != 0)
+        && (save_errno = errno) != EINTR)
     {
         char fnc[128], msg[128];
 ```
The above has been working fine on my Ubuntu 20.04 system: I will try it next on my Raspberri PI 4 - 8GB Raspbian OS 64-bit system (i.e. Debian based).

Us trying to support so many different OS's is bound to cause difficulties. Even the original bug of an usleep time exceeding 999999 micro seconds apparently will not be problem on all Linux or Unix systems. In retrospect, we could've just fixed that bug, without adding the extra macro to check for EINVAL invalid sleep times, as the vast majority of the usleep() invocations are with hardcoded numbers or constants less than 1000000.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-08-08 10:30
> In short: I propose to not alter the current `usleep` behavior when an EINTR occurs, as we currently have no known or reported problem with it.
> 
> I have therefore tested the following fix, which should get rid of the _doubled_ thread times:

_&lt;snip patch&gt;_

> The above has been working fine on my Ubuntu 20.04 system: I will try it next on my Raspberri PI 4 - 8GB Raspbian OS 64-bit system (i.e. Debian based).

So basically ignore EINTR altogether and only report any error that is _not_ EINTR? Sounds good to me! Unless someone else objects or comes up with a better solution, I say go ahead and make the change, Peter! Thanks!

> Us trying to support so many different OS's is bound to cause difficulties.

No shit! &nbsp;`:)`

> Even the original bug of an usleep time exceeding 999999 micro seconds apparently will not be problem on all Linux or Unix systems.

Yes, I saw that too. But we of course cannot rely on that. In my own quick testing (on Windows) before I fixed `MAX_TOD_UPDATE_USECS` for example, the `rubato_thread` would set `sysblk.txf_timerint` to 1000000 (one million), resulting in a EINVAL error and no sleep occurring. And of course the `timer_thread` would end up using that bad `sysblk.txf_timerint` value in its usleep too, causing the exact same problem to occur, thereby compounding the problem, leading to a hard CPU loop in both threads, consuming all available host CPU time for each of them.

Thus the reason for reporting all EINVAL _(i.e. non-EINTR)_ errors, so such bugs could be identified and eventually fixed.

But I figured EINTR was only a temporary error that likely would not occur on retry. If however, it _continually_ occurs _(i.e. if the cause cannot be "cleared" somehow)_, then yes, we should probably ignore it I guess _(which is what your proposed patch does and is what I agree we should probably do instead_.

> When replacing usleep with re-started nanosleep for the remaining sleep times, the result can guarantee that the requested sleep time is being observed, but in general the sleep time will be larger that the actually requested sleep time.

I would rather have the thread sleep for slightly longer than requested than for it to not sleep at all! I believe it is the "not sleeping at all" that is causing the unusually high CPU time to be consumed. With that in mind, I believe we should strongly consider changing our `herc_usleep` function to call `nanosleep` instead. At least we can then guarantee that the thread _will_ sleep for _**at least**_ the requested amount of time.

So... which should we do? Quick fix `herc_usleep` to not retry EINTR? (i.e. your proposed change/fix), or change it to do a restartable `nanosleep` instead?

Me? I vote for the nanosleep approach (with the same check for, and reporting of, EINVAL).

How do others feel?

_(Yes, I've calmed down a bit now. I've just been having a lot of bad luck with Linux lately, which was greatly affecting me mood-wise. I think the recent threads on the main Hercules group these past few weeks got to me. I apologize to you and Ivan for blowing up like that, but I find myself becoming upset much more easily as I get older, so if it happens again, just remind me to take a few deep breaths.)_ &nbsp;`;-)`

**Comment by ivan-w** [comment] 2023-08-08 12:57
We all have our bad hair day - no ,biggy !

**Comment by Peter-J-Jansen** [comment] 2023-08-08 14:59
Couldn't agree with you more Ivan !

And I also agree with Fish in that the `nanosleep()` approach is the better solution, also in order to stop using the deprecated obsolete `usleep()`. Nevertheless I just committed my proposed stop-gap solution as my tests were successful, so that Ivan can check whether the _doubled_ thread times indeed disappear. My tests neither showed `HHC00075E`'s or increased CPU times.

When `nanosleep()` calls need to be repeated due to EINTR interrupts, I think one could perhaps generate a warning message, or even just an informational messages, when such repeats occur more than say 3 times or so for a given `herc_usleep` call.

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-08-08 16:51
> And I also agree with Fish in that the `nanosleep()` approach is the better solution, also in order to stop using the deprecated obsolete `usleep()`.

Good point. I remember seeing that too. `usleep` was _originally_ defned as a legitimate POSIX function, but was later removed and replaced with a recommendation to use `nanosleep` instead.

> When `nanosleep()` calls need to be repeated due to EINTR interrupts, I think one could perhaps generate a warning message, or even just an informational messages, when such repeats occur more than say 3 times or so for a given `herc_usleep` call.

Another excellent idea. The EINTR could occur more than once for a single call, and we don't want to issue a (warning? informational?) message each time. A message should only be issued if the EINTR occurs more than 'n' number of times in a row (there 'n' is some value such as 3 as you suggested), and even then, it should be issued only once. (If it occurs, say, 10 times in a row on a given call, the (warning? informational?) message should only be issued once.)

Since you suggested it, may I presume you will implement that suggested change, Peter, after Ivan has conformed your temporary stop-gap solution resolves his double CPU issue?

I should also mention that, depending on how often EINTR occurs during normal Hercules processing, that such a "restartable" (retry) nanosleep approach will of course more than likely cause a noticeable increase in CPU time! How much of an increase it caused is unknown however, but there _will_ of course be an increase. Hopefully it will only be a slight (insignificant) increase, but we won't know that until we actually give it a try.

Maybe it can be coded to skip the restart (retry) if the remaining number of nanoseconds is less than a certain threshold value? What should that threshold value be? 1000? (i.e. one microsecond?) Or some slightly larger value?

**Comment by Peter-J-Jansen** [comment] 2023-08-11 14:14
Even whist awaiting feedback on my last stop-gap commit https://github.com/SDL-Hercules-390/hyperion/commit/bf1a5d73cd3cbc51780f302a231c1850a944f5b6 I tried a `nanosleep()` replacement for `usleep()` but one that was _**not**_ good, as it left two threads running at 100% even after performing a shutdown command on my Ubuntu 20.04 system. The `nanosleep(`) implementation I tried went was as follows : 
```diff
--- SDL-hyperion/hscutl.c       2023-08-11 15:55:40.673462497 +0200
+++ hscutl.c    2023-08-11 12:54:50.518908396 +0200
@@ -607,24 +607,54 @@
 /* Hercules microsecond sleep */
 DLL_EXPORT int herc_usleep( useconds_t usecs, const char* file, int line )
 {
-    int  rc, save_errno;
 
-    if (1
-        && (rc = usleep( usecs )) != 0
-        && (save_errno = errno) != EINTR)
+#define USLEEP_MIN 1
+#define NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD 3
+
+    int  rc, save_errno, eintr_retrys = 0;
+
+    struct timespec usecs_left;
+    usecs_left.tv_nsec += usecs * 1000L;
+    usecs_left.tv_sec += usecs_left.tv_nsec / 1000000000;
+    usecs_left.tv_nsec %= 1000000000;
+
+    while ( 1
+        && ( rc = nanosleep( &usecs_left, &usecs_left ) != 0 )
+        && ( 0 
+           || usecs_left.tv_sec != 0  
+           || usecs_left.tv_nsec > ( USLEEP_MIN * 1000 ) )                 
+        && ( eintr_retrys++ ) 
+        && ( save_errno = errno ) != EINTR );
+
+    if ( 0
+       || rc != 0  
+       || eintr_retrys > NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD )            
     {
         char fnc[128], msg[128];
 
         MSGBUF( fnc, "USLEEP() at %s(%d)",
             TRIMLOC( file ), line);
+         
+        if ( save_errno != EINTR )
+        {
+            MSGBUF( msg, "rc=%d, errno=%d: %s",
+                rc, save_errno, strerror( save_errno ));
+
+            // "Error in function %s: %s"
+            WRMSG( HHC00075, "E", fnc, msg );
+            errno = save_errno;
+        }
 
-        MSGBUF( msg, "rc=%d, errno=%d: %s",
-            rc, save_errno, strerror( save_errno ));
+        if ( eintr_retrys > NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD )
+        {
+            MSGBUF( msg, "rc=%d, EINTR retrys count=%d",
+                rc, eintr_retrys );
 
-        // "Error in function %s: %s"
-        WRMSG( HHC00075, "E", fnc, msg );
-        errno = save_errno;
-    }
+#define HHC00092 "Warning in function %s: %s" 
+            // "Warning in function %s: %s"           
+            WRMSG( HHC00092, "W", fnc, msg );
+        }
+    }     
     return rc;
 }
```
But as stated, **_not_** good. (The `#define` statements above would need to be placed in the correct files.)

I will be off-line in a few days time for about 5 weeks (only reading s-mails now and then), but before that I'll still open an Issue which is now perfectly reproducible, but one I have not able to been able to fix. So in case you're bored ...

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-08-11 21:35
> The `nanosleep(`) implementation I tried went was as follows:

Surprisingly, when I compile the above with **clang**, _**I get no warnings whatsoever!**_

When I compile it with **gcc** however, I _correctly_ get the following warnings:
```
hscutl.c: In function ‘herc_usleep’:
hscutl.c:617:24: warning: ‘usecs_left.tv_nsec’ is used uninitialized [-Wuninitialized]
hscutl.c:616:21: note: ‘usecs_left’ declared here
hscutl.c:618:23: warning: ‘usecs_left.tv_sec’ is used uninitialized [-Wuninitialized]
hscutl.c:616:21: note: ‘usecs_left’ declared here
hscutl.c:638:12: warning: ‘save_errno’ may be used uninitialized [-Wmaybe-uninitialized]
```

Trying to compile it on Windows also _correctly_ fails with:
```
hscutl.c(616) : error C2220: warning treated as error - no 'object' file generated
hscutl.c(616) : warning C4700: uninitialized local variable 'usecs_left' used
NMAKE : fatal error U1077: '"cl.EXE"' : return code '0x2'
```

_(it still misses the "may be used uninitialized" for `save_erro` though, but then I think it has unfortunately always done that.)_

Perhaps the above bug(s) are what was causing your problem Peter?

**Comment by Fish-Git** [comment] 2023-08-11 22:38
_**FYI:**_ &nbsp;The following seems to work well for me on Kubuntu 21.10 under VMware:

```diff
--- hyperion-1/hscutl.c	2023-08-08 09:25:22.238314000 -0700
+++ hyperion-0/hscutl.c	2023-08-11 15:09:19.559728700 -0700
@@ -607,23 +607,54 @@
 /* Hercules microsecond sleep */
 DLL_EXPORT int herc_usleep( useconds_t usecs, const char* file, int line )
 {
-    int  rc, save_errno;
+#define USLEEP_MIN                              1
+#define NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD  3
 
-    if (1
-        && (rc = usleep( usecs )) != 0
-        && (save_errno = errno) != EINTR)
+    int  rc, save_errno = 0, eintr_retrys = 0;
+    struct timespec usecs_left;
+
+    usecs_left.tv_nsec = usecs * 1000L;
+    usecs_left.tv_sec  = usecs_left.tv_nsec / ONE_BILLION;
+    usecs_left.tv_nsec %=                     ONE_BILLION;
+
+    while (1
+        && (rc = nanosleep( &usecs_left, &usecs_left )) != 0
+        && (save_errno = errno) == EINTR
+        && (0
+            || usecs_left.tv_sec != 0
+            || usecs_left.tv_nsec > (USLEEP_MIN * 1000)
+           )
+    )
+        ++eintr_retrys; // (keep retrying until done or min reached)
+
+    if (0
+        || rc != 0
+        || eintr_retrys > NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD
+    )
     {
         char fnc[128], msg[128];
 
         MSGBUF( fnc, "USLEEP() at %s(%d)",
             TRIMLOC( file ), line);
 
-        MSGBUF( msg, "rc=%d, errno=%d: %s",
-            rc, save_errno, strerror( save_errno ));
+        if (save_errno != EINTR)
+        {
+            MSGBUF( msg, "rc=%d, errno=%d: %s",
+                rc, save_errno, strerror( save_errno ));
 
-        // "Error in function %s: %s"
-        WRMSG( HHC00075, "E", fnc, msg );
-        errno = save_errno;
+            // "Error in function %s: %s"
+            WRMSG( HHC00075, "E", fnc, msg );
+            errno = save_errno;
+        }
+
+        if (eintr_retrys > NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD)
+        {
+            MSGBUF( msg, "rc=%d, EINTR retrys count=%d",
+                rc, eintr_retrys );
+
+            // "Warning in function %s: %s"
+            WRMSG( HHC00092, "W", fnc, msg );
+        }
     }
     return rc;
 }
@@ -2317,12 +2348,12 @@
 DLL_EXPORT const char* perc2name( BYTE perc, char* buf, size_t bufsiz )
 {   /*
            Hex    Bit   PER Event
-            80     0    Successful-branching 
+            80     0    Successful-branching
             40     1    Instruction-fetching
             20     2    Storage-alteration
             10     3    Storage-key-alteration
-            08     4    Store-using-real-address 
-            04     5    Zero-address-detection 
+            08     4    Store-using-real-address
+            04     5    Zero-address-detection
             02     6    Transaction-end
             01     7    Instruction-fetching nullification (PER-3) */
 
@@ -3325,7 +3356,7 @@
 }
 
 //---------------------------------------------------------------------
-//                    I/O Interrupt 
+//                    I/O Interrupt
 //            (handles both HHC00805 and HHC00806)
 //---------------------------------------------------------------------
 DLL_EXPORT bool tf_0806( REGS* regs, U32 ioid, U32 ioparm, U32 iointid )
@@ -4114,7 +4145,7 @@
 
     if (max_recsize < sizeof( TF01321 ))
         max_recsize = sizeof( TF01321 );
-    
+
     if (max_recsize < sizeof( TF01329 ))
         max_recsize = sizeof( TF01329 );
 
--- hyperion-1/msgenu.h	2023-07-09 17:33:35.000000000 -0700
+++ hyperion-0/msgenu.h	2023-08-11 14:56:41.453140900 -0700
@@ -287,7 +287,8 @@
 #define HHC00089 "The are no HAO rules defined"
 #define HHC00090 "HAO thread waiting for logger facility to become active"
 #define HHC00091 "Logger facility now active; HAO thread proceeding"
-//efine HHC00092 - HHC00099 (available)
+#define HHC00092 "Warning in function %s: %s"
+//efine HHC00093 - HHC00099 (available)
 
 // reserve 100-129 thread related
 #define HHC00100 "Thread id "TIDPAT", prio %d, name '%s' started"
```

**Comment by Peter-J-Jansen** [comment] 2023-08-12 09:09
Yes, thanks for catching my errors. This works for me fine as well (under 1st level (no VMware) Lubunto 20.04). I got a few HHC00092W's, perhaps a slightly increased `NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD  6` would be more appropriate ?

Cheers,

Peter

**Comment by Fish-Git** [comment] 2023-08-12 14:59
> I got a few `HHC00092W`'s, perhaps a slightly increased `NANOSLEEP_EINTR_RETRY_WARNING_TRESHOLD 6` would be more appropriate?

Sounds good to me!

(And I would suggest moving the `#define`s to `hscutil.h` where the `herc_usleep` function is declared too.)

My goal today is to try and reproduce your issue #590 problem.

**Comment by Fish-Git** [comment] 2023-08-24 04:54
### _FYI:_

I have removed the "Researching..." label and have added the "BUG" label as I believe we may have more than likely identified the root cause of the excessive host CPU consumption by the timer thread. Since I am not 100% certain of this however _(we will have to monitor our "fix" to see whether it does indeed fix the problem or not)_, I am leaving the "Unknown" label for now.

Once we have enough evidence (feedback) to reliably conclude the problem has indeed been fixed, I will then remove the "Uknown" label at that time.
